-- ============================================================
-- 정보화실무협의회 테이블 변경 DDL (ALTER)
-- Date    : 2026-04-02
-- Changes :
--   1. BCMMTM  : CM_TP → VLR_TP
--   2. BPOVWM  : 컬럼명 BPROJM 스키마 일치, 타입 변경
--   3. CCODEM  : CTT_TP VARCHAR2(32), 협의회 코드 INSERT
--   4. BPERFM  : CLF/GL_NV/MSM_TPM 추가, MSM_CYC → MSM_CLE
-- ============================================================

-- ─────────────────────────────────────────
-- 1. TAAABB_BCMMTM: CM_TP → VLR_TP (위원유형)
-- ─────────────────────────────────────────
ALTER TABLE TAAABB_BCMMTM RENAME COLUMN CM_TP TO VLR_TP;

-- ─────────────────────────────────────────
-- 2. TAAABB_BPOVWM: BPROJM 스키마 일치
-- ─────────────────────────────────────────
-- 필요성: NCS_MTA VARCHAR2(2000) → NCS VARCHAR2(1000)
ALTER TABLE TAAABB_BPOVWM RENAME COLUMN NCS_MTA TO NCS;
ALTER TABLE TAAABB_BPOVWM MODIFY (NCS VARCHAR2(1000));

-- 전결권자: DCSPE VARCHAR2(200) → EDRT VARCHAR2(32)
ALTER TABLE TAAABB_BPOVWM RENAME COLUMN DCSPE TO EDRT;
ALTER TABLE TAAABB_BPOVWM MODIFY (EDRT VARCHAR2(32));

-- 사업내용: PRJ_CONE VARCHAR2(4000) → PRJ_DES VARCHAR2(1000)
ALTER TABLE TAAABB_BPOVWM RENAME COLUMN PRJ_CONE TO PRJ_DES;
ALTER TABLE TAAABB_BPOVWM MODIFY (PRJ_DES VARCHAR2(1000));

-- 기대효과: XPT_EFF VARCHAR2(2000) → VARCHAR2(1000)
ALTER TABLE TAAABB_BPOVWM MODIFY (XPT_EFF VARCHAR2(1000));

-- 소요예산: SRP_BDT VARCHAR2(100) → PRJ_BG NUMBER (타입 변경: add/drop)
ALTER TABLE TAAABB_BPOVWM RENAME COLUMN SRP_BDT TO SRP_BDT_OLD;
ALTER TABLE TAAABB_BPOVWM ADD PRJ_BG NUMBER;
ALTER TABLE TAAABB_BPOVWM DROP COLUMN SRP_BDT_OLD;

-- ─────────────────────────────────────────
-- 3. TAAABB_CCODEM: CTT_TP 길이 통일 + 협의회 코드 데이터 INSERT
-- ─────────────────────────────────────────
ALTER TABLE TAAABB_CCODEM MODIFY (CTT_TP VARCHAR2(32));

-- DBR_TP (심의유형)
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('DBR_TP-001', 'DBR_TP', 'INFO_SYS', '정보시스템 사업 타당성 검토', 1, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('DBR_TP-002', 'DBR_TP', 'INFO_SEC', '정보보호시스템 사업 타당성 검토', 2, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('DBR_TP-003', 'DBR_TP', 'ETC', '기타(위원장 인정 사항)', 3, 'N', SYSDATE, 'SYSTEM');

-- KPN_TP (저장유형)
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('KPN_TP-001', 'KPN_TP', 'TEMP', '임시저장', 1, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('KPN_TP-002', 'KPN_TP', 'COMPLETE', '작성완료', 2, 'N', SYSDATE, 'SYSTEM');

-- CKG_ITM (타당성 점검항목)
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-001', 'CKG_ITM', 'MGMT_STR', '경영전략/계획 부합', 1, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-002', 'CKG_ITM', 'FIN_EFC', '재무 효과', 2, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-003', 'CKG_ITM', 'RISK_IMP', '리스크 개선 효과', 3, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-004', 'CKG_ITM', 'REP_IMP', '평판/이미지 개선 효과', 4, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-005', 'CKG_ITM', 'DUP_SYS', '유사/중복 시스템 유무', 5, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('CKG_ITM-006', 'CKG_ITM', 'ETC', '기타', 6, 'N', SYSDATE, 'SYSTEM');

-- VLR_TP (위원유형)
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('VLR_TP-001', 'VLR_TP', 'MAND', '당연위원', 1, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('VLR_TP-002', 'VLR_TP', 'CALL', '소집위원', 2, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('VLR_TP-003', 'VLR_TP', 'SECR', '간사', 3, 'N', SYSDATE, 'SYSTEM');

-- ASCT_STS (협의회상태)
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-001', 'ASCT_STS', 'DRAFT', '작성중', 1, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-002', 'ASCT_STS', 'SUBMITTED', '작성완료', 2, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-003', 'ASCT_STS', 'APPROVAL_PENDING', '결재대기', 3, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-004', 'ASCT_STS', 'APPROVED', '결재완료', 4, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-005', 'ASCT_STS', 'PREPARING', '개최준비', 5, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-006', 'ASCT_STS', 'SCHEDULED', '일정확정', 6, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-007', 'ASCT_STS', 'IN_PROGRESS', '진행중', 7, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-008', 'ASCT_STS', 'EVALUATING', '평가중', 8, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-009', 'ASCT_STS', 'RESULT_WRITING', '결과서작성', 9, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-010', 'ASCT_STS', 'RESULT_REVIEW', '결과서검토', 10, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-011', 'ASCT_STS', 'FINAL_APPROVAL', '결과결재', 11, 'N', SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, CTT_TP, C_NM, C_DES, C_SQN, DEL_YN, FST_ENR_DTM, FST_ENR_USID)
VALUES ('ASCT_STS-012', 'ASCT_STS', 'COMPLETED', '완료', 12, 'N', SYSDATE, 'SYSTEM');

-- ─────────────────────────────────────────
-- 4. TAAABB_BPERFM: 컬럼 추가 + MSM_CYC → MSM_CLE
-- ─────────────────────────────────────────
ALTER TABLE TAAABB_BPERFM ADD CLF      VARCHAR2(1000);  -- 산식
ALTER TABLE TAAABB_BPERFM ADD GL_NV    VARCHAR2(200);   -- 목표치
ALTER TABLE TAAABB_BPERFM ADD MSM_TPM  VARCHAR2(100);   -- 측정시점
ALTER TABLE TAAABB_BPERFM RENAME COLUMN MSM_CYC TO MSM_CLE;  -- 주기

COMMIT;
