
  CREATE TABLE "ITPAPP"."TPRMPP_BASCTL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"ASCT_STS_C" VARCHAR2(3 CHAR),
	"CNRC_DT" VARCHAR2(255 CHAR),
	"CNRC_PLC_NM" VARCHAR2(100 CHAR),
	"CNRC_TM" VARCHAR2(6 CHAR),
	"DBR_TC" VARCHAR2(20 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BASCTL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BASCTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_STS_C" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"CNRC_DT" VARCHAR2(255 CHAR),
	"CNRC_PLC_NM" VARCHAR2(100 CHAR),
	"CNRC_TM" VARCHAR2(6 CHAR),
	"DBR_TC" VARCHAR2(20 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BASCTM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BBUGTL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"BG_MNG_NO" VARCHAR2(32 CHAR),
	"BG_SNO" NUMBER(10,0),
	"BG_YY" VARCHAR2(4 CHAR),
	"DUP_RT" NUMBER(10,0),
	"IOE_C" VARCHAR2(3),
	"ORC_PK_VL" VARCHAR2(32 CHAR),
	"ORC_SNO_VL" NUMBER(10,0),
	"ORC_TB" VARCHAR2(10 CHAR),
	"DUP_BG_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BBUGTL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BBUGTM"
   (	"BG_MNG_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"BG_SNO" NUMBER(4,0) NOT NULL ENABLE,
	"BG_YY" VARCHAR2(4 CHAR),
	"ORC_TB" VARCHAR2(10),
	"ORC_PK_VL" VARCHAR2(32),
	"ORC_SNO_VL" NUMBER(4,0),
	"IOE_C" VARCHAR2(3),
	"DUP_RT" NUMBER(3,0),
	"DUP_BG_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_BBUGTM_BG_MNG_NO_BG_SNO" PRIMARY KEY ("BG_MNG_NO", "BG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCHKLC"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_ITM_C" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"CKG_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	 CONSTRAINT "PK_TAAABB_BCHKLC_ASCT_ID_CKG_ITM_C" PRIMARY KEY ("ASCT_ID", "CKG_ITM_C")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCHKLL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_ITM_C" VARCHAR2(20 CHAR),
	"CKG_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BCHKLL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCHKLM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_ITM_C" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"CKG_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCHKLM" PRIMARY KEY ("ASCT_ID", "CKG_ITM_C")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCMMTL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"VLR_TC" VARCHAR2(32 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BCMMTL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCMMTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CNFM_YN" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"VLR_TC" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCMMTM" PRIMARY KEY ("ASCT_ID", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCOSTL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"ABUS_C" VARCHAR2(100 CHAR),
	"BG_YY" VARCHAR2(4 CHAR),
	"CTT_NM" VARCHAR2(800 CHAR),
	"CUR_C" VARCHAR2(3),
	"DFR_CLE_C" VARCHAR2(3),
	"FST_DFR_DT" DATE,
	"INF_PRT_YN" VARCHAR2(4 CHAR),
	"IOE_C" VARCHAR2(3),
	"IT_MNGC_NO" VARCHAR2(32 CHAR),
	"IT_MNGC_SNO" NUMBER(4,0),
	"IT_MNGC_TP" VARCHAR2(100 CHAR),
	"LST_YN" VARCHAR2(4 CHAR),
	"PUL_DTT" VARCHAR2(100 CHAR),
	"XCR_BSE_DT" DATE,
	"XCR" NUMBER(9,4),
	"IND_RSN" VARCHAR2(600),
	"CTT_OPP_NM" VARCHAR2(100),
	"CGPR_ENO" VARCHAR2(32),
	"BICE_TEM_C" VARCHAR2(5 CHAR),
	"BICE_DPM_C" VARCHAR2(3),
	"IT_MNGC_BG_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"FC_AMT" NUMBER(18,3),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BCOSTL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BCOSTM"
   (	"IT_MNGC_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"IT_MNGC_SNO" NUMBER(4,0) NOT NULL ENABLE,
	"ABUS_C" VARCHAR2(100 CHAR),
	"CTT_NM" VARCHAR2(800 CHAR),
	"CUR_C" VARCHAR2(3),
	"DFR_CLE_C" VARCHAR2(3),
	"FST_DFR_DT" DATE,
	"INF_PRT_YN" VARCHAR2(4 CHAR),
	"IOE_C" VARCHAR2(3),
	"PUL_DTT" VARCHAR2(100 CHAR),
	"IT_MNGC_TP" VARCHAR2(100 CHAR),
	"LST_YN" VARCHAR2(4),
	"XCR_BSE_DT" DATE,
	"BG_YY" VARCHAR2(4),
	"CNCD_IT_MNGC_NO" VARCHAR2(32 CHAR),
	"XCR" NUMBER(9,4),
	"IND_RSN" VARCHAR2(600),
	"CTT_OPP_NM" VARCHAR2(100),
	"CGPR_ENO" VARCHAR2(32),
	"BICE_TEM_C" VARCHAR2(5 CHAR),
	"BICE_DPM_C" VARCHAR2(3),
	"IT_MNGC_BG_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"FC_AMT" NUMBER(18,3),
	 CONSTRAINT "PK_TAAABB_BCOSTM_IT_MNGC_NO_IT_MNGC_SNO" PRIMARY KEY ("IT_MNGC_NO", "IT_MNGC_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BEVALL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_ITM_C" VARCHAR2(20 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"CKG_OPNN_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BEVALL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BEVALM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_ITM_C" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_OPNN_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BEVALM" PRIMARY KEY ("ASCT_ID", "CKG_ITM_C", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BGDOCL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"DOC_MNG_NO" VARCHAR2(32 CHAR),
	"DOC_NM" VARCHAR2(200 CHAR),
	"DOC_INF" CLOB,
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BGDOCL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BGDOCM"
   (	"DOC_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"DOC_NM" VARCHAR2(200),
	"DOC_INF" CLOB,
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_BGDOCM_DOC_MNG_NO" PRIMARY KEY ("DOC_MNG_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BITEML"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"BG_FDTN_CONE" VARCHAR2(300),
	"CUR_C" VARCHAR2(3),
	"DFR_CLE_C" VARCHAR2(3),
	"GCL_DTT" VARCHAR2(32 CHAR),
	"GCL_MNG_NO" VARCHAR2(32 CHAR),
	"GCL_NM" VARCHAR2(100 CHAR),
	"GCL_SNO" NUMBER(10,0),
	"INF_PRT_YN" VARCHAR2(1 CHAR),
	"ITR_INFR_YN" VARCHAR2(1 CHAR),
	"LST_YN" VARCHAR2(1 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"XCR_BSE_DT" DATE,
	"IOE_C" VARCHAR2(3),
	"GCL_QTY" NUMBER(10,0),
	"XCR" NUMBER(9,4),
	"ITD_YM" VARCHAR2(6),
	"GCL_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"FC_AMT" NUMBER(18,3),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BITEML" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BITEMM"
   (	"GCL_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"GCL_SNO" NUMBER(4,0) NOT NULL ENABLE,
	"PRJ_MNG_NO" VARCHAR2(32),
	"PRJ_SNO" NUMBER(4,0),
	"IOE_C" VARCHAR2(3),
	"GCL_NM" VARCHAR2(100),
	"CUR_C" VARCHAR2(3),
	"XCR_BSE_DT" DATE,
	"BG_FDTN_CONE" VARCHAR2(300),
	"DFR_CLE_C" VARCHAR2(3),
	"INF_PRT_YN" VARCHAR2(1) DEFAULT 'N',
	"ITR_INFR_YN" VARCHAR2(1) DEFAULT 'N',
	"LST_YN" VARCHAR2(1) DEFAULT 'Y',
	"GCL_QTY" NUMBER(10,0),
	"XCR" NUMBER(9,4),
	"ITD_YM" VARCHAR2(6),
	"GCL_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	"FC_AMT" NUMBER(18,3),
	 CONSTRAINT "PK_TAAABB_BITEMM_GCL_MNG_NO_GCL_SNO" PRIMARY KEY ("GCL_MNG_NO", "GCL_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BMQNAL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"QTN_ID" VARCHAR2(32 CHAR),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"QTN_ENO" VARCHAR2(32 CHAR),
	"REP_ENO" VARCHAR2(32 CHAR),
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BMQNAL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BMQNAM"
   (	"QTN_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"QTN_ENO" VARCHAR2(32 CHAR),
	"REP_ENO" VARCHAR2(32 CHAR),
	 CONSTRAINT "PK_BMQNAM" PRIMARY KEY ("QTN_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPERFL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"DTP_SNO" NUMBER(10,0),
	"CLF" VARCHAR2(1000 CHAR),
	"DTP_CONE" VARCHAR2(1000 CHAR),
	"DTP_NM" VARCHAR2(200 CHAR),
	"GL_NV_CONE" VARCHAR2(200 CHAR),
	"MSM_CLE" VARCHAR2(100 CHAR),
	"MSM_END_DT" VARCHAR2(255 CHAR),
	"MSM_MANR_CONE" VARCHAR2(1000 CHAR),
	"MSM_PTM_CONE" VARCHAR2(100 CHAR),
	"MSM_STT_DT" VARCHAR2(255 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BPERFL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPERFM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DTP_SNO" NUMBER(10,0) NOT NULL ENABLE,
	"CLF" VARCHAR2(1000 CHAR),
	"DTP_CONE" VARCHAR2(1000 CHAR),
	"DTP_NM" VARCHAR2(200 CHAR),
	"GL_NV_CONE" VARCHAR2(200 CHAR),
	"MSM_CLE" VARCHAR2(100 CHAR),
	"MSM_END_DT" VARCHAR2(255 CHAR),
	"MSM_MANR_CONE" VARCHAR2(1000 CHAR),
	"MSM_PTM_CONE" VARCHAR2(100 CHAR),
	"MSM_STT_DT" VARCHAR2(255 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPERFM" PRIMARY KEY ("ASCT_ID", "DTP_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPLANL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"CPT_BG" NUMBER(15,2),
	"MNGC" NUMBER(15,2),
	"PLN_MNG_NO" VARCHAR2(32 CHAR),
	"PLN_TP" VARCHAR2(16 CHAR),
	"PLN_YY" VARCHAR2(4 CHAR),
	"TTL_BG" NUMBER(15,2),
	"IT_PRJ_CONE" VARCHAR2(4000),
	"IT_BG_CONE" VARCHAR2(4000),
	"IT_PRJ_RMK" VARCHAR2(600),
	"CPIT_BG_RMK" VARCHAR2(600),
	"MNGC_BG_RMK" VARCHAR2(600),
	"PLN_DTL_INF" CLOB,
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BPLANL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPLANM"
   (	"PLN_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"PLN_TP" VARCHAR2(16),
	"PLN_YY" VARCHAR2(4),
	"TTL_BG" NUMBER(15,2),
	"CPT_BG" NUMBER(15,2),
	"MNGC" NUMBER(15,2),
	"IT_PRJ_CONE" VARCHAR2(4000),
	"IT_BG_CONE" VARCHAR2(4000),
	"IT_PRJ_RMK" VARCHAR2(600),
	"CPIT_BG_RMK" VARCHAR2(600),
	"MNGC_BG_RMK" VARCHAR2(600),
	"PLN_DTL_INF" CLOB,
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_BPLANM_PLN_MNG_NO" PRIMARY KEY ("PLN_MNG_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPOVWL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"EDRT_NM" VARCHAR2(100 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"KPN_TC" VARCHAR2(10 CHAR),
	"LGL_RGL_NM" VARCHAR2(500 CHAR),
	"LGL_RGL_YN" VARCHAR2(1 CHAR),
	"NCS_CONE" VARCHAR2(1000 CHAR),
	"PRJ_BG_AMT" NUMBER(18,3),
	"PRJ_DES" VARCHAR2(1000 CHAR),
	"PRJ_NM" VARCHAR2(200 CHAR),
	"PRJ_TRM_CONE" VARCHAR2(100 CHAR),
	"XPT_EFF_CONE" VARCHAR2(1000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"PRJ_BG_AMR" NUMBER(18,3),
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BPOVWL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPOVWM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"EDRT_NM" VARCHAR2(100 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"KPN_TC" VARCHAR2(10 CHAR),
	"LGL_RGL_NM" VARCHAR2(500 CHAR),
	"LGL_RGL_YN" VARCHAR2(1 CHAR),
	"NCS_CONE" VARCHAR2(1000 CHAR),
	"PRJ_BG_AMT" NUMBER(18,3),
	"PRJ_DES" VARCHAR2(1000 CHAR),
	"PRJ_NM" VARCHAR2(200 CHAR),
	"PRJ_TRM_CONE" VARCHAR2(100 CHAR),
	"XPT_EFF_CONE" VARCHAR2(1000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"PRJ_BG_AMR" NUMBER(18,3),
	 CONSTRAINT "PK_BPOVWM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPQNAL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"QTN_ID" VARCHAR2(32 CHAR),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"QTN_ENO" VARCHAR2(32 CHAR),
	"REP_ENO" VARCHAR2(32 CHAR),
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BPQNAL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPQNAM"
   (	"QTN_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"QTN_ENO" VARCHAR2(32 CHAR),
	"REP_ENO" VARCHAR2(32 CHAR),
	 CONSTRAINT "PK_BPQNAM" PRIMARY KEY ("QTN_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPROJA"
   (	"PRJ_MNG_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"BZ_MNG_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_BPROJA_PRJ_MNG_NO_BZ_MNG_NO" PRIMARY KEY ("PRJ_MNG_NO", "BZ_MNG_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPROJL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"BG_YY" VARCHAR2(4 CHAR),
	"BZ_DTT" VARCHAR2(32 CHAR),
	"DPL_YN" VARCHAR2(1 CHAR),
	"EDRT" VARCHAR2(32 CHAR),
	"END_DT" DATE,
	"HRF_PLN" VARCHAR2(1000 CHAR),
	"IT_DPM" VARCHAR2(100 CHAR),
	"IT_DPM_CGPR" VARCHAR2(32 CHAR),
	"IT_DPM_TLR" VARCHAR2(32 CHAR),
	"LBL_FSG_TLM" DATE,
	"LST_YN" VARCHAR2(1 CHAR),
	"MN_USR" VARCHAR2(32 CHAR),
	"NCS" VARCHAR2(1000 CHAR),
	"NYY_PRJ_BG" NUMBER(15,2),
	"ORN_YN" VARCHAR2(1 CHAR),
	"PLM" VARCHAR2(1000 CHAR),
	"PRJ_BG" NUMBER(15,2),
	"PRJ_DES" VARCHAR2(1000 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_NM" VARCHAR2(200 CHAR),
	"PRJ_PUL_PTT" VARCHAR2(3),
	"PRJ_RNG" VARCHAR2(1000 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"PRJ_STS" VARCHAR2(32 CHAR),
	"PRJ_TP" VARCHAR2(100 CHAR),
	"PUL_DTT" VARCHAR2(32 CHAR),
	"PUL_PSG" VARCHAR2(1000 CHAR),
	"RPR_STS" VARCHAR2(32 CHAR),
	"SAF" VARCHAR2(1000 CHAR),
	"STT_DT" DATE,
	"SVN_DPM" VARCHAR2(100 CHAR),
	"SVN_DPM_CGPR" VARCHAR2(32 CHAR),
	"SVN_DPM_TLR" VARCHAR2(32 CHAR),
	"SVN_HDQ" VARCHAR2(32 CHAR),
	"TCHN_TP" VARCHAR2(32 CHAR),
	"XPT_EFF" VARCHAR2(1000 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BPROJL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BPROJM"
   (	"PRJ_MNG_NO" VARCHAR2(255 CHAR),
	"PRJ_SNO" NUMBER(4,0),
	"BG_YY" VARCHAR2(4),
	"PRJ_NM" VARCHAR2(200),
	"PRJ_TP" VARCHAR2(100),
	"SVN_DPM" VARCHAR2(100),
	"IT_DPM" VARCHAR2(100),
	"PRJ_BG" NUMBER(15,2),
	"STT_DT" DATE,
	"END_DT" DATE,
	"SVN_DPM_CGPR" VARCHAR2(32),
	"IT_DPM_CGPR" VARCHAR2(32),
	"SVN_DPM_TLR" VARCHAR2(32),
	"IT_DPM_TLR" VARCHAR2(32),
	"EDRT" VARCHAR2(32),
	"PRJ_DES" VARCHAR2(1000),
	"SAF" VARCHAR2(1000),
	"NCS" VARCHAR2(1000),
	"XPT_EFF" VARCHAR2(1000),
	"PLM" VARCHAR2(1000),
	"PRJ_RNG" VARCHAR2(1000),
	"PUL_PSG" VARCHAR2(1000),
	"HRF_PLN" VARCHAR2(1000),
	"BZ_DTT" VARCHAR2(32),
	"TCHN_TP" VARCHAR2(32),
	"MN_USR" VARCHAR2(32),
	"DPL_YN" VARCHAR2(1) DEFAULT 'N',
	"LBL_FSG_TLM" DATE,
	"RPR_STS" VARCHAR2(32),
	"PRJ_PUL_PTT" VARCHAR2(3),
	"PRJ_STS" VARCHAR2(32),
	"SVN_HDQ" VARCHAR2(32),
	"LST_YN" VARCHAR2(1 CHAR),
	"NYY_PRJ_BG" NUMBER(15,2),
	"ORN_YN" VARCHAR2(1) DEFAULT 'N',
	"PUL_DTT" VARCHAR2(32 CHAR),
	"CNCD_PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_BPROJM_PRJ_MNG_NO_PRJ_SNO" PRIMARY KEY ("PRJ_MNG_NO", "PRJ_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRDOCL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"BZ_DTT" VARCHAR2(32 CHAR),
	"DOC_MNG_NO" VARCHAR2(32 CHAR),
	"DOC_VRS" NUMBER(4,2),
	"FSG_TLM" DATE,
	"REQ_DTT" VARCHAR2(32 CHAR),
	"REQ_NM" VARCHAR2(200 CHAR),
	"REQ_INF" CLOB,
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BRDOCL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRDOCM"
   (	"DOC_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"DOC_VRS" NUMBER(4,2) NOT NULL ENABLE,
	"REQ_NM" VARCHAR2(200),
	"REQ_DTT" VARCHAR2(32),
	"BZ_DTT" VARCHAR2(32),
	"FSG_TLM" DATE,
	"REQ_INF" CLOB,
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_TAAABB_BRDOCM_DOC_MNG_NO_DOC_VRS" PRIMARY KEY ("DOC_MNG_NO", "DOC_VRS")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRIVGL"
   (	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"DOC_MNG_NO" VARCHAR2(32 CHAR),
	"DOC_VRS" NUMBER(5,2),
	"IVG_TP" VARCHAR2(1 CHAR),
	"MARK_ID" VARCHAR2(64 CHAR),
	"QTD_CONE" VARCHAR2(4000 CHAR),
	"RSLV_YN" VARCHAR2(1 CHAR),
	"FSG_YN" VARCHAR2(1 CHAR),
	"IDC_ID" VARCHAR2(64 CHAR),
	"QOT_CONE" VARCHAR2(4000 CHAR),
	"IVG_CONE" VARCHAR2(4000),
	"IVG_SNO" NUMBER(22,0),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BRIVGL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRIVGM"
   (	"IVG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"DOC_MNG_NO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DOC_VRS" NUMBER(5,2) NOT NULL ENABLE,
	"IVG_TP" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"MARK_ID" VARCHAR2(64 CHAR),
	"QTD_CONE" VARCHAR2(4000 CHAR),
	"FSG_YN" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"IDC_ID" VARCHAR2(64 CHAR),
	"QOT_CONE" VARCHAR2(4000 CHAR),
	"IVG_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	 CONSTRAINT "PK_BRIVGM" PRIMARY KEY ("IVG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRSLTL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_OPNN_CONE" VARCHAR2(4000 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"SYN_OPNN_CONE" VARCHAR2(4000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BRSLTL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BRSLTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_OPNN_CONE" VARCHAR2(4000 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"SYN_OPNN_CONE" VARCHAR2(4000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BRSLTM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BSCHDL"
   (	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"DSD_DT" VARCHAR2(8 CHAR),
	"DSD_TM" VARCHAR2(10 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"PSB_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BSCHDL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BSCHDM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DSD_DT" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"DSD_TM" VARCHAR2(10 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"PSB_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BSCHDM" PRIMARY KEY ("ASCT_ID", "DSD_DT", "DSD_TM", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BTERML"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"CGPR_ENO" VARCHAR2(32 CHAR),
	"CUR_C" VARCHAR2(3),
	"DFR_CLE_C" VARCHAR2(3),
	"IT_MNGC_NO" VARCHAR2(32 CHAR),
	"IT_MNGC_SNO" NUMBER(4,0),
	"TMN_MNG_NO" VARCHAR2(32 CHAR),
	"TMN_NM" VARCHAR2(100 CHAR),
	"TMN_SVC" VARCHAR2(100 CHAR),
	"TMN_TUZ_MANR" VARCHAR2(100 CHAR),
	"TMN_USG" VARCHAR2(100 CHAR),
	"XCR_BSE_DT" DATE,
	"XCR" NUMBER(9,4),
	"IND_RSN" VARCHAR2(600),
	"BICE_TEM_C" VARCHAR2(5 CHAR),
	"BICE_DPM_C" VARCHAR2(3),
	"RMK" VARCHAR2(300),
	"TML_AMT" NUMBER(18,3),
	"TMN_SNO" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"FC_AMT" NUMBER(18,3),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_BTERML" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_BTERMM"
   (	"TMN_MNG_NO" VARCHAR2(255 CHAR) NOT NULL ENABLE,
	"TMN_SNO" NUMBER(10,0) NOT NULL ENABLE,
	"IT_MNGC_NO" VARCHAR2(32),
	"IT_MNGC_SNO" NUMBER(4,0),
	"TMN_NM" VARCHAR2(100),
	"TMN_TUZ_MANR" VARCHAR2(100),
	"TMN_USG" VARCHAR2(100),
	"TMN_SVC" VARCHAR2(100),
	"CUR_C" VARCHAR2(3),
	"XCR_BSE_DT" DATE,
	"DFR_CLE_C" VARCHAR2(3),
	"CGPR_ENO" VARCHAR2(32),
	"XCR" NUMBER(9,4),
	"IND_RSN" VARCHAR2(600),
	"BICE_TEM_C" VARCHAR2(5 CHAR),
	"BICE_DPM_C" VARCHAR2(3),
	"RMK" VARCHAR2(300),
	"TML_AMT" NUMBER(18,3),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	"FC_AMT" NUMBER(18,3),
	 CONSTRAINT "PK_TAAABB_BTERMM_TMN" PRIMARY KEY ("TMN_MNG_NO", "TMN_SNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TAAABB_BTERMM_IT_MNGC_NO_IT_MNGC_SNO" FOREIGN KEY ("IT_MNGC_NO", "IT_MNGC_SNO")
	  REFERENCES "ITPAPP"."TPRMPP_BCOSTM" ("IT_MNGC_NO", "IT_MNGC_SNO") ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CAPPLA"
   (	"APF_SNO" NUMBER(9,0) NOT NULL ENABLE,
	"APF_DCM_NO" VARCHAR2(64) NOT NULL ENABLE,
	"FNT_TB_NM" VARCHAR2(120),
	"PK_COL_NM" VARCHAR2(32),
	"FNT_TB_CRY_SNO" NUMBER(4,0),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_CAPPLA" PRIMARY KEY ("APF_DCM_NO", "APF_SNO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TAAABB_CAPPLA_APF_MNG_NO" FOREIGN KEY ("APF_DCM_NO")
	  REFERENCES "ITPAPP"."TPRMPP_CAPPLM" ("APF_DCM_NO") ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CAPPLL"
   (	"LOG_HIS_TGR_SNO" NUMBER(18,0) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	"APF_DCM_NO" VARCHAR2(64 CHAR),
	"APF_PRG_STS_C" VARCHAR2(3 CHAR),
	"DCD_REQ_DTM" DATE,
	"DCD_REQ_INF" CLOB,
	"DCD_REQ_TTL" VARCHAR2(255 CHAR),
	"DCD_REQ_USID" VARCHAR2(14 CHAR),
	"RGPR_DCD_REQ_CONE" VARCHAR2(1000 CHAR),
	 CONSTRAINT "PK_CAPPLL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CAPPLM"
   (	"APF_DCM_NO" VARCHAR2(64) NOT NULL ENABLE,
	"DCD_REQ_USID" VARCHAR2(14),
	"DCD_REQ_DTM" DATE DEFAULT SYSDATE,
	"RGPR_DCD_REQ_CONE" VARCHAR2(1000),
	"DCD_REQ_TTL" VARCHAR2(255),
	"DCD_REQ_INF" CLOB,
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	"APF_PRG_STS_C" VARCHAR2(3) NOT NULL ENABLE,
	"DCD_REQ_BBR_C" VARCHAR2(3),
	 CONSTRAINT "PK_TAAABB_CAPPLM_APF_MNG_NO" PRIMARY KEY ("APF_DCM_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CAUTHI"
   (	"ATH_ID" VARCHAR2(32) NOT NULL ENABLE,
	"QLF_GR_NM" VARCHAR2(200),
	"QLF_GR_MAT" VARCHAR2(600),
	"USE_YN" VARCHAR2(1) DEFAULT 'Y',
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_CAUTHI_ATH_ID" PRIMARY KEY ("ATH_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CBLBCL"
   (	"LOG_HIS_TGR_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (6),
	"CHG_TC" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14),
	"NAC_MNG_NO" VARCHAR2(32),
	"BLB_MNG_NO" VARCHAR2(32),
	"NAC_NM" VARCHAR2(300),
	"NAC_INQ_NBR" NUMBER(10,0),
	"NAC_TP" VARCHAR2(32),
	"KD_C" VARCHAR2(32),
	"PRIT_C" VARCHAR2(32),
	"HRK_FXN_YN" VARCHAR2(1),
	"SRE_YN" VARCHAR2(1),
	"BBR_C" VARCHAR2(8),
	"STT_YMD" DATE,
	"END_YMD" DATE,
	"FL_APG_YN" VARCHAR2(1),
	"FL_NBR" NUMBER(4,0),
	"NAC_GRP_NO" VARCHAR2(32),
	"NAC_GRP_SQN" NUMBER(5,0),
	"NAC_GRP_LEV" NUMBER(2,0),
	"HRK_NAC_MNG_NO" VARCHAR2(32),
	"END_DT" DATE,
	"STT_DT" DATE,
	"NAC_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" TIMESTAMP (6),
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" TIMESTAMP (6),
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	 CONSTRAINT "PK_CBLBCL" PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CBLBCM"
   (	"NAC_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"BLB_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"NAC_NM" VARCHAR2(300) NOT NULL ENABLE,
	"NAC_INQ_NBR" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE,
	"NAC_TP" VARCHAR2(32),
	"KD_C" VARCHAR2(32),
	"PRIT_C" VARCHAR2(32) DEFAULT 'PRIT_C_001' NOT NULL ENABLE,
	"HRK_FXN_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"SRE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"BBR_C" VARCHAR2(8),
	"FL_APG_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"FL_NBR" NUMBER(4,0) DEFAULT 0 NOT NULL ENABLE,
	"NAC_GRP_NO" VARCHAR2(32) NOT NULL ENABLE,
	"NAC_GRP_SQN" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"NAC_GRP_LEV" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"HRK_NAC_MNG_NO" VARCHAR2(32),
	"END_DT" DATE,
	"STT_DT" DATE,
	"NAC_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(10,0) DEFAULT 1,
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" TIMESTAMP (6),
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" TIMESTAMP (6),
	 CONSTRAINT "PK_TAAABB_CBLBCM_NAC_MNG_NO" PRIMARY KEY ("NAC_MNG_NO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TAAABB_CBLBCM_BLB_MNG_NO" FOREIGN KEY ("BLB_MNG_NO")
	  REFERENCES "ITPAPP"."TPRMPP_CBLBMM" ("BLB_MNG_NO") ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CBLBML"
   (	"LOG_HIS_TGR_SNO" NUMBER(19,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"LST_CHG_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"BLB_MNG_NO" VARCHAR2(32 CHAR),
	"BLB_NM" VARCHAR2(100 CHAR),
	"BLB_TC" VARCHAR2(3 CHAR),
	"CMMT_USE_YN" VARCHAR2(1 CHAR),
	"ENR_ATH_C" VARCHAR2(32 CHAR),
	"FL_ESN_YN" VARCHAR2(1 CHAR),
	"HRK_FXN_USE_YN" VARCHAR2(1 CHAR),
	"INQ_ATH_C" VARCHAR2(32 CHAR),
	"KD_USE_YN" VARCHAR2(1 CHAR),
	"NAC_TP_USE_YN" VARCHAR2(1 CHAR),
	"REP_USE_YN" VARCHAR2(1 CHAR),
	"RMK" VARCHAR2(300 CHAR),
	"SRE_SQN_NO" NUMBER(10,0),
	"USE_YN" VARCHAR2(1 CHAR),
	 PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CBLBMM"
   (	"BLB_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"BLB_NM" VARCHAR2(100) NOT NULL ENABLE,
	"BLB_TC" VARCHAR2(3) NOT NULL ENABLE,
	"REP_USE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"CMMT_USE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"FL_ESN_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"HRK_FXN_USE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"NAC_TP_USE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"KD_USE_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"INQ_ATH_C" VARCHAR2(32) DEFAULT 'ALL' NOT NULL ENABLE,
	"ENR_ATH_C" VARCHAR2(32) DEFAULT 'ALL' NOT NULL ENABLE,
	"SRE_SQN_NO" NUMBER(3,0) DEFAULT 0 NOT NULL ENABLE,
	"USE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"RMK" VARCHAR2(300),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(10,0) DEFAULT 1,
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" TIMESTAMP (6),
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" TIMESTAMP (6),
	 CONSTRAINT "PK_TAAABB_CBLBMM_BLB_MNG_NO" PRIMARY KEY ("BLB_MNG_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CCMMTL"
   (	"LOG_HIS_TGR_SNO" NUMBER(19,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"LST_CHG_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"CMMT_CONE" VARCHAR2(4000 CHAR),
	"CMMT_GRP_LEV" NUMBER(10,0),
	"CMMT_GRP_NO" VARCHAR2(32 CHAR),
	"CMMT_GRP_SQN" NUMBER(10,0),
	"CMMT_MNG_NO" VARCHAR2(32 CHAR),
	"HRK_CMMT_MNG_NO" VARCHAR2(32 CHAR),
	"NAC_MNG_NO" VARCHAR2(32 CHAR),
	"SRE_YN" VARCHAR2(1 CHAR),
	 PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CCMMTM"
   (	"CMMT_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"NAC_MNG_NO" VARCHAR2(32) NOT NULL ENABLE,
	"SRE_YN" VARCHAR2(1) DEFAULT 'Y' NOT NULL ENABLE,
	"CMMT_GRP_NO" VARCHAR2(32) NOT NULL ENABLE,
	"CMMT_GRP_SQN" NUMBER(5,0) DEFAULT 0 NOT NULL ENABLE,
	"CMMT_GRP_LEV" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE,
	"HRK_CMMT_MNG_NO" VARCHAR2(32),
	"CMMT_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(10,0) DEFAULT 1,
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" TIMESTAMP (6),
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" TIMESTAMP (6),
	 CONSTRAINT "PK_TAAABB_CCMMTM_CMMT_MNG_NO" PRIMARY KEY ("CMMT_MNG_NO")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TAAABB_CCMMTM_NAC_MNG_NO" FOREIGN KEY ("NAC_MNG_NO")
	  REFERENCES "ITPAPP"."TPRMPP_CBLBCM" ("NAC_MNG_NO") ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CCODEL"
   (	"LOG_HIS_TGR_SNO" NUMBER(19,0) NOT NULL ENABLE,
	"CHG_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"CHG_DTT_YN" VARCHAR2(1 CHAR),
	"CHG_USID" VARCHAR2(14 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"LST_CHG_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"CO_C_ID" VARCHAR2(20 CHAR),
	"CO_C_NM" VARCHAR2(100 CHAR),
	"C_SQN_SNO" NUMBER(10,0),
	"CO_C_INTN_NM" VARCHAR2(200 CHAR),
	"CO_C_INTN_CONE" VARCHAR2(500 CHAR),
	"CDVA_ID" VARCHAR2(40 CHAR),
	"CO_CDVA_ABV_NM" VARCHAR2(100 CHAR),
	"CO_CDVA_SPS" VARCHAR2(2000 CHAR),
	"CO_CDVA_NM" VARCHAR2(500 CHAR),
	"END_DTM" DATE,
	"HRK_CDVA_ID" VARCHAR2(40 CHAR),
	"STT_DTM" DATE,
	"CDVA_NM" VARCHAR2(500 CHAR),
	 PRIMARY KEY ("LOG_HIS_TGR_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CCODEM"
   (	"CO_C_ID" VARCHAR2(20) NOT NULL ENABLE,
	"CDVA_ID" VARCHAR2(40) NOT NULL ENABLE,
	"STT_DTM" DATE NOT NULL ENABLE,
	"CO_C_NM" VARCHAR2(100),
	"C_SQN_SNO" NUMBER(9,0),
	"CO_C_INTN_NM" VARCHAR2(200),
	"CO_C_INTN_CONE" VARCHAR2(500 CHAR),
	"CO_CDVA_ABV_NM" VARCHAR2(100),
	"CO_CDVA_SPS" VARCHAR2(2000),
	"CO_CDVA_NM" VARCHAR2(500),
	"CDVA_NM" VARCHAR2(500 CHAR),
	"END_DTM" DATE,
	"HRK_CDVA_ID" VARCHAR2(40),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	 CONSTRAINT "PK_TAAABB_CCODEM_C_ID_CDVA_STT_DT" PRIMARY KEY ("CO_C_ID", "CDVA_ID", "STT_DTM")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CDECIM"
   (	"APF_DCM_NO" VARCHAR2(64) NOT NULL ENABLE,
	"DCR_SQN_SNO" NUMBER(9,0) NOT NULL ENABLE,
	"DCR_ENO" VARCHAR2(32),
	"DCD_TP_C" VARCHAR2(2),
	"DCD_DTM" DATE,
	"DCR_OPNN_CONE" VARCHAR2(2000),
	"LST_DCD_YN" VARCHAR2(1),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	"DCD_STS_C" VARCHAR2(3) NOT NULL ENABLE,
	 CONSTRAINT "PK_TAAABB_CDECIM_DCD_MNG_NO_DCD_SQN" PRIMARY KEY ("APF_DCM_NO", "DCR_SQN_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CFILEM"
   (	"FL_MPN_ID" VARCHAR2(36) NOT NULL ENABLE,
	"FL_NM" VARCHAR2(100) NOT NULL ENABLE,
	"FL_PYS_NM" VARCHAR2(120) NOT NULL ENABLE,
	"FL_KPN_PTH" VARCHAR2(255) NOT NULL ENABLE,
	"FL_TP_CONE" VARCHAR2(100),
	"PK_COL_NM" VARCHAR2(4000),
	"PK_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_CFILEM_FL_MNG_NO" PRIMARY KEY ("FL_MPN_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CINFMM"
   (	"INFM_MSG_NO" VARCHAR2(30) NOT NULL ENABLE,
	"INFM_SVC_TC" VARCHAR2(2) NOT NULL ENABLE,
	"TTL" VARCHAR2(100),
	"INFM_MSG_CONE" VARCHAR2(4000),
	"INFM_RCD_URL" VARCHAR2(300),
	"RMS_ENO" VARCHAR2(14) NOT NULL ENABLE,
	"INQ_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"INQ_DTM" DATE,
	"SD_TC" VARCHAR2(2),
	"SD_DTM" DATE,
	"SD_DOC_CONE" VARCHAR2(4000),
	"DEL_YN" VARCHAR2(1) DEFAULT 'N' NOT NULL ENABLE,
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER DEFAULT 1,
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" TIMESTAMP (6),
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" TIMESTAMP (6),
	 CONSTRAINT "PK_CINFMM" PRIMARY KEY ("INFM_MSG_NO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CLOGNH"
   (	"LGN_LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"LGN_ERR_RSN" VARCHAR2(600),
	"IP_ADDR" VARCHAR2(20),
	"LGN_DTM" TIMESTAMP (9) NOT NULL ENABLE,
	"LGN_TC" VARCHAR2(1) NOT NULL ENABLE,
	"AGT_VRS_CONE" VARCHAR2(2000 CHAR),
	"DEL_YN" VARCHAR2(1 CHAR),
	"GUID" VARCHAR2(38 CHAR),
	"GUID_PRG_SNO" NUMBER(10,0),
	"FST_ENR_USID" VARCHAR2(14 CHAR),
	"FST_ENR_DTM" TIMESTAMP (9),
	"LST_CHG_USID" VARCHAR2(14 CHAR),
	"LST_CHG_DTM" TIMESTAMP (9),
	 CONSTRAINT "PK_TAAABB_CLOGNH_LGN_SNO" PRIMARY KEY ("LGN_LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CORGNI"
   (	"PRLM_OGZ_C_CONE" VARCHAR2(100) NOT NULL ENABLE,
	"BBR_NM" VARCHAR2(100),
	"BBR_WREN_NM" VARCHAR2(100),
	"PRLM_HRK_OGZ_C_CONE" VARCHAR2(100),
	"ITM_SQN_SNO" NUMBER(9,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_TAAABB_CORGNI_PRLM_OGZ_C_CONE" PRIMARY KEY ("PRLM_OGZ_C_CONE")
  USING INDEX  ENABLE,
	 CONSTRAINT "FK_TAAABB_CORGNI_PRLM_HRK_OGZ_C_CONE" FOREIGN KEY ("PRLM_HRK_OGZ_C_CONE")
	  REFERENCES "ITPAPP"."TPRMPP_CORGNI" ("PRLM_OGZ_C_CONE") ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CROLEI"
   (	"ATH_ID" VARCHAR2(32) NOT NULL ENABLE,
	"ENO" VARCHAR2(32) NOT NULL ENABLE,
	"USE_YN" VARCHAR2(1) DEFAULT 'Y',
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_CROLEI_ATH_ID_ENO" PRIMARY KEY ("ATH_ID", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CRTOKM"
   (	"TOK_SNO" NUMBER(22,0),
	"ENO" VARCHAR2(32) NOT NULL ENABLE,
	"END_DTM" DATE NOT NULL ENABLE,
	"TOK_CONE" VARCHAR2(2000 CHAR) NOT NULL ENABLE,
	"DEL_YN" VARCHAR2(1) DEFAULT 'N',
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE DEFAULT SYSDATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE DEFAULT SYSDATE,
	 CONSTRAINT "PK_TAAABB_CRTOKM_TOK_SNO" PRIMARY KEY ("TOK_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "ITPAPP"."TPRMPP_CUSERI"
   (	"ENO" VARCHAR2(32),
	"USR_ECY_PWD" VARCHAR2(64),
	"BBR_C" VARCHAR2(3),
	"CADR_TPN" VARCHAR2(20),
	"DTC_BBR_C" VARCHAR2(3),
	"DTS_DTL_CONE" VARCHAR2(2000),
	"ETR_MIL_ADDR_NM" VARCHAR2(200),
	"INLE_NO" VARCHAR2(20),
	"PT_C" VARCHAR2(5),
	"PT_C_NM" VARCHAR2(200),
	"TEM_C" VARCHAR2(5),
	"TEM_NM" VARCHAR2(100),
	"USR_NM" VARCHAR2(100),
	"USR_WREN_NM" VARCHAR2(100),
	"CPN_TPN" VARCHAR2(100),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_TAAABB_CUSERI_ENO" PRIMARY KEY ("ENO")
  USING INDEX  ENABLE,
	 CONSTRAINT "SYS_C0011168" CHECK ("FST_ENR_USID" IS NOT NULL) ENABLE,
	 CONSTRAINT "SYS_C0011169" CHECK ("GUID" IS NOT NULL) ENABLE,
	 CONSTRAINT "FK_TAAABB_CUSERI_BBR_C" FOREIGN KEY ("BBR_C")
	  REFERENCES "ITPAPP"."TPRMPP_CORGNI" ("PRLM_OGZ_C_CONE") ENABLE
   ) ;

