-- V20260606_005__SeedItPtlStsTcAndBackfillProjectStatus.sql
-- 정보화포탈 프로젝트상태(IT_PTL_STS_TC) 공통코드 신규 적재 + BPROJM 기존 한글값 코드 백필.
--
-- 배경:
--  - BPROJM.IT_PTL_STS_TC 는 VARCHAR2(2 CHAR) "상태구분코드" 컬럼이나(V20260605_004),
--    데이터는 한글 약어(예산/정실/요건 등 2글자)로 남아 있었고 공통코드도 없었다.
--  - 협의회(정실협) 목록 쿼리가 풀 라벨('예산 작성','계획 작성','정실협 진행중')로 필터링해
--    2자 컬럼과 절대 매칭되지 않아 /api/council 이 항상 빈 배열을 반환했다.
--  - 본 마이그레이션으로 IT_PTL_STS_TC 코드체계(PRD_20260606.md)를 공통코드에 적재하고,
--    기존 한글 데이터를 코드값으로 변환한다.
--
-- 멱등성: IT_PTL_STS_TC 그룹 DELETE 후 재INSERT, 백필 UPDATE 는 한글값 대상 조건이라 재실행 안전.

-- 1) 공통코드 그룹(IT_PTL_STS_TC) 재적재
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'IT_PTL_STS_TC';

INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','01',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 작성중',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','09',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 결재완료',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','11',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 진행중',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','19',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 완료',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','21',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 진행중',5,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','29',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 완료',6,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','31',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 요청 작성중',7,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','32',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 진행중',8,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','39',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 완료',9,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','41',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 요청 작성중',10,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','42',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 진행중',11,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','49',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 완료',12,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','51',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 요청 작성중',13,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','52',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 진행중',14,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','59',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 완료',15,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','61',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 요청 작성중',16,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','62',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 진행중',17,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','69',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 완료',18,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','71',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 작성중',19,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','79',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 완료',20,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

-- 2) 기존 BPROJM 한글 약어 → 코드 백필
--    예산→19(예산편성 작업 완료, 정실협 신청 대상), 정실→21(정실협 진행중), 요건→29(정실협 완료),
--    과심→42(과업심의위원회 진행중), 소요→32(소요예산 산정 진행중), 입찰→52(입찰/계약 진행중),
--    사전→09(예산편성 요청 결재완료)
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '19' WHERE IT_PTL_STS_TC = '예산';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '21' WHERE IT_PTL_STS_TC = '정실';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '29' WHERE IT_PTL_STS_TC = '요건';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '42' WHERE IT_PTL_STS_TC = '과심';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '32' WHERE IT_PTL_STS_TC = '소요';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '52' WHERE IT_PTL_STS_TC = '입찰';
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = '09' WHERE IT_PTL_STS_TC = '사전';

COMMIT;
