-- V20260531_001__CreateRealtimeLogView.sql
-- 실시간 로그 모니터링 화면용 통합 View 및 CHG_DTM 인덱스 보강.
-- 모든 단계는 멱등(idempotent). 재실행에도 안전.

-- 1) CHG_DTM 인덱스 보강 (이미 존재하면 ORA-00955 무시)
DECLARE
    PROCEDURE create_idx(p_idx_name VARCHAR2, p_table VARCHAR2) IS
    BEGIN
        EXECUTE IMMEDIATE 'CREATE INDEX ' || p_idx_name ||
                          ' ON ' || p_table || ' (CHG_DTM)';
    EXCEPTION
        WHEN OTHERS THEN
            IF SQLCODE = -955 THEN NULL;  -- 이미 존재
            ELSE RAISE;
            END IF;
    END;
BEGIN
    create_idx('IX_BASCTL_CHG_DTM',  'TPRMPP_BASCTL');
    create_idx('IX_BBUGTL_CHG_DTM',  'TPRMPP_BBUGTL');
    create_idx('IX_BCHKLL_CHG_DTM',  'TPRMPP_BCHKLL');
    create_idx('IX_BCMMTL_CHG_DTM',  'TPRMPP_BCMMTL');
    create_idx('IX_BCOSTL_CHG_DTM',  'TPRMPP_BCOSTL');
    create_idx('IX_BEVALL_CHG_DTM',  'TPRMPP_BEVALL');
    create_idx('IX_BGDOCL_CHG_DTM',  'TPRMPP_BGDOCL');
    create_idx('IX_BITEML_CHG_DTM',  'TPRMPP_BITEML');
    create_idx('IX_BPERFL_CHG_DTM',  'TPRMPP_BPERFL');
    create_idx('IX_BPLANL_CHG_DTM',  'TPRMPP_BPLANL');
    create_idx('IX_BPOVWL_CHG_DTM',  'TPRMPP_BPOVWL');
    create_idx('IX_BPQNAL_CHG_DTM',  'TPRMPP_BPQNAL');
    create_idx('IX_BPROJL_CHG_DTM',  'TPRMPP_BPROJL');
    create_idx('IX_BRDOCL_CHG_DTM',  'TPRMPP_BRDOCL');
    create_idx('IX_BRIVGL_CHG_DTM',  'TPRMPP_BRIVGL');
    create_idx('IX_BRSLTL_CHG_DTM',  'TPRMPP_BRSLTL');
    create_idx('IX_BSCHDL_CHG_DTM',  'TPRMPP_BSCHDL');
    create_idx('IX_BTERML_CHG_DTM',  'TPRMPP_BTERML');
    create_idx('IX_CAPPLL_CHG_DTM',  'TPRMPP_CAPPLL');
    create_idx('IX_CCODEL_CHG_DTM',  'TPRMPP_CCODEL');
END;
/

-- 2) 통합 View
CREATE OR REPLACE VIEW V_ITPAPP_LOG_FEED AS
SELECT 'TPRMPP_BASCTL' AS LOG_TBL, 'basctm' AS LOG_KEY,
       LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID,
       GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID,
       LST_CHG_DTM, LST_CHG_USID, DEL_YN
  FROM TPRMPP_BASCTL
UNION ALL
SELECT 'TPRMPP_BBUGTL', 'bbugt',  LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BBUGTL
UNION ALL
SELECT 'TPRMPP_BCHKLL', 'bchklc', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BCHKLL
UNION ALL
SELECT 'TPRMPP_BCMMTL', 'bcmmtm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BCMMTL
UNION ALL
SELECT 'TPRMPP_BCOSTL', 'bcostm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BCOSTL
UNION ALL
SELECT 'TPRMPP_BEVALL', 'bevalm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BEVALL
UNION ALL
SELECT 'TPRMPP_BGDOCL', 'bgdocm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BGDOCL
UNION ALL
SELECT 'TPRMPP_BITEML', 'bitemm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BITEML
UNION ALL
SELECT 'TPRMPP_BPERFL', 'bperfm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BPERFL
UNION ALL
SELECT 'TPRMPP_BPLANL', 'bplanm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BPLANL
UNION ALL
SELECT 'TPRMPP_BPOVWL', 'bpovwm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BPOVWL
UNION ALL
SELECT 'TPRMPP_BPQNAL', 'bpqnam', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BPQNAL
UNION ALL
SELECT 'TPRMPP_BPROJL', 'bprojm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BPROJL
UNION ALL
SELECT 'TPRMPP_BRDOCL', 'brdocm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BRDOCL
UNION ALL
SELECT 'TPRMPP_BRIVGL', 'brivgm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BRIVGL
UNION ALL
SELECT 'TPRMPP_BRSLTL', 'brsltm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BRSLTL
UNION ALL
SELECT 'TPRMPP_BSCHDL', 'bschdm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BSCHDL
UNION ALL
SELECT 'TPRMPP_BTERML', 'btermm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_BTERML
UNION ALL
SELECT 'TPRMPP_CAPPLL', 'capplm', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_CAPPLL
UNION ALL
SELECT 'TPRMPP_CCODEL', 'ccodem', LOG_HIS_TGR_SNO, CHG_DTT_YN, CHG_DTM, CHG_USID, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID, DEL_YN FROM TPRMPP_CCODEL;
