-- =============================================================================
-- Phase 3: APF_REL_SNO VARCHAR2(36) -> NUMBER(22)
-- Migration: V20260521_004__fix_sno_number22_phase3_apf.sql
-- Date: 2026-05-21
-- =============================================================================
-- 대상: TAAABB_CAPPLA.APF_REL_SNO
-- 변환식: TO_NUMBER(REGEXP_REPLACE(APF_REL_SNO, '[^0-9]', ''))
-- 예: 'APPL-0000000000000000000000000001' -> 1
-- =============================================================================

ALTER TABLE ITPAPP.TAAABB_CAPPLA ADD TMP_APF_REL_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CAPPLA SET TMP_APF_REL_SNO = TO_NUMBER(REGEXP_REPLACE(APF_REL_SNO, '[^0-9]', '')) WHERE APF_REL_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CAPPLA DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CAPPLA DROP COLUMN APF_REL_SNO;
ALTER TABLE ITPAPP.TAAABB_CAPPLA RENAME COLUMN TMP_APF_REL_SNO TO APF_REL_SNO;
ALTER TABLE ITPAPP.TAAABB_CAPPLA MODIFY APF_REL_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CAPPLA ADD CONSTRAINT PK_CAPPLA PRIMARY KEY (APF_REL_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(APF_REL_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CAPPLA;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CAPPLA'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CAPPLA START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

COMMIT;
