-- 과업심의결과구분코드(TASK_DBR_RLT_TC): 01 승인 / 02 반려 / 03 조건부. 멱등: 그룹 DELETE 후 INSERT.
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'TASK_DBR_RLT_TC';
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('TASK_DBR_RLT_TC', '01', DATE '2026-01-01', DATE '9999-12-31', '과업심의결과', '승인', 1, 'MIGRATION', SYSDATE, 'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('TASK_DBR_RLT_TC', '02', DATE '2026-01-01', DATE '9999-12-31', '과업심의결과', '반려', 2, 'MIGRATION', SYSDATE, 'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('TASK_DBR_RLT_TC', '03', DATE '2026-01-01', DATE '9999-12-31', '과업심의결과', '조건부', 3, 'MIGRATION', SYSDATE, 'N');
COMMIT;
