-- ============================================================
-- 표준명칭 변경: 타입변경 동반 (데이터 보존: ADD→UPDATE→DROP)
-- 생성: _generate_rename.py (보고서 기반, 멱등). 직접 수정 금지.
-- ============================================================

-- TPRMPP_BPROJL: LBL_FSG_TLM -> FLF_FSG_DT (VARCHAR2(8 CHAR))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BPROJL' AND column_name='FLF_FSG_DT';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BPROJL ADD (FLF_FSG_DT VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BPROJL SET FLF_FSG_DT=TO_CHAR(LBL_FSG_TLM,'YYYYMMDD') WHERE LBL_FSG_TLM IS NOT NULL AND FLF_FSG_DT IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BPROJL' AND column_name='LBL_FSG_TLM';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BPROJL DROP COLUMN LBL_FSG_TLM'; END IF;
END;
/

-- TPRMPP_BPROJM: LBL_FSG_TLM -> FLF_FSG_DT (VARCHAR2(8 CHAR))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BPROJM' AND column_name='FLF_FSG_DT';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BPROJM ADD (FLF_FSG_DT VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BPROJM SET FLF_FSG_DT=TO_CHAR(LBL_FSG_TLM,'YYYYMMDD') WHERE LBL_FSG_TLM IS NOT NULL AND FLF_FSG_DT IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BPROJM' AND column_name='LBL_FSG_TLM';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BPROJM DROP COLUMN LBL_FSG_TLM'; END IF;
END;
/

-- TPRMPP_BRDOCL: FSG_TLM -> RVW_FSG_TLM_DT (VARCHAR2(8 CHAR))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BRDOCL' AND column_name='RVW_FSG_TLM_DT';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BRDOCL ADD (RVW_FSG_TLM_DT VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BRDOCL SET RVW_FSG_TLM_DT=TO_CHAR(FSG_TLM,'YYYYMMDD') WHERE FSG_TLM IS NOT NULL AND RVW_FSG_TLM_DT IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BRDOCL' AND column_name='FSG_TLM';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BRDOCL DROP COLUMN FSG_TLM'; END IF;
END;
/

-- TPRMPP_BRDOCM: FSG_TLM -> RVW_FSG_TLM_DT (VARCHAR2(8 CHAR))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BRDOCM' AND column_name='RVW_FSG_TLM_DT';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BRDOCM ADD (RVW_FSG_TLM_DT VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BRDOCM SET RVW_FSG_TLM_DT=TO_CHAR(FSG_TLM,'YYYYMMDD') WHERE FSG_TLM IS NOT NULL AND RVW_FSG_TLM_DT IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BRDOCM' AND column_name='FSG_TLM';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BRDOCM DROP COLUMN FSG_TLM'; END IF;
END;
/

-- TPRMPP_CCMMTL: CMMT_GRP_NO -> CMMT_TGT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='CMMT_TGT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL ADD (CMMT_TGT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTL SET CMMT_TGT_SNO=TO_NUMBER(CMMT_GRP_NO) WHERE CMMT_GRP_NO IS NOT NULL AND CMMT_TGT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='CMMT_GRP_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL DROP COLUMN CMMT_GRP_NO'; END IF;
END;
/

-- TPRMPP_CCMMTL: CMMT_MNG_NO -> CMMT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='CMMT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL ADD (CMMT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTL SET CMMT_SNO=TO_NUMBER(CMMT_MNG_NO) WHERE CMMT_MNG_NO IS NOT NULL AND CMMT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='CMMT_MNG_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL DROP COLUMN CMMT_MNG_NO'; END IF;
END;
/

-- TPRMPP_CCMMTL: HRK_CMMT_MNG_NO -> HRK_CMMT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='HRK_CMMT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL ADD (HRK_CMMT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTL SET HRK_CMMT_SNO=TO_NUMBER(HRK_CMMT_MNG_NO) WHERE HRK_CMMT_MNG_NO IS NOT NULL AND HRK_CMMT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTL' AND column_name='HRK_CMMT_MNG_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTL DROP COLUMN HRK_CMMT_MNG_NO'; END IF;
END;
/

-- TPRMPP_CCMMTM: CMMT_GRP_NO -> CMMT_TGT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='CMMT_TGT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM ADD (CMMT_TGT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTM SET CMMT_TGT_SNO=TO_NUMBER(CMMT_GRP_NO) WHERE CMMT_GRP_NO IS NOT NULL AND CMMT_TGT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='CMMT_GRP_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM DROP COLUMN CMMT_GRP_NO'; END IF;
END;
/

-- TPRMPP_CCMMTM: CMMT_MNG_NO -> CMMT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='CMMT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM ADD (CMMT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTM SET CMMT_SNO=TO_NUMBER(CMMT_MNG_NO) WHERE CMMT_MNG_NO IS NOT NULL AND CMMT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='CMMT_MNG_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM DROP COLUMN CMMT_MNG_NO'; END IF;
END;
/

-- TPRMPP_CCMMTM: HRK_CMMT_MNG_NO -> HRK_CMMT_SNO (NUMBER(9,0))
DECLARE
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='HRK_CMMT_SNO';
  IF has_new=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM ADD (HRK_CMMT_SNO NUMBER(9,0))'; END IF;
END;
/
UPDATE TPRMPP_CCMMTM SET HRK_CMMT_SNO=TO_NUMBER(HRK_CMMT_MNG_NO) WHERE HRK_CMMT_MNG_NO IS NOT NULL AND HRK_CMMT_SNO IS NULL;
DECLARE has_old NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_CCMMTM' AND column_name='HRK_CMMT_MNG_NO';
  IF has_old=1 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CCMMTM DROP COLUMN HRK_CMMT_MNG_NO'; END IF;
END;
/

COMMIT;
