-- =============================================================================
-- 테이블 prefix 변경: TAAABB_ → TPRMPP_
-- Migration: V20260521_006__rename_table_prefix_tprmpp.sql
-- Date: 2026-05-21
-- =============================================================================
-- Oracle ALTER TABLE RENAME: 인덱스/제약조건/FK는 내부 object_id 참조로 자동 유지
-- =============================================================================

ALTER TABLE ITPAPP.TAAABB_BASCTL  RENAME TO TPRMPP_BASCTL;
ALTER TABLE ITPAPP.TAAABB_BASCTM  RENAME TO TPRMPP_BASCTM;
ALTER TABLE ITPAPP.TAAABB_BBUGTL  RENAME TO TPRMPP_BBUGTL;
ALTER TABLE ITPAPP.TAAABB_BBUGTM  RENAME TO TPRMPP_BBUGTM;
ALTER TABLE ITPAPP.TAAABB_BCHKLC  RENAME TO TPRMPP_BCHKLC;
ALTER TABLE ITPAPP.TAAABB_BCHKLL  RENAME TO TPRMPP_BCHKLL;
ALTER TABLE ITPAPP.TAAABB_BCMMTL  RENAME TO TPRMPP_BCMMTL;
ALTER TABLE ITPAPP.TAAABB_BCMMTM  RENAME TO TPRMPP_BCMMTM;
ALTER TABLE ITPAPP.TAAABB_BCOSTL  RENAME TO TPRMPP_BCOSTL;
ALTER TABLE ITPAPP.TAAABB_BCOSTM  RENAME TO TPRMPP_BCOSTM;
ALTER TABLE ITPAPP.TAAABB_BEVALL  RENAME TO TPRMPP_BEVALL;
ALTER TABLE ITPAPP.TAAABB_BEVALM  RENAME TO TPRMPP_BEVALM;
ALTER TABLE ITPAPP.TAAABB_BGDOCL  RENAME TO TPRMPP_BGDOCL;
ALTER TABLE ITPAPP.TAAABB_BGDOCM  RENAME TO TPRMPP_BGDOCM;
ALTER TABLE ITPAPP.TAAABB_BITEML  RENAME TO TPRMPP_BITEML;
ALTER TABLE ITPAPP.TAAABB_BITEMM  RENAME TO TPRMPP_BITEMM;
ALTER TABLE ITPAPP.TAAABB_BPERFL  RENAME TO TPRMPP_BPERFL;
ALTER TABLE ITPAPP.TAAABB_BPERFM  RENAME TO TPRMPP_BPERFM;
ALTER TABLE ITPAPP.TAAABB_BPLANL  RENAME TO TPRMPP_BPLANL;
ALTER TABLE ITPAPP.TAAABB_BPLANM  RENAME TO TPRMPP_BPLANM;
ALTER TABLE ITPAPP.TAAABB_BPOVWL  RENAME TO TPRMPP_BPOVWL;
ALTER TABLE ITPAPP.TAAABB_BPOVWM  RENAME TO TPRMPP_BPOVWM;
ALTER TABLE ITPAPP.TAAABB_BPQNAL  RENAME TO TPRMPP_BPQNAL;
ALTER TABLE ITPAPP.TAAABB_BPQNAM  RENAME TO TPRMPP_BPQNAM;
ALTER TABLE ITPAPP.TAAABB_BPROJA  RENAME TO TPRMPP_BPROJA;
ALTER TABLE ITPAPP.TAAABB_BPROJL  RENAME TO TPRMPP_BPROJL;
ALTER TABLE ITPAPP.TAAABB_BPROJM  RENAME TO TPRMPP_BPROJM;
ALTER TABLE ITPAPP.TAAABB_BRDOCL  RENAME TO TPRMPP_BRDOCL;
ALTER TABLE ITPAPP.TAAABB_BRDOCM  RENAME TO TPRMPP_BRDOCM;
ALTER TABLE ITPAPP.TAAABB_BRIVGL  RENAME TO TPRMPP_BRIVGL;
ALTER TABLE ITPAPP.TAAABB_BRIVGM  RENAME TO TPRMPP_BRIVGM;
ALTER TABLE ITPAPP.TAAABB_BRSLTL  RENAME TO TPRMPP_BRSLTL;
ALTER TABLE ITPAPP.TAAABB_BRSLTM  RENAME TO TPRMPP_BRSLTM;
ALTER TABLE ITPAPP.TAAABB_BSCHDL  RENAME TO TPRMPP_BSCHDL;
ALTER TABLE ITPAPP.TAAABB_BSCHDM  RENAME TO TPRMPP_BSCHDM;
ALTER TABLE ITPAPP.TAAABB_BTERML  RENAME TO TPRMPP_BTERML;
ALTER TABLE ITPAPP.TAAABB_BTERMM  RENAME TO TPRMPP_BTERMM;
ALTER TABLE ITPAPP.TAAABB_CAPPLA  RENAME TO TPRMPP_CAPPLA;
ALTER TABLE ITPAPP.TAAABB_CAPPLL  RENAME TO TPRMPP_CAPPLL;
ALTER TABLE ITPAPP.TAAABB_CAPPLM  RENAME TO TPRMPP_CAPPLM;
ALTER TABLE ITPAPP.TAAABB_CAUTHI  RENAME TO TPRMPP_CAUTHI;
ALTER TABLE ITPAPP.TAAABB_CBLBCL  RENAME TO TPRMPP_CBLBCL;
ALTER TABLE ITPAPP.TAAABB_CBLBCM  RENAME TO TPRMPP_CBLBCM;
ALTER TABLE ITPAPP.TAAABB_CBLBML  RENAME TO TPRMPP_CBLBML;
ALTER TABLE ITPAPP.TAAABB_CBLBMM  RENAME TO TPRMPP_CBLBMM;
ALTER TABLE ITPAPP.TAAABB_CCMMTL  RENAME TO TPRMPP_CCMMTL;
ALTER TABLE ITPAPP.TAAABB_CCMMTM  RENAME TO TPRMPP_CCMMTM;
ALTER TABLE ITPAPP.TAAABB_CCODEL  RENAME TO TPRMPP_CCODEL;
ALTER TABLE ITPAPP.TAAABB_CCODEM  RENAME TO TPRMPP_CCODEM;
ALTER TABLE ITPAPP.TAAABB_CDECIM  RENAME TO TPRMPP_CDECIM;
ALTER TABLE ITPAPP.TAAABB_CFILEM  RENAME TO TPRMPP_CFILEM;
ALTER TABLE ITPAPP.TAAABB_CINFMM  RENAME TO TPRMPP_CINFMM;
ALTER TABLE ITPAPP.TAAABB_CLOGNH  RENAME TO TPRMPP_CLOGNH;
ALTER TABLE ITPAPP.TAAABB_CORGNI  RENAME TO TPRMPP_CORGNI;
ALTER TABLE ITPAPP.TAAABB_CROLEI  RENAME TO TPRMPP_CROLEI;
ALTER TABLE ITPAPP.TAAABB_CRTOKM  RENAME TO TPRMPP_CRTOKM;
ALTER TABLE ITPAPP.TAAABB_CUSERI  RENAME TO TPRMPP_CUSERI;

COMMIT;
