-- 공통 게시판 인덱스 생성
ALTER SESSION SET CURRENT_SCHEMA = ITPAPP;

-- 게시물 목록 조회 (게시판별 + 소프트삭제 + 화면여부 + 상위고정 + 등록일시)
CREATE INDEX IDX_CBLBCM_LIST   ON TAAABB_CBLBCM (BLB_MNG_NO, DEL_YN, SRE_YN, HRK_FXN_YN, FST_ENR_DTM);
-- 답변 트리 조회 (그룹번호 + 그룹순서)
CREATE INDEX IDX_CBLBCM_GRP    ON TAAABB_CBLBCM (NAC_GRP_NO, NAC_GRP_SQN);
-- 상위게시물 역참조
CREATE INDEX IDX_CBLBCM_HRK    ON TAAABB_CBLBCM (HRK_NAC_MNG_NO);
-- 작성자 기반 조회
CREATE INDEX IDX_CBLBCM_AUTHOR ON TAAABB_CBLBCM (FST_ENR_USID, DEL_YN);
-- 담당부서 필터
CREATE INDEX IDX_CBLBCM_BBR    ON TAAABB_CBLBCM (BBR_C);
-- 게시판 메타 사이드바 정렬
CREATE INDEX IDX_CBLBMM_NAV    ON TAAABB_CBLBMM (USE_YN, SRE_SQN_NO);
-- 댓글 목록 조회
CREATE INDEX IDX_CCMMTM_LIST   ON TAAABB_CCMMTM (NAC_MNG_NO, DEL_YN, SRE_YN, FST_ENR_DTM);
-- 댓글 트리 조회
CREATE INDEX IDX_CCMMTM_GRP    ON TAAABB_CCMMTM (CMMT_GRP_NO, CMMT_GRP_SQN);
-- 상위댓글 역참조
CREATE INDEX IDX_CCMMTM_HRK    ON TAAABB_CCMMTM (HRK_CMMT_MNG_NO);
