-- ============================================================
-- V20260512_002: TAAABB_CCODEL_V2 신규 스키마 생성
-- 공통코드 변경로그 V2 — 마스터와 동일 필드셋
-- ============================================================

CREATE TABLE TAAABB_CCODEL_V2 (
    LOG_SNO      NUMBER        NOT NULL,
    CHG_TP       VARCHAR2(10),
    C_ID         VARCHAR2(32),
    CDVA         VARCHAR2(32),
    STT_DT       DATE,
    END_DT       DATE,
    C_NM         VARCHAR2(100),
    C_DES        VARCHAR2(500),
    CDVA_DTL     VARCHAR2(100),
    C_TP         VARCHAR2(100),
    C_TP_DES     VARCHAR2(500),
    HRK_C        VARCHAR2(65),
    C_SQN        NUMBER,
    DEL_YN       VARCHAR2(1),
    GUID         VARCHAR2(36),
    FST_ENR_DTM  TIMESTAMP,
    FST_ENR_USID VARCHAR2(20),
    LST_CHG_DTM  TIMESTAMP,
    LST_CHG_USID VARCHAR2(20),
    CONSTRAINT PK_CCODEL_V2 PRIMARY KEY (LOG_SNO)
);

CREATE SEQUENCE SEQ_CCODEL_V2 START WITH 1 INCREMENT BY 1 NOCACHE;

COMMENT ON TABLE  TAAABB_CCODEL_V2              IS '공통코드 변경로그 V2';
COMMENT ON COLUMN TAAABB_CCODEL_V2.LOG_SNO      IS '로그순번 (자동채번)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.CHG_TP       IS '변경유형 (INSERT/UPDATE/DELETE/MIGRATION)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_ID         IS '코드ID';
COMMENT ON COLUMN TAAABB_CCODEL_V2.CDVA         IS '코드값';
COMMENT ON COLUMN TAAABB_CCODEL_V2.STT_DT       IS '시작일자';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_NM         IS '코드명 (구 CDVA)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_DES        IS '코드설명 (구 CTT_TP_DES)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.CDVA_DTL     IS '코드값상세 (구 C_NM)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_TP         IS '코드타입 (구 CTT_TP)';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_TP_DES     IS '코드타입설명';
COMMENT ON COLUMN TAAABB_CCODEL_V2.HRK_C        IS '상위코드';
COMMENT ON COLUMN TAAABB_CCODEL_V2.C_SQN        IS '코드순서';
