-- 단말기용도 표준화: TMN_USG -> NSF_USG_CONE, VARCHAR2(200)

DECLARE
  has_old NUMBER;
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BTERML' AND column_name='TMN_USG';
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BTERML' AND column_name='NSF_USG_CONE';

  IF has_new=0 AND has_old=1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERML RENAME COLUMN TMN_USG TO NSF_USG_CONE';
  ELSIF has_new=0 AND has_old=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERML ADD (NSF_USG_CONE VARCHAR2(200 CHAR))';
  END IF;
END;
/

DECLARE
  has_old NUMBER;
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BTERMM' AND column_name='TMN_USG';
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BTERMM' AND column_name='NSF_USG_CONE';

  IF has_new=0 AND has_old=1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERMM RENAME COLUMN TMN_USG TO NSF_USG_CONE';
  ELSIF has_new=0 AND has_old=0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERMM ADD (NSF_USG_CONE VARCHAR2(200 CHAR))';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERML MODIFY (NSF_USG_CONE VARCHAR2(200 CHAR))';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN TPRMPP_BTERML.NSF_USG_CONE IS ''소요자금용도내용''';
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERMM MODIFY (NSF_USG_CONE VARCHAR2(200 CHAR))';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN TPRMPP_BTERMM.NSF_USG_CONE IS ''소요자금용도내용''';
END;
/
