-- V20260606_003__WidenAndFillBtermmTerminalCodes.sql
-- Btermm 단말 코드 컬럼이 VARCHAR2(2)로 코드 도메인(3자리: 001~011)보다 좁은
-- 기존 스키마 버그 수정 → VARCHAR2(3)로 확장 후 더티 데이터를 유효 코드로 채움.
-- 멱등: 폭 확장은 현재 길이 < 3일 때만, 채움은 대상 행만.
SET DEFINE OFF

DECLARE
  PROCEDURE widen3(p_col VARCHAR2) IS
    v_len NUMBER;
  BEGIN
    -- CHAR_LENGTH(문자 길이) 기준: VARCHAR2(2 CHAR)는 DATA_LENGTH가 바이트(6)로 나와 부정확
    SELECT CHAR_LENGTH INTO v_len FROM USER_TAB_COLS
      WHERE TABLE_NAME='TPRMPP_BTERMM' AND COLUMN_NAME=p_col;
    IF v_len < 3 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ITPAPP.TPRMPP_BTERMM MODIFY ('||p_col||' VARCHAR2(3 CHAR))';
    END IF;
  END;
BEGIN
  widen3('IT_PTL_TMN_SVC_TC');
  widen3('IT_PTL_TMN_KD_TC');
END;
/

-- IT_PTL_TMN_SVC_TC: NULL → 001~003 랜덤 (결정)
UPDATE ITPAPP.TPRMPP_BTERMM
SET IT_PTL_TMN_SVC_TC = TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(1,4)), 'FM000')
WHERE IT_PTL_TMN_SVC_TC IS NULL;

-- IT_PTL_TMN_KD_TC: 코드값 아닌 행(한글 등) → 001~003 랜덤 (결정)
UPDATE ITPAPP.TPRMPP_BTERMM
SET IT_PTL_TMN_KD_TC = TO_CHAR(TRUNC(DBMS_RANDOM.VALUE(1,4)), 'FM000')
WHERE IT_PTL_TMN_KD_TC IS NULL OR IT_PTL_TMN_KD_TC NOT IN ('001','002','003');

COMMIT;
