-- 계약방법코드(CTT_MANR_C): 01 협상에의한계약 / 02 규격가격동시 / 03 수의계약 / 04 일반경쟁. 멱등: 그룹 DELETE 후 INSERT.
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'CTT_MANR_C';
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('CTT_MANR_C', '01', DATE '2026-01-01', DATE '9999-12-31', '계약방법', '협상에의한계약', 1, 'MIGRATION', SYSDATE, 'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('CTT_MANR_C', '02', DATE '2026-01-01', DATE '9999-12-31', '계약방법', '규격가격동시', 2, 'MIGRATION', SYSDATE, 'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('CTT_MANR_C', '03', DATE '2026-01-01', DATE '9999-12-31', '계약방법', '수의계약', 3, 'MIGRATION', SYSDATE, 'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES ('CTT_MANR_C', '04', DATE '2026-01-01', DATE '9999-12-31', '계약방법', '일반경쟁', 4, 'MIGRATION', SYSDATE, 'N');
COMMIT;
