-- SYS_HRK_MNU_ID 폐기: 그룹핑은 부모 HED(HRK_MNU_ID)가 담당한다.
-- IDX_CMENUM_TREE가 SYS_HRK_MNU_ID를 선두 컬럼으로 포함하므로 인덱스 드롭 → 컬럼 드롭 → 인덱스 재생성.
-- CMENUM, CMENUL 양쪽 컬럼 제거. 멱등성: 존재 여부 확인 후 처리.
DECLARE
    v NUMBER;
BEGIN
    SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CMENUM_TREE';
    IF v > 0 THEN EXECUTE IMMEDIATE 'DROP INDEX IDX_CMENUM_TREE'; END IF;

    SELECT COUNT(*) INTO v FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'TPRMPP_CMENUM' AND COLUMN_NAME = 'SYS_HRK_MNU_ID';
    IF v > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CMENUM DROP COLUMN SYS_HRK_MNU_ID'; END IF;

    SELECT COUNT(*) INTO v FROM USER_TAB_COLS
     WHERE TABLE_NAME = 'TPRMPP_CMENUL' AND COLUMN_NAME = 'SYS_HRK_MNU_ID';
    IF v > 0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_CMENUL DROP COLUMN SYS_HRK_MNU_ID'; END IF;

    SELECT COUNT(*) INTO v FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_CMENUM_TREE';
    IF v = 0 THEN
        EXECUTE IMMEDIATE 'CREATE INDEX IDX_CMENUM_TREE ON TPRMPP_CMENUM (HRK_MNU_ID, MNU_SOT_SQN_SNO)';
    END IF;
END;
/
