-- V20260512_012__fix_log_sno_underscore_to_dash.sql
-- 로그 테이블 일련번호(LOG_SNO) 및 관리번호 컬럼 구분자 통일
-- Underbar(_) → Dash(-) 전환 / 23개 로그 테이블 전체
--
-- LOG_SNO 형식: {POSTFIX}_{22자리숫자} → {POSTFIX}-{22자리숫자}
--   예: BCOSTL_0000000000000000000001 → BCOSTL-0000000000000000000001
--
-- 로그 테이블은 타 테이블로부터 FK 참조를 받지 않으므로 제약 비활성화 불필요

-- ============================================================
-- STEP 1: LOG_SNO PK 변환 (23개 로그 테이블)
-- ============================================================

UPDATE TAAABB_BASCTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BBUGTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BCHKLL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BCMMTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BCOSTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BEVALL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BGDOCL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BITEML
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BPERFL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BPLANL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BPOVWL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BPQNAL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BPROJL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BRDOCL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BRIVGL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BRSLTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BSCHDL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_BTERML
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_CAPPLL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_CBLBCL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_CBLBML
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_CCMMTL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

UPDATE TAAABB_CCODEL
   SET LOG_SNO = REGEXP_REPLACE(LOG_SNO, '^([A-Z][A-Z0-9]+)_([0-9]+)$', '\1-\2')
 WHERE REGEXP_LIKE(LOG_SNO, '^[A-Z][A-Z0-9]+_[0-9]+$');

-- ============================================================
-- STEP 2: 관리번호 FK 컬럼 변환
-- ============================================================

-- PRJ_MNG_NO: PRJ_YYYY_NNNN → PRJ-YYYY-NNNN
-- 대상: TAAABB_BASCTL, TAAABB_BPROJL, TAAABB_BITEML
UPDATE TAAABB_BASCTL
   SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
 WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

UPDATE TAAABB_BPROJL
   SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
 WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

UPDATE TAAABB_BITEML
   SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
 WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

-- IT_MNGC_NO: COST_YYYY_NNNN → COST-YYYY-NNNN
-- 대상: TAAABB_BCOSTL, TAAABB_BTERML
UPDATE TAAABB_BCOSTL
   SET IT_MNGC_NO = REGEXP_REPLACE(IT_MNGC_NO, '^COST_([0-9]{4})_([0-9]+)$', 'COST-\1-\2')
 WHERE REGEXP_LIKE(IT_MNGC_NO, '^COST_[0-9]{4}_[0-9]+$');

UPDATE TAAABB_BTERML
   SET IT_MNGC_NO = REGEXP_REPLACE(IT_MNGC_NO, '^COST_([0-9]{4})_([0-9]+)$', 'COST-\1-\2')
 WHERE REGEXP_LIKE(IT_MNGC_NO, '^COST_[0-9]{4}_[0-9]+$');

-- TMN_MNG_NO: TER_YYYY_NNNN → TER-YYYY-NNNN
-- 대상: TAAABB_BTERML
UPDATE TAAABB_BTERML
   SET TMN_MNG_NO = REGEXP_REPLACE(TMN_MNG_NO, '^TER_([0-9]{4})_([0-9]+)$', 'TER-\1-\2')
 WHERE REGEXP_LIKE(TMN_MNG_NO, '^TER_[0-9]{4}_[0-9]+$');

-- APF_MNG_NO: APF_YYYYNNNNNNNN → APF-YYYY-NNNNNNNN
-- 대상: TAAABB_CAPPLL
UPDATE TAAABB_CAPPLL
   SET APF_MNG_NO = REGEXP_REPLACE(APF_MNG_NO, '^APF_([0-9]{4})([0-9]{8})$', 'APF-\1-\2')
 WHERE REGEXP_LIKE(APF_MNG_NO, '^APF_[0-9]{4}[0-9]{8}$');

-- GCL_MNG_NO: {PREFIX}_YYYY_NNNN → {PREFIX}-YYYY-NNNN
-- 대상: TAAABB_BITEML
UPDATE TAAABB_BITEML
   SET GCL_MNG_NO = REGEXP_REPLACE(GCL_MNG_NO, '^([A-Z]+)_([0-9]{4})_([0-9]+)$', '\1-\2-\3')
 WHERE REGEXP_LIKE(GCL_MNG_NO, '^[A-Z]+_[0-9]{4}_[0-9]+$');

COMMIT;
