-- V20260606_009__InsertFeasibilityCouncilStatusAndRenumber.sql
-- IT_PTL_STS_TC 공통코드에 '타당성검토 정실협'(31/32/39) 추가 후, 기존 3X 이후 코드를 한 단계(+10) 순연.
--
-- 변경 전(20개) → 변경 후(23개):
--   31 소요예산 요청작성중  → 41,  32 소요예산 진행중 → 42,  39 소요예산 완료 → 49
--   41 과업심의위 요청작성중 → 51,  42 과업심의위 진행중 → 52, 49 과업심의위 완료 → 59
--   51 입찰/계약 요청작성중  → 61,  52 입찰/계약 진행중 → 62, 59 입찰/계약 완료 → 69
--   61 대금지급 요청작성중   → 71,  62 대금지급 진행중 → 72, 69 대금지급 완료 → 79
--   71 성과평가 작성중       → 81,  79 성과평가 완료 → 89
--   (신규) 31 타당성검토 정실협 요청작성중 / 32 진행중 / 39 완료
--   01~29(예산편성·정보기술부문계획 정실협)는 불변 → 협의회 로직(21/29/19) 영향 없음.
--
-- 멱등성: BPROJM 데이터 순연은 '재적재 전 구(舊) 레이아웃 판정' 가드로 1회만 수행.
--         CCODEM 그룹은 DELETE 후 재INSERT(목표 23개) 라 재실행 안전.

-- 1) BPROJM 사업상태 데이터 순연 (CCODEM 재적재 '전'에, 구 레이아웃일 때만 1회)
--    CASE 는 '구 값' 기준 평가라 연쇄 이동 없음. 31~79 → +10.
DECLARE
  v_old_layout NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_old_layout
    FROM ITPAPP.TPRMPP_CCODEM
   WHERE CO_C_ID = 'IT_PTL_STS_TC' AND CDVA_ID = '31'
     AND DEL_YN = 'N' AND CDVA_NM LIKE '소요예산%';
  IF v_old_layout > 0 THEN
    UPDATE ITPAPP.TPRMPP_BPROJM
       SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC
             WHEN '31' THEN '41' WHEN '32' THEN '42' WHEN '39' THEN '49'
             WHEN '41' THEN '51' WHEN '42' THEN '52' WHEN '49' THEN '59'
             WHEN '51' THEN '61' WHEN '52' THEN '62' WHEN '59' THEN '69'
             WHEN '61' THEN '71' WHEN '62' THEN '72' WHEN '69' THEN '79'
             WHEN '71' THEN '81' WHEN '79' THEN '89'
             ELSE IT_PTL_STS_TC
           END
     WHERE IT_PTL_STS_TC IN ('31','32','39','41','42','49','51','52','59','61','62','69','71','79');
  END IF;
END;
/

-- 2) CCODEM 그룹(IT_PTL_STS_TC) 목표 23개로 재적재
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'IT_PTL_STS_TC';

INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','01',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 작성중',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','09',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 결재완료',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','11',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 진행중',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','19',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 완료',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','21',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 진행중',5,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','29',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 완료',6,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','31',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 요청 작성중',7,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','32',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 진행중',8,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','39',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 완료',9,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','41',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 요청 작성중',10,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','42',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 진행중',11,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','49',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 완료',12,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','51',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 요청 작성중',13,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','52',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 진행중',14,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','59',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 완료',15,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','61',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 요청 작성중',16,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','62',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 진행중',17,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','69',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 완료',18,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','71',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 요청 작성중',19,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','72',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 진행중',20,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','79',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 완료',21,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','81',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 작성중',22,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','89',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 완료',23,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

COMMIT;
