-- GCL_QTT → GCL_QTY 컬럼명 표준화 및 타입 변경 (NUMBER(9) → NUMBER(10))
-- 대상 테이블: TAAABB_BITEMM (품목), TAAABB_BITEMM_L (품목 이력)
-- 멱등성 보장: 컬럼이 이미 GCL_QTY 인 경우 RENAME 건너뜀

-- 1) TAAABB_BITEMM
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TAAABB_BITEMM' AND COLUMN_NAME = 'GCL_QTT';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_BITEMM RENAME COLUMN GCL_QTT TO GCL_QTY';
    END IF;

    SELECT COUNT(*) INTO v_cnt
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TAAABB_BITEMM' AND COLUMN_NAME = 'GCL_QTY';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_BITEMM MODIFY (GCL_QTY NUMBER(10))';
    END IF;
END;
/

-- 2) TAAABB_BITEMM_L (이력 테이블)
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TAAABB_BITEMM_L' AND COLUMN_NAME = 'GCL_QTT';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_BITEMM_L RENAME COLUMN GCL_QTT TO GCL_QTY';
    END IF;

    SELECT COUNT(*) INTO v_cnt
      FROM USER_TAB_COLUMNS
     WHERE TABLE_NAME = 'TAAABB_BITEMM_L' AND COLUMN_NAME = 'GCL_QTY';
    IF v_cnt > 0 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TAAABB_BITEMM_L MODIFY (GCL_QTY NUMBER(10))';
    END IF;
END;
/

-- 컬럼 코멘트 재적용
COMMENT ON COLUMN TAAABB_BITEMM.GCL_QTY IS '품목수량';
COMMENT ON COLUMN TAAABB_BITEMM_L.GCL_QTY IS '품목수량';
