-- ============================================================
-- V20260512_011: 관리번호 구분자 통일 (Underscore → Dash)
--
-- 실제 FK 제약 (user_constraints 조회 확인):
--   TAAABB_BTERMM.FKK58AD6SHPR5X8SFABNUMIPUMY → TAAABB_BCOSTM(IT_MNGC_NO, IT_MNGC_SNO)
--   TAAABB_CAPPLA.FK_TAAABB_CAPPLA_APF         → TAAABB_CAPPLM(APF_MNG_NO)
--
-- PK 변경 전 FK 제약을 ALTER TABLE DDL로 비활성화하고
-- 모든 UPDATE 완료 후 재활성화합니다.
-- (Flyway는 PL/SQL BEGIN...END;/ 미지원 → ORA-00900 우회)
-- ============================================================

ALTER SESSION SET CURRENT_SCHEMA = ITPAPP;

-- ============================================================
-- STEP 1: FK 제약 비활성화
-- ============================================================

ALTER TABLE TAAABB_BTERMM DISABLE CONSTRAINT FKK58AD6SHPR5X8SFABNUMIPUMY;
ALTER TABLE TAAABB_CAPPLA DISABLE CONSTRAINT FK_TAAABB_CAPPLA_APF;

-- ============================================================
-- STEP 2: PK 컬럼 변환
-- ============================================================

-- 2-1. CAPPLM.APF_MNG_NO (PK): APF_YYYYNNNNNNNN → APF-YYYY-NNNNNNNN
UPDATE TAAABB_CAPPLM
SET APF_MNG_NO = REGEXP_REPLACE(APF_MNG_NO, '^APF_([0-9]{4})([0-9]{8})$', 'APF-\1-\2')
WHERE REGEXP_LIKE(APF_MNG_NO, '^APF_[0-9]{12}$');

-- 2-2. BCOSTM.IT_MNGC_NO (PK): COST_YYYY_NNNN → COST-YYYY-NNNN
UPDATE TAAABB_BCOSTM
SET IT_MNGC_NO = REGEXP_REPLACE(IT_MNGC_NO, '^COST_([0-9]{4})_([0-9]+)$', 'COST-\1-\2')
WHERE REGEXP_LIKE(IT_MNGC_NO, '^COST_[0-9]{4}_[0-9]+$');

-- 2-3. BPROJM.PRJ_MNG_NO (PK, 방어적): PRJ_YYYY_NNNN → PRJ-YYYY-NNNN
UPDATE TAAABB_BPROJM
SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

-- 2-4. CAPPLA.APF_REL_SNO: APPL_NNN... → APPL-NNN...
UPDATE TAAABB_CAPPLA
SET APF_REL_SNO = REGEXP_REPLACE(APF_REL_SNO, '^APPL_([0-9]+)$', 'APPL-\1')
WHERE REGEXP_LIKE(APF_REL_SNO, '^APPL_[0-9]+$');

-- ============================================================
-- STEP 3: FK 컬럼 변환
-- ============================================================

-- 3-1. CAPPLA.APF_MNG_NO (FK → CAPPLM): APF_YYYYNNNNNNNN → APF-YYYY-NNNNNNNN
UPDATE TAAABB_CAPPLA
SET APF_MNG_NO = REGEXP_REPLACE(APF_MNG_NO, '^APF_([0-9]{4})([0-9]{8})$', 'APF-\1-\2')
WHERE REGEXP_LIKE(APF_MNG_NO, '^APF_[0-9]{12}$');

-- 3-2. CAPPLA.ORC_PK_VL → BCOSTM 참조: COST_YYYY_NNNN → COST-YYYY-NNNN
UPDATE TAAABB_CAPPLA
SET ORC_PK_VL = REGEXP_REPLACE(ORC_PK_VL, '^COST_([0-9]{4})_([0-9]+)$', 'COST-\1-\2')
WHERE ORC_TB_CD = 'BCOSTM'
  AND REGEXP_LIKE(ORC_PK_VL, '^COST_[0-9]{4}_[0-9]+$');

-- 3-3. CAPPLA.ORC_PK_VL → BPROJM 참조 (방어적): PRJ_YYYY_NNNN → PRJ-YYYY-NNNN
UPDATE TAAABB_CAPPLA
SET ORC_PK_VL = REGEXP_REPLACE(ORC_PK_VL, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
WHERE ORC_TB_CD = 'BPROJM'
  AND REGEXP_LIKE(ORC_PK_VL, '^PRJ_[0-9]{4}_[0-9]+$');

-- 3-4. CDECIM.DCD_MNG_NO (FK → CAPPLM): APF_YYYYNNNNNNNN → APF-YYYY-NNNNNNNN
UPDATE TAAABB_CDECIM
SET DCD_MNG_NO = REGEXP_REPLACE(DCD_MNG_NO, '^APF_([0-9]{4})([0-9]{8})$', 'APF-\1-\2')
WHERE REGEXP_LIKE(DCD_MNG_NO, '^APF_[0-9]{12}$');

-- 3-5. BTERMM.IT_MNGC_NO (FK → BCOSTM): COST_YYYY_NNNN → COST-YYYY-NNNN
UPDATE TAAABB_BTERMM
SET IT_MNGC_NO = REGEXP_REPLACE(IT_MNGC_NO, '^COST_([0-9]{4})_([0-9]+)$', 'COST-\1-\2')
WHERE REGEXP_LIKE(IT_MNGC_NO, '^COST_[0-9]{4}_[0-9]+$');

-- 3-6. BTERMM.TMN_MNG_NO: TER_YYYY_NNNN → TER-YYYY-NNNN
UPDATE TAAABB_BTERMM
SET TMN_MNG_NO = REGEXP_REPLACE(TMN_MNG_NO, '^TER_([0-9]{4})_([0-9]+)$', 'TER-\1-\2')
WHERE REGEXP_LIKE(TMN_MNG_NO, '^TER_[0-9]{4}_[0-9]+$');

-- 3-7. BITEMM.PRJ_MNG_NO (FK, 방어적): PRJ_YYYY_NNNN → PRJ-YYYY-NNNN
UPDATE TAAABB_BITEMM
SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

-- 3-8. BPROJA.PRJ_MNG_NO (FK, 방어적): PRJ_YYYY_NNNN → PRJ-YYYY-NNNN
UPDATE TAAABB_BPROJA
SET PRJ_MNG_NO = REGEXP_REPLACE(PRJ_MNG_NO, '^PRJ_([0-9]{4})_([0-9]+)$', 'PRJ-\1-\2')
WHERE REGEXP_LIKE(PRJ_MNG_NO, '^PRJ_[0-9]{4}_[0-9]+$');

COMMIT;

-- ============================================================
-- STEP 4: FK 제약 재활성화 (데이터 정합성 검증 포함)
-- ============================================================

ALTER TABLE TAAABB_BTERMM ENABLE CONSTRAINT FKK58AD6SHPR5X8SFABNUMIPUMY;
ALTER TABLE TAAABB_CAPPLA ENABLE CONSTRAINT FK_TAAABB_CAPPLA_APF;
