-- =====================================================================
-- V20260602_006 컬럼 코멘트 누락 보강
-- 출처: 백엔드 엔티티 @Column(comment=...) SoT
-- 멱등: COMMENT ON COLUMN 은 재실행 시 동일값 덮어쓰기 (안전)
-- =====================================================================

-- ---------- LOG_HIS_TGR_SNO : 로그이력전문일련번호 (전 *L 로그 테이블) ----------
COMMENT ON COLUMN "TPRMPP_BASCTL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BBUGTL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BCHKLL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BCMMTL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BCOSTL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BEVALL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BGDOCL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BITEML"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BMQNAL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BPERFL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BPLANL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BPOVWL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BPQNAL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BPROJL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BRDOCL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BRIVGL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BRSLTL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BSCHDL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_BTERML"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';
COMMENT ON COLUMN "TPRMPP_CBLBCL"."LOG_HIS_TGR_SNO" IS '로그이력전문일련번호';

-- ---------- CHG_DTT_YN : 변경구분여부 (전 *L 로그 테이블) ----------
COMMENT ON COLUMN "TPRMPP_BASCTL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BBUGTL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BCHKLL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BCMMTL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BCOSTL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BEVALL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BGDOCL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BITEML"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BMQNAL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BPERFL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BPLANL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BPOVWL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BPQNAL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BPROJL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BRDOCL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BRIVGL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BRSLTL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BSCHDL"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_BTERML"."CHG_DTT_YN" IS '변경구분여부';
COMMENT ON COLUMN "TPRMPP_CBLBCL"."CHG_DTT_YN" IS '변경구분여부';

-- ---------- 도메인 컬럼 ----------
-- FLF_FSG_DT : 의무완료기한
COMMENT ON COLUMN "TPRMPP_BPROJL"."FLF_FSG_DT" IS '의무완료기한';
COMMENT ON COLUMN "TPRMPP_BPROJM"."FLF_FSG_DT" IS '의무완료기한';

-- FSG_YN : 완료여부
COMMENT ON COLUMN "TPRMPP_BRIVGL"."FSG_YN" IS '완료여부';
COMMENT ON COLUMN "TPRMPP_BRIVGM"."FSG_YN" IS '완료여부';

-- FST_DFR_DT : 지급예정월
COMMENT ON COLUMN "TPRMPP_BCOSTL"."FST_DFR_DT" IS '지급예정월';
COMMENT ON COLUMN "TPRMPP_BCOSTM"."FST_DFR_DT" IS '지급예정월';

-- IPM_OPNN_SNO : 의견일련번호
COMMENT ON COLUMN "TPRMPP_BRIVGL"."IPM_OPNN_SNO" IS '의견일련번호';
COMMENT ON COLUMN "TPRMPP_BRIVGM"."IPM_OPNN_SNO" IS '의견일련번호';

-- IT_MNGC_NO : 전산관리비관리번호
COMMENT ON COLUMN "TPRMPP_BTERMM"."IT_MNGC_NO" IS '전산관리비관리번호';

-- RFR_CONE : 인용내용
COMMENT ON COLUMN "TPRMPP_BRIVGL"."RFR_CONE" IS '인용내용';
COMMENT ON COLUMN "TPRMPP_BRIVGM"."RFR_CONE" IS '인용내용';

-- RFR_ID : 표시ID
COMMENT ON COLUMN "TPRMPP_BRIVGL"."RFR_ID" IS '표시ID';
COMMENT ON COLUMN "TPRMPP_BRIVGM"."RFR_ID" IS '표시ID';

-- RPL_OPNN_TC : 의견유형
COMMENT ON COLUMN "TPRMPP_BRIVGL"."RPL_OPNN_TC" IS '의견유형';
COMMENT ON COLUMN "TPRMPP_BRIVGM"."RPL_OPNN_TC" IS '의견유형';

-- RVW_FSG_TLM_DT : 완료기한
COMMENT ON COLUMN "TPRMPP_BRDOCL"."RVW_FSG_TLM_DT" IS '완료기한';
COMMENT ON COLUMN "TPRMPP_BRDOCM"."RVW_FSG_TLM_DT" IS '완료기한';

-- TMN_SNO : 단말기일련번호
COMMENT ON COLUMN "TPRMPP_BTERML"."TMN_SNO" IS '단말기일련번호';
COMMENT ON COLUMN "TPRMPP_BTERMM"."TMN_SNO" IS '단말기일련번호';

-- TMN_USG : 단말기용도
COMMENT ON COLUMN "TPRMPP_BTERML"."TMN_USG" IS '단말기용도';
COMMENT ON COLUMN "TPRMPP_BTERMM"."TMN_USG" IS '단말기용도';

-- XCR_BSE_DT : 환율기준일자
COMMENT ON COLUMN "TPRMPP_BCOSTL"."XCR_BSE_DT" IS '환율기준일자';
COMMENT ON COLUMN "TPRMPP_BCOSTM"."XCR_BSE_DT" IS '환율기준일자';
COMMENT ON COLUMN "TPRMPP_BITEML"."XCR_BSE_DT" IS '환율기준일자';
COMMENT ON COLUMN "TPRMPP_BITEMM"."XCR_BSE_DT" IS '환율기준일자';
COMMENT ON COLUMN "TPRMPP_BTERML"."XCR_BSE_DT" IS '환율기준일자';
COMMENT ON COLUMN "TPRMPP_BTERMM"."XCR_BSE_DT" IS '환율기준일자';

COMMIT;
