-- V20260521_002__fix_sno_number_phase2.sql
-- TMN_SNO, DTP_SNO, ITM_SQN_SNO: VARCHAR2 -> NUMBER

-- ─────────────────────────────────────────
-- 1. TMN_SNO: VARCHAR2(32/255) -> NUMBER(10)
--    BTERMM(마스터, VARCHAR2 PK) + BTERML(로그, 스냅샷)
-- ─────────────────────────────────────────

-- [BTERMM 마스터] PK 교체
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (TMN_SNO_NEW NUMBER(10));
UPDATE ITPAPP.TAAABB_BTERMM SET TMN_SNO_NEW = TO_NUMBER(TMN_SNO);
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP PRIMARY KEY;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN TMN_SNO;
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN TMN_SNO_NEW TO TMN_SNO;
ALTER TABLE ITPAPP.TAAABB_BTERMM MODIFY (TMN_SNO NUMBER(10) NOT NULL);
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD CONSTRAINT PK_TAAABB_BTERMM_TMN PRIMARY KEY (TMN_MNG_NO, TMN_SNO);

-- [BTERML 로그] 스냅샷 컬럼 (PK=LOG_SNO, 변경 없음)
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (TMN_SNO_NEW NUMBER(10));
UPDATE ITPAPP.TAAABB_BTERML SET TMN_SNO_NEW = TO_NUMBER(TMN_SNO) WHERE TMN_SNO IS NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN TMN_SNO;
ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN TMN_SNO_NEW TO TMN_SNO;

-- ─────────────────────────────────────────
-- 2. DTP_SNO: VARCHAR2(32) -> NUMBER(10)
--    BPERFM(마스터, 데이터 없음) + BPERFL(로그, 스냅샷)
--    데이터가 없으므로 DROP+ADD 방식 사용
-- ─────────────────────────────────────────

-- [BPERFM 마스터] PK 포함
ALTER TABLE ITPAPP.TAAABB_BPERFM DROP PRIMARY KEY;
ALTER TABLE ITPAPP.TAAABB_BPERFM DROP COLUMN DTP_SNO;
ALTER TABLE ITPAPP.TAAABB_BPERFM ADD (DTP_SNO NUMBER(10));
ALTER TABLE ITPAPP.TAAABB_BPERFM MODIFY (DTP_SNO NUMBER(10) NOT NULL);
ALTER TABLE ITPAPP.TAAABB_BPERFM ADD CONSTRAINT PK_TAAABB_BPERFM_DTP PRIMARY KEY (ASCT_ID, DTP_SNO);

-- [BPERFL 로그] 스냅샷 컬럼
ALTER TABLE ITPAPP.TAAABB_BPERFL DROP COLUMN DTP_SNO;
ALTER TABLE ITPAPP.TAAABB_BPERFL ADD (DTP_SNO NUMBER(10));

-- ─────────────────────────────────────────
-- 3. ITM_SQN_SNO: VARCHAR2(9) -> NUMBER(9) (정렬용 비-PK 컬럼)
-- ─────────────────────────────────────────
ALTER TABLE ITPAPP.TAAABB_CORGNI ADD (ITM_SQN_SNO_NEW NUMBER(9));
UPDATE ITPAPP.TAAABB_CORGNI
   SET ITM_SQN_SNO_NEW = TO_NUMBER(ITM_SQN_SNO)
 WHERE ITM_SQN_SNO IS NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CORGNI DROP COLUMN ITM_SQN_SNO;
ALTER TABLE ITPAPP.TAAABB_CORGNI RENAME COLUMN ITM_SQN_SNO_NEW TO ITM_SQN_SNO;

COMMIT;
