-- 컬럼 표준화
--   ITD_DT   → ITD_YM       : VARCHAR2(6)
--   IND_RSN                  : VARCHAR2(600)
--   CTT_OPP  → CTT_OPP_NM   : VARCHAR2(100)
--   CGPR     → CGPR_ENO     : VARCHAR2(32)
--   BICE_TEM → BICE_TEM_C   : VARCHAR2(3)
--   BICE_DPM → BICE_DPM_C   : VARCHAR2(3)
--
-- 변경 방식
--   - 타입 축소 또는 컬럼명 변경+축소: 기존 컬럼을 _BAK 으로 백업 RENAME →
--     목표 이름/사이즈로 신규 컬럼 ADD → SUBSTR 복사 → _BAK DROP.
--   - 단순 RENAME (사이즈 동일): RENAME COLUMN.

-- ============================================================
-- 1) ITD_DT → ITD_YM : VARCHAR2(6)
--    대상: TAAABB_BITEMM, TAAABB_BITEML
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BITEMM RENAME COLUMN ITD_DT TO ITD_DT_BAK;
ALTER TABLE ITPAPP.TAAABB_BITEMM ADD (ITD_YM VARCHAR2(6));
UPDATE ITPAPP.TAAABB_BITEMM SET ITD_YM = SUBSTR(ITD_DT_BAK, 1, 6);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEMM DROP COLUMN ITD_DT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.ITD_YM IS '추진년월';

ALTER TABLE ITPAPP.TAAABB_BITEML RENAME COLUMN ITD_DT TO ITD_DT_BAK;
ALTER TABLE ITPAPP.TAAABB_BITEML ADD (ITD_YM VARCHAR2(6));
UPDATE ITPAPP.TAAABB_BITEML SET ITD_YM = SUBSTR(ITD_DT_BAK, 1, 6);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEML DROP COLUMN ITD_DT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.ITD_YM IS '추진년월';

-- ============================================================
-- 2) IND_RSN : VARCHAR2(600) — 사이즈 축소 (이름 동일)
--    대상: TAAABB_BTERMM(1000→600), TAAABB_BTERML(1000→600),
--         TAAABB_BCOSTM(4000→600), TAAABB_BCOSTL(4000→600)
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN IND_RSN TO IND_RSN_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (IND_RSN VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BTERMM SET IND_RSN = SUBSTR(IND_RSN_BAK, 1, 600);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN IND_RSN_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.IND_RSN IS '증감사유';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN IND_RSN TO IND_RSN_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (IND_RSN VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BTERML SET IND_RSN = SUBSTR(IND_RSN_BAK, 1, 600);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN IND_RSN_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.IND_RSN IS '증감사유';

ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN IND_RSN TO IND_RSN_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (IND_RSN VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BCOSTM SET IND_RSN = SUBSTR(IND_RSN_BAK, 1, 600);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN IND_RSN_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.IND_RSN IS '증감사유';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN IND_RSN TO IND_RSN_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (IND_RSN VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BCOSTL SET IND_RSN = SUBSTR(IND_RSN_BAK, 1, 600);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN IND_RSN_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.IND_RSN IS '증감사유';

-- ============================================================
-- 3) CTT_OPP → CTT_OPP_NM : VARCHAR2(100) — 이름 변경 + 사이즈 축소(400→100)
--    대상: TAAABB_BCOSTM, TAAABB_BCOSTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN CTT_OPP TO CTT_OPP_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (CTT_OPP_NM VARCHAR2(100));
UPDATE ITPAPP.TAAABB_BCOSTM SET CTT_OPP_NM = SUBSTR(CTT_OPP_BAK, 1, 100);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN CTT_OPP_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.CTT_OPP_NM IS '계약상대처명';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN CTT_OPP TO CTT_OPP_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (CTT_OPP_NM VARCHAR2(100));
UPDATE ITPAPP.TAAABB_BCOSTL SET CTT_OPP_NM = SUBSTR(CTT_OPP_BAK, 1, 100);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN CTT_OPP_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.CTT_OPP_NM IS '계약상대처명';

-- ============================================================
-- 4) CGPR → CGPR_ENO : VARCHAR2(32)
--    BTERMM/BTERML (32→32) : 단순 RENAME
--    BCOSTM/BCOSTL (128→32) : 백업→신규→복사→DROP
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN CGPR TO CGPR_ENO;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.CGPR_ENO IS '담당자행번';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN CGPR TO CGPR_ENO;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.CGPR_ENO IS '담당자행번';

ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN CGPR TO CGPR_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (CGPR_ENO VARCHAR2(32));
UPDATE ITPAPP.TAAABB_BCOSTM SET CGPR_ENO = SUBSTR(CGPR_BAK, 1, 32);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN CGPR_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.CGPR_ENO IS '담당자행번';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN CGPR TO CGPR_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (CGPR_ENO VARCHAR2(32));
UPDATE ITPAPP.TAAABB_BCOSTL SET CGPR_ENO = SUBSTR(CGPR_BAK, 1, 32);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN CGPR_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.CGPR_ENO IS '담당자행번';

-- ============================================================
-- 5) BICE_TEM → BICE_TEM_C : VARCHAR2(3) — 이름 변경 + 축소(100→3)
--    대상: TAAABB_BTERMM, TAAABB_BTERML, TAAABB_BCOSTM, TAAABB_BCOSTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN BICE_TEM TO BICE_TEM_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (BICE_TEM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BTERMM SET BICE_TEM_C = SUBSTR(BICE_TEM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN BICE_TEM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.BICE_TEM_C IS '담당팀코드';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN BICE_TEM TO BICE_TEM_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (BICE_TEM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BTERML SET BICE_TEM_C = SUBSTR(BICE_TEM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN BICE_TEM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.BICE_TEM_C IS '담당팀코드';

ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN BICE_TEM TO BICE_TEM_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (BICE_TEM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BCOSTM SET BICE_TEM_C = SUBSTR(BICE_TEM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN BICE_TEM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.BICE_TEM_C IS '담당팀코드';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN BICE_TEM TO BICE_TEM_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (BICE_TEM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BCOSTL SET BICE_TEM_C = SUBSTR(BICE_TEM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN BICE_TEM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.BICE_TEM_C IS '담당팀코드';

-- ============================================================
-- 6) BICE_DPM → BICE_DPM_C : VARCHAR2(3) — 이름 변경 + 축소(100→3)
--    대상: TAAABB_BTERMM, TAAABB_BTERML, TAAABB_BCOSTM, TAAABB_BCOSTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN BICE_DPM TO BICE_DPM_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (BICE_DPM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BTERMM SET BICE_DPM_C = SUBSTR(BICE_DPM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN BICE_DPM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.BICE_DPM_C IS '담당부서코드';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN BICE_DPM TO BICE_DPM_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (BICE_DPM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BTERML SET BICE_DPM_C = SUBSTR(BICE_DPM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN BICE_DPM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.BICE_DPM_C IS '담당부서코드';

ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN BICE_DPM TO BICE_DPM_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (BICE_DPM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BCOSTM SET BICE_DPM_C = SUBSTR(BICE_DPM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN BICE_DPM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.BICE_DPM_C IS '담당부서코드';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN BICE_DPM TO BICE_DPM_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (BICE_DPM_C VARCHAR2(3));
UPDATE ITPAPP.TAAABB_BCOSTL SET BICE_DPM_C = SUBSTR(BICE_DPM_BAK, 1, 3);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN BICE_DPM_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.BICE_DPM_C IS '담당부서코드';
