-- V20260607_002__CreateEstimateTables.sql
-- 소요예산 산정 마스터(BESTIM) + 팀별 산정 명세(BESTID) + 변경로그(BESTIL/BESTIDL) + 시퀀스.
-- ddl-auto=validate 이므로 엔티티 작성 전 본 스크립트를 먼저 실행한다.

CREATE TABLE TPRMPP_BESTIM (
  RQM_BG_REQ_DOC_NO VARCHAR2(30 CHAR) NOT NULL,
  DOC_VRS_SNO       NUMBER(9,0)       NOT NULL,
  LST_YN            VARCHAR2(1 CHAR)  DEFAULT 'Y' NOT NULL,
  BG_PRN_TC         VARCHAR2(3 CHAR)  NOT NULL,
  CNCD_RFR_NO       VARCHAR2(30 CHAR) NOT NULL,
  IT_PTL_STS_TC     VARCHAR2(2 CHAR)  NOT NULL,
  REQ_CONE          VARCHAR2(300 CHAR),
  DEL_YN            VARCHAR2(1 CHAR)  DEFAULT 'N' NOT NULL,
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BESTIM PRIMARY KEY (RQM_BG_REQ_DOC_NO, DOC_VRS_SNO),
  CONSTRAINT CK_BESTIM_LST_YN CHECK (LST_YN IN ('Y','N')),
  CONSTRAINT CK_BESTIM_DEL_YN CHECK (DEL_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BESTIM                   IS '소요예산 산정 기본';
COMMENT ON COLUMN TPRMPP_BESTIM.RQM_BG_REQ_DOC_NO IS '소요예산요청문서번호';
COMMENT ON COLUMN TPRMPP_BESTIM.DOC_VRS_SNO       IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BESTIM.LST_YN            IS '최종여부';
COMMENT ON COLUMN TPRMPP_BESTIM.BG_PRN_TC         IS '예산성격구분코드(대상구분)';
COMMENT ON COLUMN TPRMPP_BESTIM.CNCD_RFR_NO       IS '관련참조번호(대상관리번호)';
COMMENT ON COLUMN TPRMPP_BESTIM.IT_PTL_STS_TC     IS 'IT포탈상태구분코드';
COMMENT ON COLUMN TPRMPP_BESTIM.REQ_CONE          IS '요청내용';
CREATE INDEX IDX_BESTIM_TGT ON TPRMPP_BESTIM (BG_PRN_TC, CNCD_RFR_NO);
CREATE INDEX IDX_BESTIM_STS ON TPRMPP_BESTIM (IT_PTL_STS_TC);

CREATE TABLE TPRMPP_BESTID (
  RQM_BG_REQ_DOC_NO VARCHAR2(30 CHAR) NOT NULL,
  DOC_VRS_SNO       NUMBER(9,0)       NOT NULL,
  SVN_TEM_C         VARCHAR2(5 CHAR)  NOT NULL,
  IOE_C             VARCHAR2(7 CHAR)  NOT NULL,
  RQM_BG_AMT        NUMBER(18,0),
  OPNN_CONE         VARCHAR2(1000 CHAR),
  DEL_YN            VARCHAR2(1 CHAR)  DEFAULT 'N' NOT NULL,
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BESTID PRIMARY KEY (RQM_BG_REQ_DOC_NO, DOC_VRS_SNO, SVN_TEM_C, IOE_C),
  CONSTRAINT CK_BESTID_DEL_YN CHECK (DEL_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BESTID                   IS '소요예산 산정 상세(팀별 산정)';
COMMENT ON COLUMN TPRMPP_BESTID.RQM_BG_REQ_DOC_NO IS '소요예산요청문서번호';
COMMENT ON COLUMN TPRMPP_BESTID.DOC_VRS_SNO       IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BESTID.SVN_TEM_C         IS '담당팀코드';
COMMENT ON COLUMN TPRMPP_BESTID.IOE_C             IS '비목코드';
COMMENT ON COLUMN TPRMPP_BESTID.RQM_BG_AMT        IS '소요예산금액';
COMMENT ON COLUMN TPRMPP_BESTID.OPNN_CONE         IS '의견내용';

CREATE TABLE TPRMPP_BESTIL (
  LOG_HIS_TGR_SNO   NUMBER(18,0) NOT NULL,
  CHG_DTT_YN        VARCHAR2(1 CHAR),
  CHG_DTM           TIMESTAMP(9),
  CHG_USID          VARCHAR2(14 CHAR),
  DEL_YN            VARCHAR2(1 CHAR),
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  RQM_BG_REQ_DOC_NO VARCHAR2(30 CHAR),
  DOC_VRS_SNO       NUMBER(9,0),
  LST_YN            VARCHAR2(1 CHAR),
  BG_PRN_TC         VARCHAR2(3 CHAR),
  CNCD_RFR_NO       VARCHAR2(30 CHAR),
  IT_PTL_STS_TC     VARCHAR2(2 CHAR),
  REQ_CONE          VARCHAR2(300 CHAR),
  CONSTRAINT PK_TPRMPP_BESTIL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE TPRMPP_BESTIL IS '소요예산 산정 기본 변경 로그';

CREATE TABLE TPRMPP_BESTIDL (
  LOG_HIS_TGR_SNO   NUMBER(18,0) NOT NULL,
  CHG_DTT_YN        VARCHAR2(1 CHAR),
  CHG_DTM           TIMESTAMP(9),
  CHG_USID          VARCHAR2(14 CHAR),
  DEL_YN            VARCHAR2(1 CHAR),
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  RQM_BG_REQ_DOC_NO VARCHAR2(30 CHAR),
  DOC_VRS_SNO       NUMBER(9,0),
  SVN_TEM_C         VARCHAR2(5 CHAR),
  IOE_C             VARCHAR2(7 CHAR),
  RQM_BG_AMT        NUMBER(18,0),
  OPNN_CONE         VARCHAR2(1000 CHAR),
  CONSTRAINT PK_TPRMPP_BESTIDL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE TPRMPP_BESTIDL IS '소요예산 산정 상세 변경 로그';

CREATE SEQUENCE SEQ_BESTIM  START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BESTIL  START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BESTIDL START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
