-- =============================================================================
-- V20260622_002__RenameCodeGroupsAndSeedCouncilCodes.sql
-- CCODEM 스키마 변경(V20260622_001: CO_C_ID→CO_C_ID_NM, STT_DTM→STT_DT(VARCHAR2(8)),
-- END_DTM→END_DT(VARCHAR2(8))) 이후 적용.
--
-- 1) 공통코드 그룹 식별자(CO_C_ID_NM) 메타 표준 명칭으로 일괄 변경(구→신).
--    구 값이 모두 존재한다는 가정으로 5개 모두 UPDATE 한다.
--    (구 값이 없으면 해당 UPDATE는 0건 처리될 뿐, 문장 자체는 항상 포함한다.)
--      ASCT_PRG_STS_TC -> IT_PTL_ASCT_PRG_STS_TC
--      DBR_TC          -> IT_PTL_ASCT_DBR_TC
--      VLR_TC          -> IT_PTL_ASCT_MEB_TC
--      CKG_ITM_C       -> IT_PTL_CKG_ITM_TC
--      KPN_TC          -> KPN_TP_TC
--
-- 2) 협의회 핵심 3개 그룹(IT_PTL_ASCT_PRG_STS_TC / IT_PTL_ASCT_DBR_TC /
--    IT_PTL_ASCT_MEB_TC) 데이터 시드. 그룹별 DELETE 후 재INSERT라 멱등(재실행 안전).
--
-- 날짜 컬럼은 VARCHAR2(8) yyyyMMdd 문자열('20260101' ~ '99991231').
-- 소유 스키마 ITPOWN. PK = (CO_C_ID_NM, CDVA_ID, STT_DT).
-- =============================================================================

-- 1) 그룹 식별자 rename (구→신) — 5개 모두 포함
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'IT_PTL_ASCT_PRG_STS_TC' WHERE CO_C_ID_NM = 'ASCT_PRG_STS_TC';
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'IT_PTL_ASCT_DBR_TC'     WHERE CO_C_ID_NM = 'DBR_TC';
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'IT_PTL_ASCT_MEB_TC'     WHERE CO_C_ID_NM = 'VLR_TC';
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'IT_PTL_CKG_ITM_TC'      WHERE CO_C_ID_NM = 'CKG_ITM_C';
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'KPN_TP_TC'              WHERE CO_C_ID_NM = 'KPN_TC';

-- 2) 협의회 핵심 3개 그룹 시드 ---------------------------------------------------

-- 2-1) IT_PTL_ASCT_PRG_STS_TC — 협의회진행상태 (01~13)
DELETE FROM ITPOWN.TPRMPP_CCODEM WHERE CO_C_ID_NM = 'IT_PTL_ASCT_PRG_STS_TC';
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','01','20260101','99991231',NULL,'협의회진행상태','요청서 작성 중',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','02','20260101','99991231',NULL,'협의회진행상태','요청서 작성 완료',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','03','20260101','99991231',NULL,'협의회진행상태','요청서 결재 대기',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','04','20260101','99991231',NULL,'협의회진행상태','요청서 결재 완료',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','05','20260101','99991231',NULL,'협의회진행상태','협의회 개최 준비',5,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','06','20260101','99991231',NULL,'협의회진행상태','협의회 일정 확정',6,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','07','20260101','99991231',NULL,'협의회진행상태','협의회 진행 중',7,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','08','20260101','99991231',NULL,'협의회진행상태','평가의견 작성 중',8,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','09','20260101','99991231',NULL,'협의회진행상태','결과서 작성 중',9,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','10','20260101','99991231',NULL,'협의회진행상태','결과서 검토 중',10,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','11','20260101','99991231',NULL,'협의회진행상태','결과보고 결재 대기',11,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','12','20260101','99991231',NULL,'협의회진행상태','결과보고 결재 중',12,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_PRG_STS_TC','13','20260101','99991231',NULL,'협의회진행상태','완료',13,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

-- 2-2) IT_PTL_ASCT_DBR_TC — 협의회심의구분 (01~05, types/council.ts HearingType 기준)
--   01 중기계획 수립 / 02 IT계획 수립 / 03 정보시스템 사업 / 04 정보보호 사업 / 05 기타
DELETE FROM ITPOWN.TPRMPP_CCODEM WHERE CO_C_ID_NM = 'IT_PTL_ASCT_DBR_TC';
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_DBR_TC','01','20260101','99991231',NULL,'협의회심의구분','중기계획 수립',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_DBR_TC','02','20260101','99991231',NULL,'협의회심의구분','IT계획 수립',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_DBR_TC','03','20260101','99991231',NULL,'협의회심의구분','정보시스템 사업',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_DBR_TC','04','20260101','99991231',NULL,'협의회심의구분','정보보호시스템 사업',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_DBR_TC','05','20260101','99991231',NULL,'협의회심의구분','기타',5,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

-- 2-3) IT_PTL_ASCT_MEB_TC — 협의회위원유형 (01 당연 / 02 소집 / 03 간사)
DELETE FROM ITPOWN.TPRMPP_CCODEM WHERE CO_C_ID_NM = 'IT_PTL_ASCT_MEB_TC';
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_MEB_TC','01','20260101','99991231',NULL,'협의회위원유형','당연위원',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_MEB_TC','02','20260101','99991231',NULL,'협의회위원유형','소집위원',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_ASCT_MEB_TC','03','20260101','99991231',NULL,'협의회위원유형','간사',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

COMMIT;
