-- 정보화 예산 금액 컬럼 메타사전 정합 (마스터 + 변경로그 미러 동시 적용)
--   메타 SoT(C:\it\table.csv) 기준으로 현재 DB를 정렬한다. 항목:
--   1) 컬럼명+코멘트  : TPRMPP_BPROJM/BPROJL  MPL_XP_AMT(예정비용금액) -> MPL_MNGC_AMT(예정관리비금액)
--   2) 컬럼타입       : TPRMPP_BTERMM/BTERML  AMT  NUMBER(18,0) -> NUMBER(18,3)
--                       정수부 자릿수가 18->15로 줄어 직접 MODIFY 불가(ORA-01440)하므로 임시컬럼 재생성으로 처리.
--                       현재 데이터 최대 9자리(3억)라 NUMBER(18,3) 한도(정수 15자리) 내로 무손실.
--   3) 컬럼코멘트     : 금액 계열 코멘트를 메타 용어로 단순화
--                       - TPRMPP_BCOSTM/BCOSTL.AMT          -> '금액'
--                       - TPRMPP_BPLANM/BPLANL.TOT_CPIT_AMT -> '총자본금액'
--                       - TPRMPP_BTERMM/BTERML.AMT          -> '금액'
--   4) 컬럼순서       : MPL_* (BPROJ) 및 재생성된 AMT (BTERM) 를 메타 순서로 재배치
--
-- 배경: V20260614_001(금액 컬럼명 표준화)·V20260614_002(MPL_AMT 분리) 적용 후 메타사전이
--   MPL_XP_AMT -> MPL_MNGC_AMT 로 갱신되고 금액 코멘트를 사전 용어로 회귀시키기로 확정됨.
-- 멱등성: 모든 단계가 상태 비교 가드(컬럼 존재/스케일/순서)를 두어 재실행·부분적용 후에도 안전.
-- 스키마: 객체 소유자는 ITPOWN, 접속 계정은 ITPAPP. 존재 판정은 ALL_* 뷰(owner=ITPOWN)로 한다.
-- 주의: 4)의 INVISIBLE<->VISIBLE 토글, 2)의 컬럼 DROP/RENAME 중 SELECT * 결과가 잠시 달라지므로 무중단 적용 불가(로컬/점검창 전용).

SET SERVEROUTPUT ON SIZE UNLIMITED

-- ============================================================
-- 1) 컬럼 리네임 + 코멘트 : MPL_XP_AMT -> MPL_MNGC_AMT
-- ============================================================
DECLARE
    v_owner VARCHAR2(128) := 'ITPOWN';
    PROCEDURE rename_col(p_table VARCHAR2, p_old VARCHAR2, p_new VARCHAR2) IS
        v_old NUMBER; v_new NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_old FROM ALL_TAB_COLS
         WHERE OWNER = v_owner AND TABLE_NAME = p_table AND COLUMN_NAME = p_old;
        SELECT COUNT(*) INTO v_new FROM ALL_TAB_COLS
         WHERE OWNER = v_owner AND TABLE_NAME = p_table AND COLUMN_NAME = p_new;
        IF v_old > 0 AND v_new = 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || v_owner || '.' || p_table ||
                              ' RENAME COLUMN ' || p_old || ' TO ' || p_new;
        END IF;
    END;
BEGIN
    rename_col('TPRMPP_BPROJM', 'MPL_XP_AMT', 'MPL_MNGC_AMT');
    rename_col('TPRMPP_BPROJL', 'MPL_XP_AMT', 'MPL_MNGC_AMT');
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.MPL_MNGC_AMT IS '예정관리비금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.MPL_MNGC_AMT IS '예정관리비금액']';
END;
/

-- ============================================================
-- 2) 컬럼타입 : TPRMPP_BTERMM/BTERML.AMT  NUMBER(18,0) -> NUMBER(18,3)
--    임시컬럼(AMT__T183) 재생성 방식. AMT 에는 인덱스/제약이 없어 안전.
--    재생성 후 AMT 는 테이블 말미로 이동하며 4)에서 메타 순서로 복귀.
-- ============================================================
DECLARE
    v_owner VARCHAR2(128) := 'ITPOWN';
    PROCEDURE rebuild_amt(p_table VARCHAR2) IS
        v_scale NUMBER;
        v_tmp   NUMBER;
    BEGIN
        SELECT data_scale INTO v_scale FROM ALL_TAB_COLS
         WHERE OWNER = v_owner AND TABLE_NAME = p_table AND COLUMN_NAME = 'AMT';
        IF v_scale = 3 THEN
            RETURN; -- 이미 정합
        END IF;
        -- 직전 부분실패로 임시컬럼이 남아 있으면 정리
        SELECT COUNT(*) INTO v_tmp FROM ALL_TAB_COLS
         WHERE OWNER = v_owner AND TABLE_NAME = p_table AND COLUMN_NAME = 'AMT__T183';
        IF v_tmp > 0 THEN
            EXECUTE IMMEDIATE 'ALTER TABLE ' || v_owner || '.' || p_table || ' DROP COLUMN AMT__T183';
        END IF;
        EXECUTE IMMEDIATE 'ALTER TABLE ' || v_owner || '.' || p_table || ' ADD (AMT__T183 NUMBER(18,3))';
        EXECUTE IMMEDIATE 'UPDATE ' || v_owner || '.' || p_table || ' SET AMT__T183 = AMT';
        EXECUTE IMMEDIATE 'ALTER TABLE ' || v_owner || '.' || p_table || ' DROP COLUMN AMT';
        EXECUTE IMMEDIATE 'ALTER TABLE ' || v_owner || '.' || p_table || ' RENAME COLUMN AMT__T183 TO AMT';
    END;
BEGIN
    rebuild_amt('TPRMPP_BTERMM');
    rebuild_amt('TPRMPP_BTERML');
    COMMIT;
END;
/

-- ============================================================
-- 3) 컬럼코멘트 : 금액 계열 코멘트를 메타 용어로 단순화 (COMMENT 는 상태 설정이라 멱등)
--    2)에서 DROP/RENAME 된 BTERM.AMT 코멘트도 여기서 재설정된다.
-- ============================================================
BEGIN
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BCOSTM.AMT IS '금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BCOSTL.AMT IS '금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BPLANM.TOT_CPIT_AMT IS '총자본금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BPLANL.TOT_CPIT_AMT IS '총자본금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BTERMM.AMT IS '금액']';
    EXECUTE IMMEDIATE q'[COMMENT ON COLUMN ITPOWN.TPRMPP_BTERML.AMT IS '금액']';
END;
/

-- ============================================================
-- 4) 컬럼순서 : 메타 순서로 재배치 (분기 지점 이후 컬럼만 목표 순서대로 토글, PK 미접촉)
-- ============================================================
DECLARE
  v_cur VARCHAR2(4000);
BEGIN
  SELECT LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY column_id) INTO v_cur
  FROM all_tab_columns WHERE owner = 'ITPOWN' AND table_name = 'TPRMPP_BPROJM';
  IF v_cur <> 'ABUS_MNG_NO,SNO,ABUS_NM,ABUS_CONE,ABUS_NCS_CONE,ABUS_TC,BSE_YY,BZ_DTT_NM,CNCD_RFR_NO,CPN_SAF_CONE,CST_TP_TC,DGOG_PPO_CONE,DPL_YN,STT_DTM,END_DTM,EXE_PTT_YN,FLF_FSG_DT,HRF_PLN_CONE,LST_YN,MN_PRG_CONE,TOT_RQM_AMT,MPL_CPIT_AMT,MPL_MNGC_AMT,ODN_YN,PLM_DES,PRLM_HRK_OGZ_C_CONE,SVN_DPM_C,TLR_USID,USID,DVM_DPM_C,DVM_TEM_C,DVM_TLR_USID,DVM_USID,BZ_TP_C,IT_PTL_EDRT_TC,IT_PTL_RPR_STS_TC,IT_PTL_TCHN_TP_TC,IT_PTL_STS_TC,ABUS_RNG_CONE,FST_ENR_USID,FST_ENR_DTM,DEL_YN,GUID,GUID_PRG_SNO,LST_CHG_USID,LST_CHG_DTM' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (MPL_CPIT_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (MPL_CPIT_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (MPL_MNGC_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (MPL_MNGC_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (ODN_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (ODN_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (PLM_DES INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (PLM_DES VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (PRLM_HRK_OGZ_C_CONE INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (PRLM_HRK_OGZ_C_CONE VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (SVN_DPM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (SVN_DPM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (TLR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (TLR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_DPM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_DPM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_TEM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_TEM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_TLR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_TLR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DVM_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (BZ_TP_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (BZ_TP_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_EDRT_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_EDRT_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_RPR_STS_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_RPR_STS_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_TCHN_TP_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_TCHN_TP_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_STS_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (IT_PTL_STS_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (ABUS_RNG_CONE INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (ABUS_RNG_CONE VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (FST_ENR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (FST_ENR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (FST_ENR_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (FST_ENR_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DEL_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (DEL_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (GUID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (GUID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (GUID_PRG_SNO INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (GUID_PRG_SNO VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (LST_CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (LST_CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (LST_CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY (LST_CHG_DTM VISIBLE)';
    DBMS_OUTPUT.PUT_LINE('REORDER TPRMPP_BPROJM (tail 25 cols)');
  END IF;
END;
/

DECLARE
  v_cur VARCHAR2(4000);
BEGIN
  SELECT LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY column_id) INTO v_cur
  FROM all_tab_columns WHERE owner = 'ITPOWN' AND table_name = 'TPRMPP_BPROJL';
  IF v_cur <> 'LOG_HIS_TGR_SNO,ABUS_MNG_NO,SNO,ABUS_NM,ABUS_CONE,ABUS_NCS_CONE,ABUS_TC,BSE_YY,BZ_DTT_NM,CNCD_RFR_NO,CPN_SAF_CONE,CST_TP_TC,DGOG_PPO_CONE,DPL_YN,STT_DTM,END_DTM,EXE_PTT_YN,FLF_FSG_DT,HRF_PLN_CONE,LST_YN,MN_PRG_CONE,TOT_RQM_AMT,MPL_CPIT_AMT,MPL_MNGC_AMT,ODN_YN,PLM_DES,PRLM_HRK_OGZ_C_CONE,SVN_DPM_C,TLR_USID,USID,DVM_DPM_C,DVM_TEM_C,DVM_TLR_USID,DVM_USID,BZ_TP_C,IT_PTL_EDRT_TC,IT_PTL_RPR_STS_TC,IT_PTL_TCHN_TP_TC,IT_PTL_STS_TC,ABUS_RNG_CONE,CHG_DTT_YN,CHG_DTM,CHG_USID,FST_ENR_USID,FST_ENR_DTM,DEL_YN,GUID,GUID_PRG_SNO,LST_CHG_USID,LST_CHG_DTM' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (MPL_CPIT_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (MPL_CPIT_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (MPL_MNGC_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (MPL_MNGC_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (ODN_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (ODN_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (PLM_DES INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (PLM_DES VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (PRLM_HRK_OGZ_C_CONE INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (PRLM_HRK_OGZ_C_CONE VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (SVN_DPM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (SVN_DPM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (TLR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (TLR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_DPM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_DPM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_TEM_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_TEM_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_TLR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_TLR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DVM_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (BZ_TP_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (BZ_TP_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_EDRT_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_EDRT_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_RPR_STS_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_RPR_STS_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_TCHN_TP_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_TCHN_TP_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_STS_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (IT_PTL_STS_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (ABUS_RNG_CONE INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (ABUS_RNG_CONE VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_DTT_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_DTT_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (FST_ENR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (FST_ENR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (FST_ENR_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (FST_ENR_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DEL_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (DEL_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (GUID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (GUID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (GUID_PRG_SNO INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (GUID_PRG_SNO VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (LST_CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (LST_CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (LST_CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY (LST_CHG_DTM VISIBLE)';
    DBMS_OUTPUT.PUT_LINE('REORDER TPRMPP_BPROJL (tail 28 cols)');
  END IF;
END;
/

DECLARE
  v_cur VARCHAR2(4000);
BEGIN
  SELECT LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY column_id) INTO v_cur
  FROM all_tab_columns WHERE owner = 'ITPOWN' AND table_name = 'TPRMPP_BTERMM';
  IF v_cur <> 'TMN_MNG_NO,SNO,BG_NO,BG_SNO,CGPR_ID,DFR_CLE_C,IND_RSN,NSF_USG_CONE,RMK,SPF_TMN_NM,SVN_DPM_C,SVN_TEM_C,AMT,FC_AMT,CUR_C,XCR,XCR_BSE_DT,IT_PTL_TMN_SVC_TC,IT_PTL_TMN_KD_TC,FST_ENR_USID,FST_ENR_DTM,DEL_YN,GUID,GUID_PRG_SNO,LST_CHG_USID,LST_CHG_DTM' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FC_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FC_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (CUR_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (CUR_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (XCR INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (XCR VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (XCR_BSE_DT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (XCR_BSE_DT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (IT_PTL_TMN_SVC_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (IT_PTL_TMN_SVC_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (IT_PTL_TMN_KD_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (IT_PTL_TMN_KD_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FST_ENR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FST_ENR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FST_ENR_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (FST_ENR_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (DEL_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (DEL_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (GUID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (GUID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (GUID_PRG_SNO INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (GUID_PRG_SNO VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (LST_CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (LST_CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (LST_CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERMM MODIFY (LST_CHG_DTM VISIBLE)';
    DBMS_OUTPUT.PUT_LINE('REORDER TPRMPP_BTERMM (tail 14 cols)');
  END IF;
END;
/

DECLARE
  v_cur VARCHAR2(4000);
BEGIN
  SELECT LISTAGG(column_name, ',') WITHIN GROUP (ORDER BY column_id) INTO v_cur
  FROM all_tab_columns WHERE owner = 'ITPOWN' AND table_name = 'TPRMPP_BTERML';
  IF v_cur <> 'LOG_HIS_TGR_SNO,TMN_MNG_NO,SNO,BG_NO,BG_SNO,CGPR_ID,DFR_CLE_C,IND_RSN,NSF_USG_CONE,RMK,SPF_TMN_NM,SVN_DPM_C,SVN_TEM_C,AMT,FC_AMT,CUR_C,XCR,XCR_BSE_DT,IT_PTL_TMN_SVC_TC,IT_PTL_TMN_KD_TC,CHG_DTT_YN,CHG_DTM,CHG_USID,FST_ENR_USID,FST_ENR_DTM,DEL_YN,GUID,GUID_PRG_SNO,LST_CHG_USID,LST_CHG_DTM' THEN
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FC_AMT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FC_AMT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CUR_C INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CUR_C VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (XCR INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (XCR VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (XCR_BSE_DT INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (XCR_BSE_DT VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (IT_PTL_TMN_SVC_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (IT_PTL_TMN_SVC_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (IT_PTL_TMN_KD_TC INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (IT_PTL_TMN_KD_TC VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_DTT_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_DTT_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FST_ENR_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FST_ENR_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FST_ENR_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (FST_ENR_DTM VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (DEL_YN INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (DEL_YN VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (GUID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (GUID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (GUID_PRG_SNO INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (GUID_PRG_SNO VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (LST_CHG_USID INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (LST_CHG_USID VISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (LST_CHG_DTM INVISIBLE)';
    EXECUTE IMMEDIATE 'ALTER TABLE ITPOWN.TPRMPP_BTERML MODIFY (LST_CHG_DTM VISIBLE)';
    DBMS_OUTPUT.PUT_LINE('REORDER TPRMPP_BTERML (tail 17 cols)');
  END IF;
END;
/
