-- 컬럼 표준화
--   RMK       : VARCHAR2(300)        -- 사이즈 축소
--   *_AMT     : NUMBER(18,3)         -- precision/scale 변경
--
-- 변경 방식 (사이즈/타입 축소·변경 시 동일하게 안전 패턴 적용)
--   ① 기존 컬럼을 _BAK 으로 백업 RENAME
--   ② 목표 정의로 신규 컬럼 ADD
--   ③ 데이터 복사 (필요 시 SUBSTR/CAST)
--   ④ _BAK DROP
--   ⑤ COMMENT 재적용
--
-- 사유: NUMBER scale 변경은 데이터가 존재하면 MODIFY 가 ORA-01440 으로 실패하므로
--      *_AMT 도 동일한 백업/복사 패턴을 사용한다.

-- ============================================================
-- 1) RMK : VARCHAR2(300)
--    대상: TAAABB_CBLBMM(500→300), TAAABB_CBLBML(500→300),
--         TAAABB_BTERMM(1000→300), TAAABB_BTERML(1000→300)
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_CBLBMM RENAME COLUMN RMK TO RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_CBLBMM ADD (RMK VARCHAR2(300));
UPDATE ITPAPP.TAAABB_CBLBMM SET RMK = SUBSTR(RMK_BAK, 1, 300);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBMM DROP COLUMN RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CBLBMM.RMK IS '비고';

ALTER TABLE ITPAPP.TAAABB_CBLBML RENAME COLUMN RMK TO RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_CBLBML ADD (RMK VARCHAR2(300));
UPDATE ITPAPP.TAAABB_CBLBML SET RMK = SUBSTR(RMK_BAK, 1, 300);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBML DROP COLUMN RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CBLBML.RMK IS '비고';

ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN RMK TO RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (RMK VARCHAR2(300));
UPDATE ITPAPP.TAAABB_BTERMM SET RMK = SUBSTR(RMK_BAK, 1, 300);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.RMK IS '비고';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN RMK TO RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (RMK VARCHAR2(300));
UPDATE ITPAPP.TAAABB_BTERML SET RMK = SUBSTR(RMK_BAK, 1, 300);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.RMK IS '비고';

-- ============================================================
-- 2) GCL_AMT : NUMBER(18,3)
--    대상: TAAABB_BITEMM, TAAABB_BITEML
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BITEMM RENAME COLUMN GCL_AMT TO GCL_AMT_BAK;
ALTER TABLE ITPAPP.TAAABB_BITEMM ADD (GCL_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BITEMM SET GCL_AMT = GCL_AMT_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEMM DROP COLUMN GCL_AMT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.GCL_AMT IS '품목금액';

ALTER TABLE ITPAPP.TAAABB_BITEML RENAME COLUMN GCL_AMT TO GCL_AMT_BAK;
ALTER TABLE ITPAPP.TAAABB_BITEML ADD (GCL_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BITEML SET GCL_AMT = GCL_AMT_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEML DROP COLUMN GCL_AMT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.GCL_AMT IS '품목금액';

-- ============================================================
-- 3) TML_AMT : NUMBER(18,3)
--    대상: TAAABB_BTERMM, TAAABB_BTERML
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN TML_AMT TO TML_AMT_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (TML_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BTERMM SET TML_AMT = TML_AMT_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN TML_AMT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.TML_AMT IS '단말기금액';

ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN TML_AMT TO TML_AMT_BAK;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (TML_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BTERML SET TML_AMT = TML_AMT_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN TML_AMT_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.TML_AMT IS '단말기금액';
