-- V20260701_002__AddAuthorOrgColumns.sql
-- 작성자 기준 소속 조직 컬럼 추가 (마스터 + 감사 로그 미러).
--   - TPRMPP_BPROJM / BPROJL : + SVN_TEM_C(5)             주관팀코드
--   - TPRMPP_BCOSTM / BCOSTL : + PRLM_HRK_OGZ_C_CONE(100) 인사상위조직코드내용
--   - TPRMPP_BRDOCM / BRDOCL : + SVN_DPM_C(20), SVN_TEM_C(5) 주관부서코드/주관팀코드
-- 값은 신규 생성 시 작성자(현재 로그인 사용자) 소속 조직 기준으로 서비스 계층(AuthorOrgResolver)에서 채운다.
-- 모두 NULL 허용(기존 행 백필 없음). ALTER ... ADD는 컬럼을 테이블 끝에 추가한다(JPA는 컬럼명으로 매핑하므로 물리 위치 무의미).
-- 주의: 적용 후 수정 금지(Flyway 체크섬 추적 대상). 추가 변경은 항상 새 버전 스크립트로 작성.

-- 1) 정보화사업 (BPROJM) + 변경 로그 (BPROJL): 주관팀코드
ALTER TABLE ITPOWN.TPRMPP_BPROJM ADD (SVN_TEM_C VARCHAR2(5 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.SVN_TEM_C IS '주관팀코드';
ALTER TABLE ITPOWN.TPRMPP_BPROJL ADD (SVN_TEM_C VARCHAR2(5 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.SVN_TEM_C IS '주관팀코드';

-- 2) 전산관리비 (BCOSTM) + 변경 로그 (BCOSTL): 인사상위조직코드내용
ALTER TABLE ITPOWN.TPRMPP_BCOSTM ADD (PRLM_HRK_OGZ_C_CONE VARCHAR2(100 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BCOSTM.PRLM_HRK_OGZ_C_CONE IS '인사상위조직코드내용';
ALTER TABLE ITPOWN.TPRMPP_BCOSTL ADD (PRLM_HRK_OGZ_C_CONE VARCHAR2(100 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BCOSTL.PRLM_HRK_OGZ_C_CONE IS '인사상위조직코드내용';

-- 3) 요구사항 정의서 (BRDOCM) + 변경 로그 (BRDOCL): 주관부서코드/주관팀코드
ALTER TABLE ITPOWN.TPRMPP_BRDOCM ADD (SVN_DPM_C VARCHAR2(20 CHAR), SVN_TEM_C VARCHAR2(5 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BRDOCM.SVN_DPM_C IS '주관부서코드';
COMMENT ON COLUMN ITPOWN.TPRMPP_BRDOCM.SVN_TEM_C IS '주관팀코드';
ALTER TABLE ITPOWN.TPRMPP_BRDOCL ADD (SVN_DPM_C VARCHAR2(20 CHAR), SVN_TEM_C VARCHAR2(5 CHAR));
COMMENT ON COLUMN ITPOWN.TPRMPP_BRDOCL.SVN_DPM_C IS '주관부서코드';
COMMENT ON COLUMN ITPOWN.TPRMPP_BRDOCL.SVN_TEM_C IS '주관팀코드';
