-- =====================================================================
-- V20260602_005 인덱스 명명 표준화 + 시퀀스 정합화 (점검 개선)
-- 멱등: 존재 시에만 적용. 인덱스 rename은 메타데이터 변경(데이터 무영향).
-- =====================================================================

-- ---------- 1) 인덱스 명명 표준화 (옛 컬럼명 박제 → 현재 컬럼명, 접두사 IX_ 통일) ----------
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BBUGTM_BG_YY_ORC_TB_ORC_PK_VL_DEL_YN" RENAME TO "IX_BBUGTM_BSE_YY_FNT_TB_NM_PK_COL_NM_DEL_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BBUGTM_ORC_TB_ORC_PK_VL_ORC_SNO_VL" RENAME TO "IX_BBUGTM_FNT_TB_NM_PK_COL_NM_FNT_TB_CRY_SNO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BCOSTM_BG_YY_DEL_YN_LST_YN_IOE_C" RENAME TO "IX_BCOSTM_BSE_YY_DEL_YN_LST_YN_IOE_C"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BCOSTM_BICE_DPM_C_DEL_YN_LST_YN" RENAME TO "IX_BCOSTM_SVN_DPM_C_DEL_YN_LST_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BITEMM_IOE_C_DEL_YN_LST_YN" RENAME TO "IX_BITEMM_IOE_C_DEL_YN_LST_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BITEMM_PRJ_MNG_NO" RENAME TO "IX_BITEMM_ABUS_MNG_NO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BITEMM_PRJ_MNG_NO_PRJ_SNO_DEL_YN_LST_YN" RENAME TO "IX_BITEMM_ABUS_MNG_NO_PRJ_SNO_DEL_YN_LST_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BPROJM_BG_YY_DEL_YN_LST_YN_ORN_YN" RENAME TO "IX_BPROJM_BSE_YY_DEL_YN_LST_YN_ORN_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BPROJM_BG_YY_DEL_YN_LST_YN_PRJ_STS" RENAME TO "IX_BPROJM_BSE_YY_DEL_YN_LST_YN_STS_TC"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_BTERMM_IT_MNGC_NO_IT_MNGC_SNO" RENAME TO "IX_BTERMM_BG_NO_IT_MNGC_SNO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CAPPLA_APF_MNG_NO_ORC_TB_CD" RENAME TO "IX_CAPPLA_APF_DCM_NO_FNT_TB_NM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBCM_BBR_C" RENAME TO "IX_CBLBCM_BBR_C"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBCM_BLB_MNG_NO_DEL_YN_SRE_YN_HRK_FXN_YN_FST_ENR_DTM" RENAME TO "IX_CBLBCM_BLB_ID_DEL_YN_SRE_USE_YN_ANC_YN_FST_ENR_DTM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBCM_FST_ENR_USID_DEL_YN" RENAME TO "IX_CBLBCM_FST_ENR_USID_DEL_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBCM_HRK_NAC_MNG_NO" RENAME TO "IX_CBLBCM_HRK_NAC_MNG_NO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBCM_NAC_GRP_NO_NAC_GRP_SQN" RENAME TO "IX_CBLBCM_NAC_GRP_NO_GRP_SQN_SNO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CBLBMM_USE_YN_SRE_SQN_NO" RENAME TO "IX_CBLBMM_USE_YN_SRE_SQN_SNO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CCMMTM_NAC_MNG_NO_DEL_YN_SRE_YN_FST_ENR_DTM" RENAME TO "IX_CCMMTM_NAC_NO_DEL_YN_SRE_USE_YN_FST_ENR_DTM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CCODEM_C_ID_DEL_YN_STT_DT_END_DT" RENAME TO "IX_CCODEM_CO_C_ID_DEL_YN_STT_DTM_END_DTM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CCODEM_C_TP_DEL_YN_STT_DT_END_DT" RENAME TO "IX_CCODEM_CO_C_INTN_NM_DEL_YN_STT_DTM_END_DTM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CCODEM_HRK_C_DEL_YN" RENAME TO "IX_CCODEM_HRK_CDVA_ID_DEL_YN"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CORGNI_PRLM_HRK_OGZ_C_CONE" RENAME TO "IX_CORGNI_PRLM_HRK_OGZ_C_CONE"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CRTOKM_ENO" RENAME TO "IX_CRTOKM_ENO"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CRTOKM_TOK" RENAME TO "IX_CRTOKM_API_TOK_CONE"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IDX_TAAABB_CUSERI_BBR_C" RENAME TO "IX_CUSERI_BBR_C"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'ALTER INDEX "IX_CINFMM_RCV" RENAME TO "IX_CINFMM_RMS_ENO_DEL_YN_INQ_YN_FST_ENR_DTM"'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- ---------- 2) 시퀀스 정합화 ----------
-- [치명] SEQ_CCMMTM: CMMT_SNO(NUMBER9) PK 채번인데 MAXVALUE 9999+CYCLE → 9999개 후 PK 중복
ALTER SEQUENCE SEQ_CCMMTM MAXVALUE 999999999 NOCYCLE CACHE 20;
-- [불일치] SEQ_CAPPLA: APF_SNO(NUMBER9)인데 MAXVALUE 28자리 → ORA-01438 위험. 컬럼 정밀도에 맞춤
ALTER SEQUENCE SEQ_CAPPLA MAXVALUE 999999999 NOCYCLE;
-- [원칙] PK 채번 시퀀스는 CYCLE 금지(중복 방지): CLOGNH/CRTOKM
ALTER SEQUENCE SEQ_CLOGNH NOCYCLE;
ALTER SEQUENCE SEQ_CRTOKM NOCYCLE;

-- [표준화 권고·검토 후 적용] 로그 PK LOG_HIS_TGR_SNO 타입 불일치(NUMBER(18) vs NUMBER(22))
--   로그 시퀀스 MAXVALUE(22자리)가 NUMBER(18) 컬럼 용량 초과 → 컬럼을 NUMBER(22)로 통일 권장.
--   예: ALTER TABLE TPRMPP_BASCTL MODIFY (LOG_HIS_TGR_SNO NUMBER(22));  (18자리 테이블 전체)

COMMIT;