-- V20260609_001__AlignSchemaWithProdNullAndTypes.sql
-- 운영(table.csv) 기준 로컬개발 DB 정합: #3 NULL 제약 / #4 컬럼 타입
-- 생성: .gen_align_migration.py (.align_plan.json 기반, DB 데이터 점검 반영)
--
-- 제외(좁히기 불가, 실제 3자리 코드값): EXE_PTT_YN, IT_PTL_RPR_STS_TC, IT_PTL_TCHN_TP_TC,
--        IT_PTL_TMN_SVC_TC, IT_PTL_TMN_KD_TC (BPROJM/L, BTERMM) — 운영 CSV/meta.csv가 stale.
-- 멱등성: 모든 변경은 현재 상태(user_tab_columns) 확인 후에만 적용.

-- ============================================================
-- A. 차단 감사컬럼 백필 (마이그레이션 시드 INSERT 누락분 보정)
-- ============================================================
UPDATE ITPAPP.TPRMPP_CROLEI SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CROLEI SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CROLEI SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_CFILEM SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_CFILEM SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CFILEM SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CAPPLL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_CAPPLL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CAPPLL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEM SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEM SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEM SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEM SET LST_CHG_DTM=NVL(FST_ENR_DTM,SYSDATE) WHERE LST_CHG_DTM IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CCODEL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUM SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUM SET LST_CHG_DTM=NVL(FST_ENR_DTM,SYSDATE) WHERE LST_CHG_DTM IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUD SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUD SET LST_CHG_DTM=NVL(FST_ENR_DTM,SYSDATE) WHERE LST_CHG_DTM IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUA SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_CMENUA SET LST_CHG_DTM=NVL(FST_ENR_DTM,SYSDATE) WHERE LST_CHG_DTM IS NULL;
UPDATE ITPAPP.TPRMPP_CBLBCL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_CBLBCL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_CBLBCL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CBLBCL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CAUTHI SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_CAUTHI SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_CAUTHI SET LST_CHG_USID=NVL(FST_ENR_USID,'MIGRATION') WHERE LST_CHG_USID IS NULL;
UPDATE ITPAPP.TPRMPP_BRDOCL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BRDOCL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BRDOCL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BRDOCL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BGDOCL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BBUGTL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BBUGTL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BBUGTL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BBUGTL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BRIVGL SET FSG_YN='N' WHERE FSG_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BRIVGL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BRIVGL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BRIVGL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BPLANL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BPLANL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BPLANL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BPLANL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BTERMM SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BTERMM SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BCOSTL SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BCOSTL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BCOSTL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BCOSTL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BTERML SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BTERML SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BTERML SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BITEML SET CHG_DTT_YN='N' WHERE CHG_DTT_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BITEML SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BITEML SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BITEML SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BASCTL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BASCTL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BASCTL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BPOVWL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BPOVWL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BPOVWL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BCHKLL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BCHKLL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BCHKLL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BPERFL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BPERFL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BPERFL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BPQNAL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BPQNAL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BPQNAL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BMQNAL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BMQNAL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BMQNAL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BCMMTL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BCMMTL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BCMMTL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BSCHDL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BSCHDL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BSCHDL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
UPDATE ITPAPP.TPRMPP_BRSLTL SET DEL_YN='N' WHERE DEL_YN IS NULL;
UPDATE ITPAPP.TPRMPP_BRSLTL SET GUID=LOWER(REGEXP_REPLACE(RAWTOHEX(SYS_GUID()),'(.{8})(.{4})(.{4})(.{4})(.{12})','\1-\2-\3-\4-\5')) WHERE GUID IS NULL;
UPDATE ITPAPP.TPRMPP_BRSLTL SET GUID_PRG_SNO=1 WHERE GUID_PRG_SNO IS NULL;
COMMIT;

-- ============================================================
-- B. NOT NULL 제약 부여 (운영=NOT NULL, 로컬=NULL) — 515개 컬럼
-- ============================================================
DECLARE
  TYPE t_rec IS RECORD (tbl VARCHAR2(30), col VARCHAR2(30));
  TYPE t_arr IS TABLE OF t_rec;
  v t_arr := t_arr(
    t_rec('TPRMPP_CUSERI','ENO'),
    t_rec('TPRMPP_CUSERI','FST_ENR_USID'),
    t_rec('TPRMPP_CUSERI','FST_ENR_DTM'),
    t_rec('TPRMPP_CUSERI','DEL_YN'),
    t_rec('TPRMPP_CUSERI','GUID'),
    t_rec('TPRMPP_CUSERI','GUID_PRG_SNO'),
    t_rec('TPRMPP_CUSERI','LST_CHG_USID'),
    t_rec('TPRMPP_CUSERI','LST_CHG_DTM'),
    t_rec('TPRMPP_CRTOKM','LGN_LOG_SNO'),
    t_rec('TPRMPP_CRTOKM','FST_ENR_USID'),
    t_rec('TPRMPP_CRTOKM','FST_ENR_DTM'),
    t_rec('TPRMPP_CRTOKM','DEL_YN'),
    t_rec('TPRMPP_CRTOKM','GUID'),
    t_rec('TPRMPP_CRTOKM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CRTOKM','LST_CHG_USID'),
    t_rec('TPRMPP_CRTOKM','LST_CHG_DTM'),
    t_rec('TPRMPP_CROLEI','FST_ENR_USID'),
    t_rec('TPRMPP_CROLEI','FST_ENR_DTM'),
    t_rec('TPRMPP_CROLEI','DEL_YN'),
    t_rec('TPRMPP_CROLEI','LST_CHG_DTM'),
    t_rec('TPRMPP_CORGNI','FST_ENR_USID'),
    t_rec('TPRMPP_CORGNI','FST_ENR_DTM'),
    t_rec('TPRMPP_CORGNI','DEL_YN'),
    t_rec('TPRMPP_CORGNI','GUID'),
    t_rec('TPRMPP_CORGNI','GUID_PRG_SNO'),
    t_rec('TPRMPP_CORGNI','LST_CHG_USID'),
    t_rec('TPRMPP_CORGNI','LST_CHG_DTM'),
    t_rec('TPRMPP_CLOGNH','LGN_DTM'),
    t_rec('TPRMPP_CLOGNH','FST_ENR_USID'),
    t_rec('TPRMPP_CLOGNH','FST_ENR_DTM'),
    t_rec('TPRMPP_CLOGNH','DEL_YN'),
    t_rec('TPRMPP_CLOGNH','GUID'),
    t_rec('TPRMPP_CLOGNH','GUID_PRG_SNO'),
    t_rec('TPRMPP_CLOGNH','LST_CHG_USID'),
    t_rec('TPRMPP_CLOGNH','LST_CHG_DTM'),
    t_rec('TPRMPP_CINFMM','FST_ENR_USID'),
    t_rec('TPRMPP_CINFMM','FST_ENR_DTM'),
    t_rec('TPRMPP_CINFMM','GUID'),
    t_rec('TPRMPP_CINFMM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CINFMM','LST_CHG_USID'),
    t_rec('TPRMPP_CINFMM','LST_CHG_DTM'),
    t_rec('TPRMPP_CFILEM','FST_ENR_USID'),
    t_rec('TPRMPP_CFILEM','FST_ENR_DTM'),
    t_rec('TPRMPP_CFILEM','LST_CHG_USID'),
    t_rec('TPRMPP_CFILEM','LST_CHG_DTM'),
    t_rec('TPRMPP_CDECIM','FST_ENR_USID'),
    t_rec('TPRMPP_CDECIM','FST_ENR_DTM'),
    t_rec('TPRMPP_CDECIM','DEL_YN'),
    t_rec('TPRMPP_CDECIM','GUID'),
    t_rec('TPRMPP_CDECIM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CDECIM','LST_CHG_USID'),
    t_rec('TPRMPP_CDECIM','LST_CHG_DTM'),
    t_rec('TPRMPP_CAPPLM','FST_ENR_USID'),
    t_rec('TPRMPP_CAPPLM','FST_ENR_DTM'),
    t_rec('TPRMPP_CAPPLM','DEL_YN'),
    t_rec('TPRMPP_CAPPLM','GUID'),
    t_rec('TPRMPP_CAPPLM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CAPPLM','LST_CHG_USID'),
    t_rec('TPRMPP_CAPPLM','LST_CHG_DTM'),
    t_rec('TPRMPP_CAPPLA','FST_ENR_USID'),
    t_rec('TPRMPP_CAPPLA','FST_ENR_DTM'),
    t_rec('TPRMPP_CAPPLA','DEL_YN'),
    t_rec('TPRMPP_CAPPLA','GUID'),
    t_rec('TPRMPP_CAPPLA','GUID_PRG_SNO'),
    t_rec('TPRMPP_CAPPLA','LST_CHG_USID'),
    t_rec('TPRMPP_CAPPLA','LST_CHG_DTM'),
    t_rec('TPRMPP_CAPPLL','APF_DCM_NO'),
    t_rec('TPRMPP_CAPPLL','APF_PRG_STS_C'),
    t_rec('TPRMPP_CAPPLL','FST_ENR_USID'),
    t_rec('TPRMPP_CAPPLL','FST_ENR_DTM'),
    t_rec('TPRMPP_CAPPLL','LST_CHG_USID'),
    t_rec('TPRMPP_CAPPLL','LST_CHG_DTM'),
    t_rec('TPRMPP_CCODEM','FST_ENR_USID'),
    t_rec('TPRMPP_CCODEM','FST_ENR_DTM'),
    t_rec('TPRMPP_CCODEM','DEL_YN'),
    t_rec('TPRMPP_CCODEL','CO_C_ID'),
    t_rec('TPRMPP_CCODEL','CDVA_ID'),
    t_rec('TPRMPP_CCODEL','STT_DTM'),
    t_rec('TPRMPP_CCODEL','FST_ENR_USID'),
    t_rec('TPRMPP_CCODEL','FST_ENR_DTM'),
    t_rec('TPRMPP_CCODEL','LST_CHG_USID'),
    t_rec('TPRMPP_CCODEL','LST_CHG_DTM'),
    t_rec('TPRMPP_CMENUM','FST_ENR_USID'),
    t_rec('TPRMPP_CMENUM','FST_ENR_DTM'),
    t_rec('TPRMPP_CMENUM','GUID'),
    t_rec('TPRMPP_CMENUM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CMENUD','FST_ENR_USID'),
    t_rec('TPRMPP_CMENUD','FST_ENR_DTM'),
    t_rec('TPRMPP_CMENUD','GUID'),
    t_rec('TPRMPP_CMENUD','GUID_PRG_SNO'),
    t_rec('TPRMPP_CMENUA','FST_ENR_USID'),
    t_rec('TPRMPP_CMENUA','FST_ENR_DTM'),
    t_rec('TPRMPP_CMENUA','GUID'),
    t_rec('TPRMPP_CMENUA','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCOSTM','FST_ENR_USID'),
    t_rec('TPRMPP_BCOSTM','FST_ENR_DTM'),
    t_rec('TPRMPP_BCOSTM','DEL_YN'),
    t_rec('TPRMPP_BCOSTM','GUID'),
    t_rec('TPRMPP_BCOSTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCOSTM','LST_CHG_USID'),
    t_rec('TPRMPP_BCOSTM','LST_CHG_DTM'),
    t_rec('TPRMPP_CMENUL','MNU_ID'),
    t_rec('TPRMPP_CMENUL','MNU_NM'),
    t_rec('TPRMPP_CMENUL','MNU_TP_C'),
    t_rec('TPRMPP_CMENUL','MNU_SOT_SQN_SNO'),
    t_rec('TPRMPP_CMENUL','HID_YN'),
    t_rec('TPRMPP_CMENUL','MNU_DEP'),
    t_rec('TPRMPP_CMENUL','WHL_MNU_PTH'),
    t_rec('TPRMPP_CMENUL','CHG_DTT_YN'),
    t_rec('TPRMPP_CMENUL','CHG_DTM'),
    t_rec('TPRMPP_CMENUL','FST_ENR_USID'),
    t_rec('TPRMPP_CMENUL','FST_ENR_DTM'),
    t_rec('TPRMPP_CMENUL','DEL_YN'),
    t_rec('TPRMPP_CMENUL','GUID'),
    t_rec('TPRMPP_CMENUL','GUID_PRG_SNO'),
    t_rec('TPRMPP_CMENUL','LST_CHG_USID'),
    t_rec('TPRMPP_CMENUL','LST_CHG_DTM'),
    t_rec('TPRMPP_CBLBMM','FST_ENR_USID'),
    t_rec('TPRMPP_CBLBMM','FST_ENR_DTM'),
    t_rec('TPRMPP_CBLBMM','GUID'),
    t_rec('TPRMPP_CBLBMM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CBLBMM','LST_CHG_USID'),
    t_rec('TPRMPP_CBLBMM','LST_CHG_DTM'),
    t_rec('TPRMPP_CBLBCM','FST_ENR_USID'),
    t_rec('TPRMPP_CBLBCM','FST_ENR_DTM'),
    t_rec('TPRMPP_CBLBCM','GUID'),
    t_rec('TPRMPP_CBLBCM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CBLBCM','LST_CHG_USID'),
    t_rec('TPRMPP_CBLBCM','LST_CHG_DTM'),
    t_rec('TPRMPP_CCMMTM','FST_ENR_USID'),
    t_rec('TPRMPP_CCMMTM','FST_ENR_DTM'),
    t_rec('TPRMPP_CCMMTM','GUID'),
    t_rec('TPRMPP_CCMMTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CCMMTM','LST_CHG_USID'),
    t_rec('TPRMPP_CCMMTM','LST_CHG_DTM'),
    t_rec('TPRMPP_CBLBML','BLB_ID'),
    t_rec('TPRMPP_CBLBML','CHG_DTT_YN'),
    t_rec('TPRMPP_CBLBML','FST_ENR_USID'),
    t_rec('TPRMPP_CBLBML','FST_ENR_DTM'),
    t_rec('TPRMPP_CBLBML','DEL_YN'),
    t_rec('TPRMPP_CBLBML','GUID'),
    t_rec('TPRMPP_CBLBML','GUID_PRG_SNO'),
    t_rec('TPRMPP_CBLBML','LST_CHG_USID'),
    t_rec('TPRMPP_CBLBML','LST_CHG_DTM'),
    t_rec('TPRMPP_CBLBCL','NAC_NO'),
    t_rec('TPRMPP_CBLBCL','BLB_ID'),
    t_rec('TPRMPP_CBLBCL','ANC_YN'),
    t_rec('TPRMPP_CBLBCL','APG_FL_NBR'),
    t_rec('TPRMPP_CBLBCL','FL_APG_YN'),
    t_rec('TPRMPP_CBLBCL','GRP_SQN_SNO'),
    t_rec('TPRMPP_CBLBCL','NAC_INQ_NBR'),
    t_rec('TPRMPP_CBLBCL','NAC_LEV_MNG_SNO'),
    t_rec('TPRMPP_CBLBCL','NAC_TTL'),
    t_rec('TPRMPP_CBLBCL','SRE_USE_YN'),
    t_rec('TPRMPP_CBLBCL','CHG_DTM'),
    t_rec('TPRMPP_CBLBCL','FST_ENR_USID'),
    t_rec('TPRMPP_CBLBCL','FST_ENR_DTM'),
    t_rec('TPRMPP_CBLBCL','LST_CHG_USID'),
    t_rec('TPRMPP_CBLBCL','LST_CHG_DTM'),
    t_rec('TPRMPP_CCMMTL','CMMT_SNO'),
    t_rec('TPRMPP_CCMMTL','NAC_NO'),
    t_rec('TPRMPP_CCMMTL','CMMT_DEP_NBR'),
    t_rec('TPRMPP_CCMMTL','CMMT_SQN_SNO'),
    t_rec('TPRMPP_CCMMTL','SRE_USE_YN'),
    t_rec('TPRMPP_CCMMTL','CHG_DTT_YN'),
    t_rec('TPRMPP_CCMMTL','FST_ENR_USID'),
    t_rec('TPRMPP_CCMMTL','FST_ENR_DTM'),
    t_rec('TPRMPP_CCMMTL','DEL_YN'),
    t_rec('TPRMPP_CCMMTL','GUID'),
    t_rec('TPRMPP_CCMMTL','GUID_PRG_SNO'),
    t_rec('TPRMPP_CCMMTL','LST_CHG_USID'),
    t_rec('TPRMPP_CCMMTL','LST_CHG_DTM'),
    t_rec('TPRMPP_CAUTHI','FST_ENR_USID'),
    t_rec('TPRMPP_CAUTHI','FST_ENR_DTM'),
    t_rec('TPRMPP_CAUTHI','DEL_YN'),
    t_rec('TPRMPP_CAUTHI','LST_CHG_DTM'),
    t_rec('TPRMPP_BRDOCM','FST_ENR_USID'),
    t_rec('TPRMPP_BRDOCM','FST_ENR_DTM'),
    t_rec('TPRMPP_BRDOCM','DEL_YN'),
    t_rec('TPRMPP_BRDOCM','GUID'),
    t_rec('TPRMPP_BRDOCM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BRDOCM','LST_CHG_USID'),
    t_rec('TPRMPP_BRDOCM','LST_CHG_DTM'),
    t_rec('TPRMPP_BGDOCM','FST_ENR_USID'),
    t_rec('TPRMPP_BGDOCM','FST_ENR_DTM'),
    t_rec('TPRMPP_BGDOCM','DEL_YN'),
    t_rec('TPRMPP_BGDOCM','GUID'),
    t_rec('TPRMPP_BGDOCM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BGDOCM','LST_CHG_USID'),
    t_rec('TPRMPP_BGDOCM','LST_CHG_DTM'),
    t_rec('TPRMPP_BRDOCL','DOC_MNG_NO'),
    t_rec('TPRMPP_BRDOCL','DOC_VRS_SNO'),
    t_rec('TPRMPP_BRDOCL','FST_ENR_USID'),
    t_rec('TPRMPP_BRDOCL','FST_ENR_DTM'),
    t_rec('TPRMPP_BRDOCL','LST_CHG_USID'),
    t_rec('TPRMPP_BRDOCL','LST_CHG_DTM'),
    t_rec('TPRMPP_BGDOCL','DOC_MNG_NO'),
    t_rec('TPRMPP_BGDOCL','FST_ENR_USID'),
    t_rec('TPRMPP_BGDOCL','FST_ENR_DTM'),
    t_rec('TPRMPP_BGDOCL','DEL_YN'),
    t_rec('TPRMPP_BGDOCL','GUID'),
    t_rec('TPRMPP_BGDOCL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BGDOCL','LST_CHG_USID'),
    t_rec('TPRMPP_BGDOCL','LST_CHG_DTM'),
    t_rec('TPRMPP_BBUGTM','FST_ENR_USID'),
    t_rec('TPRMPP_BBUGTM','FST_ENR_DTM'),
    t_rec('TPRMPP_BBUGTM','DEL_YN'),
    t_rec('TPRMPP_BBUGTM','GUID'),
    t_rec('TPRMPP_BBUGTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BBUGTM','LST_CHG_USID'),
    t_rec('TPRMPP_BBUGTM','LST_CHG_DTM'),
    t_rec('TPRMPP_BBUGTL','BG_NO'),
    t_rec('TPRMPP_BBUGTL','SNO'),
    t_rec('TPRMPP_BBUGTL','FST_ENR_USID'),
    t_rec('TPRMPP_BBUGTL','FST_ENR_DTM'),
    t_rec('TPRMPP_BBUGTL','LST_CHG_USID'),
    t_rec('TPRMPP_BBUGTL','LST_CHG_DTM'),
    t_rec('TPRMPP_BRIVGM','FST_ENR_USID'),
    t_rec('TPRMPP_BRIVGM','FST_ENR_DTM'),
    t_rec('TPRMPP_BRIVGM','DEL_YN'),
    t_rec('TPRMPP_BRIVGM','GUID'),
    t_rec('TPRMPP_BRIVGM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BRIVGM','LST_CHG_USID'),
    t_rec('TPRMPP_BRIVGM','LST_CHG_DTM'),
    t_rec('TPRMPP_BRIVGL','IPM_OPNN_SNO'),
    t_rec('TPRMPP_BRIVGL','DOC_MNG_NO'),
    t_rec('TPRMPP_BRIVGL','DOC_VRS_SNO'),
    t_rec('TPRMPP_BRIVGL','CHG_DTT_YN'),
    t_rec('TPRMPP_BRIVGL','FST_ENR_USID'),
    t_rec('TPRMPP_BRIVGL','FST_ENR_DTM'),
    t_rec('TPRMPP_BRIVGL','LST_CHG_USID'),
    t_rec('TPRMPP_BRIVGL','LST_CHG_DTM'),
    t_rec('TPRMPP_BPLANM','FST_ENR_USID'),
    t_rec('TPRMPP_BPLANM','FST_ENR_DTM'),
    t_rec('TPRMPP_BPLANM','DEL_YN'),
    t_rec('TPRMPP_BPLANM','GUID'),
    t_rec('TPRMPP_BPLANM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPLANM','LST_CHG_USID'),
    t_rec('TPRMPP_BPLANM','LST_CHG_DTM'),
    t_rec('TPRMPP_BPLANL','REQ_DOC_NO'),
    t_rec('TPRMPP_BPLANL','FST_ENR_USID'),
    t_rec('TPRMPP_BPLANL','FST_ENR_DTM'),
    t_rec('TPRMPP_BPLANL','LST_CHG_USID'),
    t_rec('TPRMPP_BPLANL','LST_CHG_DTM'),
    t_rec('TPRMPP_BPLANA','FST_ENR_USID'),
    t_rec('TPRMPP_BPLANA','FST_ENR_DTM'),
    t_rec('TPRMPP_BPLANA','DEL_YN'),
    t_rec('TPRMPP_BPLANA','GUID'),
    t_rec('TPRMPP_BPLANA','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPLANA','LST_CHG_USID'),
    t_rec('TPRMPP_BPLANA','LST_CHG_DTM'),
    t_rec('TPRMPP_BPROJM','ABUS_MNG_NO'),
    t_rec('TPRMPP_BPROJM','SNO'),
    t_rec('TPRMPP_BPROJM','FST_ENR_USID'),
    t_rec('TPRMPP_BPROJM','FST_ENR_DTM'),
    t_rec('TPRMPP_BPROJM','DEL_YN'),
    t_rec('TPRMPP_BPROJM','GUID'),
    t_rec('TPRMPP_BPROJM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPROJM','LST_CHG_USID'),
    t_rec('TPRMPP_BPROJM','LST_CHG_DTM'),
    t_rec('TPRMPP_BITEMM','FST_ENR_USID'),
    t_rec('TPRMPP_BITEMM','FST_ENR_DTM'),
    t_rec('TPRMPP_BITEMM','DEL_YN'),
    t_rec('TPRMPP_BITEMM','GUID'),
    t_rec('TPRMPP_BITEMM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BITEMM','LST_CHG_USID'),
    t_rec('TPRMPP_BITEMM','LST_CHG_DTM'),
    t_rec('TPRMPP_BTERMM','FST_ENR_USID'),
    t_rec('TPRMPP_BTERMM','FST_ENR_DTM'),
    t_rec('TPRMPP_BTERMM','DEL_YN'),
    t_rec('TPRMPP_BTERMM','LST_CHG_USID'),
    t_rec('TPRMPP_BTERMM','LST_CHG_DTM'),
    t_rec('TPRMPP_BCOSTL','BG_NO'),
    t_rec('TPRMPP_BCOSTL','BG_SNO'),
    t_rec('TPRMPP_BCOSTL','FST_ENR_USID'),
    t_rec('TPRMPP_BCOSTL','FST_ENR_DTM'),
    t_rec('TPRMPP_BCOSTL','LST_CHG_USID'),
    t_rec('TPRMPP_BCOSTL','LST_CHG_DTM'),
    t_rec('TPRMPP_BTERML','TMN_MNG_NO'),
    t_rec('TPRMPP_BTERML','SNO'),
    t_rec('TPRMPP_BTERML','FST_ENR_USID'),
    t_rec('TPRMPP_BTERML','FST_ENR_DTM'),
    t_rec('TPRMPP_BTERML','DEL_YN'),
    t_rec('TPRMPP_BTERML','LST_CHG_USID'),
    t_rec('TPRMPP_BTERML','LST_CHG_DTM'),
    t_rec('TPRMPP_BPROJL','ABUS_MNG_NO'),
    t_rec('TPRMPP_BPROJL','SNO'),
    t_rec('TPRMPP_BPROJL','CHG_DTT_YN'),
    t_rec('TPRMPP_BPROJL','FST_ENR_USID'),
    t_rec('TPRMPP_BPROJL','FST_ENR_DTM'),
    t_rec('TPRMPP_BPROJL','DEL_YN'),
    t_rec('TPRMPP_BPROJL','GUID'),
    t_rec('TPRMPP_BPROJL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPROJL','LST_CHG_USID'),
    t_rec('TPRMPP_BPROJL','LST_CHG_DTM'),
    t_rec('TPRMPP_BITEML','GCL_MNG_NO'),
    t_rec('TPRMPP_BITEML','SNO'),
    t_rec('TPRMPP_BITEML','FST_ENR_USID'),
    t_rec('TPRMPP_BITEML','FST_ENR_DTM'),
    t_rec('TPRMPP_BITEML','LST_CHG_USID'),
    t_rec('TPRMPP_BITEML','LST_CHG_DTM'),
    t_rec('TPRMPP_BPQNAM','FST_ENR_USID'),
    t_rec('TPRMPP_BPQNAM','FST_ENR_DTM'),
    t_rec('TPRMPP_BPQNAM','DEL_YN'),
    t_rec('TPRMPP_BPQNAM','GUID'),
    t_rec('TPRMPP_BPQNAM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPQNAM','LST_CHG_USID'),
    t_rec('TPRMPP_BPQNAM','LST_CHG_DTM'),
    t_rec('TPRMPP_BMQNAM','FST_ENR_USID'),
    t_rec('TPRMPP_BMQNAM','FST_ENR_DTM'),
    t_rec('TPRMPP_BMQNAM','DEL_YN'),
    t_rec('TPRMPP_BMQNAM','GUID'),
    t_rec('TPRMPP_BMQNAM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BMQNAM','LST_CHG_USID'),
    t_rec('TPRMPP_BMQNAM','LST_CHG_DTM'),
    t_rec('TPRMPP_BEVALM','FST_ENR_USID'),
    t_rec('TPRMPP_BEVALM','FST_ENR_DTM'),
    t_rec('TPRMPP_BEVALM','DEL_YN'),
    t_rec('TPRMPP_BEVALM','GUID'),
    t_rec('TPRMPP_BEVALM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BEVALM','LST_CHG_USID'),
    t_rec('TPRMPP_BEVALM','LST_CHG_DTM'),
    t_rec('TPRMPP_BASCTM','FST_ENR_USID'),
    t_rec('TPRMPP_BASCTM','FST_ENR_DTM'),
    t_rec('TPRMPP_BASCTM','DEL_YN'),
    t_rec('TPRMPP_BASCTM','GUID'),
    t_rec('TPRMPP_BASCTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BASCTM','LST_CHG_USID'),
    t_rec('TPRMPP_BASCTM','LST_CHG_DTM'),
    t_rec('TPRMPP_BCHKLM','FST_ENR_USID'),
    t_rec('TPRMPP_BCHKLM','FST_ENR_DTM'),
    t_rec('TPRMPP_BCHKLM','DEL_YN'),
    t_rec('TPRMPP_BCHKLM','GUID'),
    t_rec('TPRMPP_BCHKLM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCHKLM','LST_CHG_USID'),
    t_rec('TPRMPP_BCHKLM','LST_CHG_DTM'),
    t_rec('TPRMPP_BPERFM','FST_ENR_USID'),
    t_rec('TPRMPP_BPERFM','FST_ENR_DTM'),
    t_rec('TPRMPP_BPERFM','DEL_YN'),
    t_rec('TPRMPP_BPERFM','GUID'),
    t_rec('TPRMPP_BPERFM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPERFM','LST_CHG_USID'),
    t_rec('TPRMPP_BPERFM','LST_CHG_DTM'),
    t_rec('TPRMPP_BRSLTM','FST_ENR_USID'),
    t_rec('TPRMPP_BRSLTM','FST_ENR_DTM'),
    t_rec('TPRMPP_BRSLTM','DEL_YN'),
    t_rec('TPRMPP_BRSLTM','GUID'),
    t_rec('TPRMPP_BRSLTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BRSLTM','LST_CHG_USID'),
    t_rec('TPRMPP_BRSLTM','LST_CHG_DTM'),
    t_rec('TPRMPP_BCMMTM','FST_ENR_USID'),
    t_rec('TPRMPP_BCMMTM','FST_ENR_DTM'),
    t_rec('TPRMPP_BCMMTM','DEL_YN'),
    t_rec('TPRMPP_BCMMTM','GUID'),
    t_rec('TPRMPP_BCMMTM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCMMTM','LST_CHG_USID'),
    t_rec('TPRMPP_BCMMTM','LST_CHG_DTM'),
    t_rec('TPRMPP_BPOVWM','FST_ENR_USID'),
    t_rec('TPRMPP_BPOVWM','FST_ENR_DTM'),
    t_rec('TPRMPP_BPOVWM','DEL_YN'),
    t_rec('TPRMPP_BPOVWM','GUID'),
    t_rec('TPRMPP_BPOVWM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPOVWM','LST_CHG_USID'),
    t_rec('TPRMPP_BPOVWM','LST_CHG_DTM'),
    t_rec('TPRMPP_BSCHDM','FST_ENR_USID'),
    t_rec('TPRMPP_BSCHDM','FST_ENR_DTM'),
    t_rec('TPRMPP_BSCHDM','DEL_YN'),
    t_rec('TPRMPP_BSCHDM','GUID'),
    t_rec('TPRMPP_BSCHDM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BSCHDM','LST_CHG_USID'),
    t_rec('TPRMPP_BSCHDM','LST_CHG_DTM'),
    t_rec('TPRMPP_BASCTL','CHG_DTT_YN'),
    t_rec('TPRMPP_BASCTL','FST_ENR_USID'),
    t_rec('TPRMPP_BASCTL','FST_ENR_DTM'),
    t_rec('TPRMPP_BASCTL','LST_CHG_USID'),
    t_rec('TPRMPP_BASCTL','LST_CHG_DTM'),
    t_rec('TPRMPP_BPOVWL','CHG_DTT_YN'),
    t_rec('TPRMPP_BPOVWL','FST_ENR_USID'),
    t_rec('TPRMPP_BPOVWL','FST_ENR_DTM'),
    t_rec('TPRMPP_BPOVWL','LST_CHG_USID'),
    t_rec('TPRMPP_BPOVWL','LST_CHG_DTM'),
    t_rec('TPRMPP_BCHKLL','CHG_DTT_YN'),
    t_rec('TPRMPP_BCHKLL','FST_ENR_USID'),
    t_rec('TPRMPP_BCHKLL','FST_ENR_DTM'),
    t_rec('TPRMPP_BCHKLL','LST_CHG_USID'),
    t_rec('TPRMPP_BCHKLL','LST_CHG_DTM'),
    t_rec('TPRMPP_BPERFL','CHG_DTT_YN'),
    t_rec('TPRMPP_BPERFL','FST_ENR_USID'),
    t_rec('TPRMPP_BPERFL','FST_ENR_DTM'),
    t_rec('TPRMPP_BPERFL','LST_CHG_USID'),
    t_rec('TPRMPP_BPERFL','LST_CHG_DTM'),
    t_rec('TPRMPP_BPQNAL','QTN_ID'),
    t_rec('TPRMPP_BPQNAL','CHG_DTT_YN'),
    t_rec('TPRMPP_BPQNAL','FST_ENR_USID'),
    t_rec('TPRMPP_BPQNAL','FST_ENR_DTM'),
    t_rec('TPRMPP_BPQNAL','LST_CHG_USID'),
    t_rec('TPRMPP_BPQNAL','LST_CHG_DTM'),
    t_rec('TPRMPP_BMQNAL','QTN_ID'),
    t_rec('TPRMPP_BMQNAL','CHG_DTT_YN'),
    t_rec('TPRMPP_BMQNAL','FST_ENR_USID'),
    t_rec('TPRMPP_BMQNAL','FST_ENR_DTM'),
    t_rec('TPRMPP_BMQNAL','LST_CHG_USID'),
    t_rec('TPRMPP_BMQNAL','LST_CHG_DTM'),
    t_rec('TPRMPP_BCMMTL','ENO'),
    t_rec('TPRMPP_BCMMTL','CHG_DTT_YN'),
    t_rec('TPRMPP_BCMMTL','FST_ENR_USID'),
    t_rec('TPRMPP_BCMMTL','FST_ENR_DTM'),
    t_rec('TPRMPP_BCMMTL','LST_CHG_USID'),
    t_rec('TPRMPP_BCMMTL','LST_CHG_DTM'),
    t_rec('TPRMPP_BEVALL','ENO'),
    t_rec('TPRMPP_BEVALL','CHG_DTT_YN'),
    t_rec('TPRMPP_BEVALL','FST_ENR_USID'),
    t_rec('TPRMPP_BEVALL','FST_ENR_DTM'),
    t_rec('TPRMPP_BEVALL','DEL_YN'),
    t_rec('TPRMPP_BEVALL','GUID'),
    t_rec('TPRMPP_BEVALL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BEVALL','LST_CHG_USID'),
    t_rec('TPRMPP_BEVALL','LST_CHG_DTM'),
    t_rec('TPRMPP_BSCHDL','ENO'),
    t_rec('TPRMPP_BSCHDL','CHG_DTT_YN'),
    t_rec('TPRMPP_BSCHDL','FST_ENR_USID'),
    t_rec('TPRMPP_BSCHDL','FST_ENR_DTM'),
    t_rec('TPRMPP_BSCHDL','LST_CHG_USID'),
    t_rec('TPRMPP_BSCHDL','LST_CHG_DTM'),
    t_rec('TPRMPP_BRSLTL','CHG_DTT_YN'),
    t_rec('TPRMPP_BRSLTL','FST_ENR_USID'),
    t_rec('TPRMPP_BRSLTL','FST_ENR_DTM'),
    t_rec('TPRMPP_BRSLTL','LST_CHG_USID'),
    t_rec('TPRMPP_BRSLTL','LST_CHG_DTM'),
    t_rec('TPRMPP_CROLEI','GUID'),
    t_rec('TPRMPP_CROLEI','GUID_PRG_SNO'),
    t_rec('TPRMPP_CROLEI','LST_CHG_USID'),
    t_rec('TPRMPP_CFILEM','DEL_YN'),
    t_rec('TPRMPP_CFILEM','GUID'),
    t_rec('TPRMPP_CFILEM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CAPPLL','DEL_YN'),
    t_rec('TPRMPP_CAPPLL','GUID'),
    t_rec('TPRMPP_CAPPLL','GUID_PRG_SNO'),
    t_rec('TPRMPP_CCODEM','GUID'),
    t_rec('TPRMPP_CCODEM','GUID_PRG_SNO'),
    t_rec('TPRMPP_CCODEM','LST_CHG_USID'),
    t_rec('TPRMPP_CCODEM','LST_CHG_DTM'),
    t_rec('TPRMPP_CCODEL','DEL_YN'),
    t_rec('TPRMPP_CCODEL','GUID'),
    t_rec('TPRMPP_CCODEL','GUID_PRG_SNO'),
    t_rec('TPRMPP_CMENUM','LST_CHG_USID'),
    t_rec('TPRMPP_CMENUM','LST_CHG_DTM'),
    t_rec('TPRMPP_CMENUD','LST_CHG_USID'),
    t_rec('TPRMPP_CMENUD','LST_CHG_DTM'),
    t_rec('TPRMPP_CMENUA','LST_CHG_USID'),
    t_rec('TPRMPP_CMENUA','LST_CHG_DTM'),
    t_rec('TPRMPP_CBLBCL','CHG_DTT_YN'),
    t_rec('TPRMPP_CBLBCL','DEL_YN'),
    t_rec('TPRMPP_CBLBCL','GUID'),
    t_rec('TPRMPP_CBLBCL','GUID_PRG_SNO'),
    t_rec('TPRMPP_CAUTHI','GUID'),
    t_rec('TPRMPP_CAUTHI','GUID_PRG_SNO'),
    t_rec('TPRMPP_CAUTHI','LST_CHG_USID'),
    t_rec('TPRMPP_BRDOCL','CHG_DTT_YN'),
    t_rec('TPRMPP_BRDOCL','DEL_YN'),
    t_rec('TPRMPP_BRDOCL','GUID'),
    t_rec('TPRMPP_BRDOCL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BGDOCL','CHG_DTT_YN'),
    t_rec('TPRMPP_BBUGTL','CHG_DTT_YN'),
    t_rec('TPRMPP_BBUGTL','DEL_YN'),
    t_rec('TPRMPP_BBUGTL','GUID'),
    t_rec('TPRMPP_BBUGTL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BRIVGL','FSG_YN'),
    t_rec('TPRMPP_BRIVGL','DEL_YN'),
    t_rec('TPRMPP_BRIVGL','GUID'),
    t_rec('TPRMPP_BRIVGL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPLANL','CHG_DTT_YN'),
    t_rec('TPRMPP_BPLANL','DEL_YN'),
    t_rec('TPRMPP_BPLANL','GUID'),
    t_rec('TPRMPP_BPLANL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BTERMM','GUID'),
    t_rec('TPRMPP_BTERMM','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCOSTL','CHG_DTT_YN'),
    t_rec('TPRMPP_BCOSTL','DEL_YN'),
    t_rec('TPRMPP_BCOSTL','GUID'),
    t_rec('TPRMPP_BCOSTL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BTERML','CHG_DTT_YN'),
    t_rec('TPRMPP_BTERML','GUID'),
    t_rec('TPRMPP_BTERML','GUID_PRG_SNO'),
    t_rec('TPRMPP_BITEML','CHG_DTT_YN'),
    t_rec('TPRMPP_BITEML','DEL_YN'),
    t_rec('TPRMPP_BITEML','GUID'),
    t_rec('TPRMPP_BITEML','GUID_PRG_SNO'),
    t_rec('TPRMPP_BASCTL','DEL_YN'),
    t_rec('TPRMPP_BASCTL','GUID'),
    t_rec('TPRMPP_BASCTL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPOVWL','DEL_YN'),
    t_rec('TPRMPP_BPOVWL','GUID'),
    t_rec('TPRMPP_BPOVWL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCHKLL','DEL_YN'),
    t_rec('TPRMPP_BCHKLL','GUID'),
    t_rec('TPRMPP_BCHKLL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPERFL','DEL_YN'),
    t_rec('TPRMPP_BPERFL','GUID'),
    t_rec('TPRMPP_BPERFL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BPQNAL','DEL_YN'),
    t_rec('TPRMPP_BPQNAL','GUID'),
    t_rec('TPRMPP_BPQNAL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BMQNAL','DEL_YN'),
    t_rec('TPRMPP_BMQNAL','GUID'),
    t_rec('TPRMPP_BMQNAL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BCMMTL','DEL_YN'),
    t_rec('TPRMPP_BCMMTL','GUID'),
    t_rec('TPRMPP_BCMMTL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BSCHDL','DEL_YN'),
    t_rec('TPRMPP_BSCHDL','GUID'),
    t_rec('TPRMPP_BSCHDL','GUID_PRG_SNO'),
    t_rec('TPRMPP_BRSLTL','DEL_YN'),
    t_rec('TPRMPP_BRSLTL','GUID'),
    t_rec('TPRMPP_BRSLTL','GUID_PRG_SNO')
  );
  v_nullable VARCHAR2(1);
BEGIN
  FOR i IN 1..v.COUNT LOOP
    BEGIN
      SELECT nullable INTO v_nullable FROM user_tab_columns
        WHERE table_name=v(i).tbl AND column_name=v(i).col;
      IF v_nullable='Y' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ITPAPP.'||v(i).tbl||' MODIFY ("'||v(i).col||'" NOT NULL)';
      END IF;
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;
  END LOOP;
END;
/

-- ============================================================
-- C. NOT NULL 제약 해제 (운영=NULL, 로컬=NOT NULL) — 14개 컬럼
-- ============================================================
DECLARE
  TYPE t_rec IS RECORD (tbl VARCHAR2(30), col VARCHAR2(30));
  TYPE t_arr IS TABLE OF t_rec;
  v t_arr := t_arr(
    t_rec('TPRMPP_CINFMM','INQ_YN'),
    t_rec('TPRMPP_CFILEM','FL_NM'),
    t_rec('TPRMPP_CFILEM','FL_PYS_NM'),
    t_rec('TPRMPP_CFILEM','FL_KPN_PTH'),
    t_rec('TPRMPP_CDECIM','DCD_STS_C'),
    t_rec('TPRMPP_CBLBMM','APG_FL_USE_YN'),
    t_rec('TPRMPP_CBLBMM','BLB_NM'),
    t_rec('TPRMPP_CBLBMM','BLB_TC'),
    t_rec('TPRMPP_CBLBMM','CMMT_USE_YN'),
    t_rec('TPRMPP_CBLBMM','HED_TAG_USE_YN'),
    t_rec('TPRMPP_CBLBMM','REP_FNC_USE_YN'),
    t_rec('TPRMPP_CBLBMM','SRE_SQN_SNO'),
    t_rec('TPRMPP_CBLBMM','USE_YN'),
    t_rec('TPRMPP_BCMMTM','CNFM_YN')
  );
  v_nullable VARCHAR2(1);
BEGIN
  FOR i IN 1..v.COUNT LOOP
    BEGIN
      SELECT nullable INTO v_nullable FROM user_tab_columns
        WHERE table_name=v(i).tbl AND column_name=v(i).col;
      IF v_nullable='N' THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ITPAPP.'||v(i).tbl||' MODIFY ("'||v(i).col||'" NULL)';
      END IF;
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;
  END LOOP;
END;
/

-- ============================================================
-- D. 컬럼 타입 정합 (#4) — 16개 (widen 6 + shrink 10). 코드컬럼 제외.
-- ============================================================
DECLARE
  TYPE t_rec IS RECORD (tbl VARCHAR2(30), col VARCHAR2(30), newlen NUMBER);
  TYPE t_arr IS TABLE OF t_rec;
  v t_arr := t_arr(
    t_rec('TPRMPP_BPQNAM','QTN_ID',36),
    t_rec('TPRMPP_BMQNAM','QTN_ID',36),
    t_rec('TPRMPP_BRSLTM','SYN_OPNN_CONE',6000),
    t_rec('TPRMPP_BPQNAL','QTN_ID',36),
    t_rec('TPRMPP_BMQNAL','QTN_ID',36),
    t_rec('TPRMPP_BRSLTL','SYN_OPNN_CONE',6000),
    t_rec('TPRMPP_BPQNAM','REP_CONE',2000),
    t_rec('TPRMPP_BMQNAM','REP_CONE',2000),
    t_rec('TPRMPP_BEVALM','CKG_OPNN_CONE',1000),
    t_rec('TPRMPP_BASCTM','CNRC_DT',8),
    t_rec('TPRMPP_BRSLTM','CKG_OPNN_CONE',1000),
    t_rec('TPRMPP_BASCTL','CNRC_DT',8),
    t_rec('TPRMPP_BPQNAL','REP_CONE',2000),
    t_rec('TPRMPP_BMQNAL','REP_CONE',2000),
    t_rec('TPRMPP_BEVALL','CKG_OPNN_CONE',1000),
    t_rec('TPRMPP_BRSLTL','CKG_OPNN_CONE',1000)
  );
  v_cur NUMBER;
BEGIN
  FOR i IN 1..v.COUNT LOOP
    BEGIN
      SELECT char_length INTO v_cur FROM user_tab_columns
        WHERE table_name=v(i).tbl AND column_name=v(i).col;
      IF v_cur <> v(i).newlen THEN
        EXECUTE IMMEDIATE 'ALTER TABLE ITPAPP.'||v(i).tbl||' MODIFY ("'||v(i).col
          ||'" VARCHAR2('||v(i).newlen||' CHAR))';
      END IF;
    EXCEPTION WHEN NO_DATA_FOUND THEN NULL;
    END;
  END LOOP;
END;
/

COMMIT;
