-- TPRMPP_CDECIM 테이블에 결재선상태코드(DCD_STS_C) 컬럼 추가 및 기존 데이터 백필
-- 코드 매핑 (Ccodem DCD_STS):
--   001: 미결재 (DCD_TP IS NULL)
--   002: 승인 (DCD_STS = '승인')
--   003: 반려 (DCD_STS = '반려')

ALTER TABLE TPRMPP_CDECIM ADD DCD_STS_C VARCHAR2(3);
COMMENT ON COLUMN TPRMPP_CDECIM.DCD_STS_C IS '결재선상태코드 (Ccodem DCD_STS)';

UPDATE TPRMPP_CDECIM
SET DCD_STS_C = CASE
    WHEN DCD_TP IS NULL    THEN '001'
    WHEN DCD_STS = '승인'  THEN '002'
    WHEN DCD_STS = '반려'  THEN '003'
    ELSE '001'
END;

COMMIT;

ALTER TABLE TPRMPP_CDECIM MODIFY DCD_STS_C VARCHAR2(3) NOT NULL;
