-- 대금지급 기본(BPAYMM), 상세(BPAYTM), 로그(BPAYML/BPAYTL), 시퀀스 생성
-- Stage 4: 대금지급

CREATE TABLE TPRMPP_BPAYMM (
  DOC_MNG_NO     VARCHAR2(20 CHAR)  NOT NULL,
  DOC_VRS_SNO    NUMBER(9,0)        NOT NULL,
  LST_YN         VARCHAR2(1 CHAR)   DEFAULT 'Y' NOT NULL,
  BG_PRN_TC      VARCHAR2(3 CHAR)   NOT NULL,
  CNCD_RFR_NO    VARCHAR2(30 CHAR)  NOT NULL,
  IT_PTL_STS_TC  VARCHAR2(2 CHAR)   NOT NULL,
  REQ_CONE       VARCHAR2(300 CHAR),
  CTT_NM         VARCHAR2(100 CHAR),
  CTT_AMT        NUMBER(18,3),
  DEL_YN         VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID           VARCHAR2(38 CHAR),
  GUID_PRG_SNO   NUMBER(4,0),
  FST_ENR_DTM    DATE,
  FST_ENR_USID   VARCHAR2(14 CHAR),
  LST_CHG_DTM    DATE,
  LST_CHG_USID   VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BPAYMM PRIMARY KEY (DOC_MNG_NO, DOC_VRS_SNO),
  CONSTRAINT CK_BPAYMM_LST_YN CHECK (LST_YN IN ('Y','N')),
  CONSTRAINT CK_BPAYMM_DEL_YN CHECK (DEL_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BPAYMM                IS '대금지급 기본';
COMMENT ON COLUMN TPRMPP_BPAYMM.DOC_MNG_NO     IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BPAYMM.DOC_VRS_SNO    IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BPAYMM.LST_YN         IS '최종여부';
COMMENT ON COLUMN TPRMPP_BPAYMM.BG_PRN_TC      IS '예산성격구분코드(대상구분)';
COMMENT ON COLUMN TPRMPP_BPAYMM.CNCD_RFR_NO    IS '관련참조번호(대상관리번호)';
COMMENT ON COLUMN TPRMPP_BPAYMM.IT_PTL_STS_TC  IS 'IT포탈상태구분코드';
COMMENT ON COLUMN TPRMPP_BPAYMM.REQ_CONE       IS '요청내용';
COMMENT ON COLUMN TPRMPP_BPAYMM.CTT_NM         IS '계약명';
COMMENT ON COLUMN TPRMPP_BPAYMM.CTT_AMT        IS '계약금액';
COMMENT ON COLUMN TPRMPP_BPAYMM.DEL_YN         IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPAYMM.GUID           IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPAYMM.GUID_PRG_SNO   IS 'GUID프로그램일련번호';
COMMENT ON COLUMN TPRMPP_BPAYMM.FST_ENR_DTM    IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPAYMM.FST_ENR_USID   IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYMM.LST_CHG_DTM    IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPAYMM.LST_CHG_USID   IS '최종변경사용자ID';
CREATE INDEX IDX_BPAYMM_TGT ON TPRMPP_BPAYMM (BG_PRN_TC, CNCD_RFR_NO);
CREATE INDEX IDX_BPAYMM_STS ON TPRMPP_BPAYMM (IT_PTL_STS_TC);

CREATE TABLE TPRMPP_BPAYTM (
  DOC_MNG_NO     VARCHAR2(20 CHAR)  NOT NULL,
  DOC_VRS_SNO    NUMBER(9,0)        NOT NULL,
  DFR_TOD        NUMBER(5,0)        NOT NULL,
  DFR_AMT        NUMBER(18,3),
  DFR_DT         VARCHAR2(8 CHAR),
  DFR_MPL_DT     VARCHAR2(8 CHAR),
  OPNN_CONE      VARCHAR2(1000 CHAR),
  DEL_YN         VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID           VARCHAR2(38 CHAR),
  GUID_PRG_SNO   NUMBER(4,0),
  FST_ENR_DTM    DATE,
  FST_ENR_USID   VARCHAR2(14 CHAR),
  LST_CHG_DTM    DATE,
  LST_CHG_USID   VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BPAYTM PRIMARY KEY (DOC_MNG_NO, DOC_VRS_SNO, DFR_TOD),
  CONSTRAINT CK_BPAYTM_DEL_YN CHECK (DEL_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BPAYTM             IS '대금지급 상세(회차별 지급)';
COMMENT ON COLUMN TPRMPP_BPAYTM.DOC_MNG_NO  IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BPAYTM.DOC_VRS_SNO IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BPAYTM.DFR_TOD     IS '지급회차';
COMMENT ON COLUMN TPRMPP_BPAYTM.DFR_AMT     IS '지급금액';
COMMENT ON COLUMN TPRMPP_BPAYTM.DFR_DT      IS '지급일자';
COMMENT ON COLUMN TPRMPP_BPAYTM.DFR_MPL_DT  IS '지급예정일자';
COMMENT ON COLUMN TPRMPP_BPAYTM.OPNN_CONE   IS '의견내용';
COMMENT ON COLUMN TPRMPP_BPAYTM.DEL_YN      IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPAYTM.GUID        IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPAYTM.GUID_PRG_SNO IS 'GUID프로그램일련번호';
COMMENT ON COLUMN TPRMPP_BPAYTM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPAYTM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYTM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPAYTM.LST_CHG_USID IS '최종변경사용자ID';

CREATE TABLE TPRMPP_BPAYML (
  LOG_HIS_TGR_SNO NUMBER(18,0) NOT NULL,
  CHG_DTT_YN      VARCHAR2(1 CHAR),
  CHG_DTM         TIMESTAMP(9),
  CHG_USID        VARCHAR2(14 CHAR),
  DEL_YN          VARCHAR2(1 CHAR),
  GUID            VARCHAR2(38 CHAR),
  GUID_PRG_SNO    NUMBER(4,0),
  FST_ENR_DTM     DATE,
  FST_ENR_USID    VARCHAR2(14 CHAR),
  LST_CHG_DTM     DATE,
  LST_CHG_USID    VARCHAR2(14 CHAR),
  DOC_MNG_NO      VARCHAR2(20 CHAR),
  DOC_VRS_SNO     NUMBER(9,0),
  LST_YN          VARCHAR2(1 CHAR),
  BG_PRN_TC       VARCHAR2(3 CHAR),
  CNCD_RFR_NO     VARCHAR2(30 CHAR),
  IT_PTL_STS_TC   VARCHAR2(2 CHAR),
  REQ_CONE        VARCHAR2(300 CHAR),
  CTT_NM          VARCHAR2(100 CHAR),
  CTT_AMT         NUMBER(18,3),
  CONSTRAINT PK_TPRMPP_BPAYML PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE  TPRMPP_BPAYML                    IS '대금지급 기본 변경 로그';
COMMENT ON COLUMN TPRMPP_BPAYML.LOG_HIS_TGR_SNO   IS '로그이력대상일련번호';
COMMENT ON COLUMN TPRMPP_BPAYML.CHG_DTT_YN        IS '변경상세여부';
COMMENT ON COLUMN TPRMPP_BPAYML.CHG_DTM           IS '변경일시';
COMMENT ON COLUMN TPRMPP_BPAYML.CHG_USID          IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYML.DEL_YN            IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPAYML.GUID              IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPAYML.GUID_PRG_SNO      IS 'GUID프로그램일련번호';
COMMENT ON COLUMN TPRMPP_BPAYML.FST_ENR_DTM       IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPAYML.FST_ENR_USID      IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYML.LST_CHG_DTM       IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPAYML.LST_CHG_USID      IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYML.DOC_MNG_NO        IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BPAYML.DOC_VRS_SNO       IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BPAYML.LST_YN            IS '최종여부';
COMMENT ON COLUMN TPRMPP_BPAYML.BG_PRN_TC         IS '예산성격구분코드(대상구분)';
COMMENT ON COLUMN TPRMPP_BPAYML.CNCD_RFR_NO       IS '관련참조번호(대상관리번호)';
COMMENT ON COLUMN TPRMPP_BPAYML.IT_PTL_STS_TC     IS 'IT포탈상태구분코드';
COMMENT ON COLUMN TPRMPP_BPAYML.REQ_CONE          IS '요청내용';
COMMENT ON COLUMN TPRMPP_BPAYML.CTT_NM            IS '계약명';
COMMENT ON COLUMN TPRMPP_BPAYML.CTT_AMT           IS '계약금액';

CREATE TABLE TPRMPP_BPAYTL (
  LOG_HIS_TGR_SNO NUMBER(18,0) NOT NULL,
  CHG_DTT_YN      VARCHAR2(1 CHAR),
  CHG_DTM         TIMESTAMP(9),
  CHG_USID        VARCHAR2(14 CHAR),
  DEL_YN          VARCHAR2(1 CHAR),
  GUID            VARCHAR2(38 CHAR),
  GUID_PRG_SNO    NUMBER(4,0),
  FST_ENR_DTM     DATE,
  FST_ENR_USID    VARCHAR2(14 CHAR),
  LST_CHG_DTM     DATE,
  LST_CHG_USID    VARCHAR2(14 CHAR),
  DOC_MNG_NO      VARCHAR2(20 CHAR),
  DOC_VRS_SNO     NUMBER(9,0),
  DFR_TOD         NUMBER(5,0),
  DFR_AMT         NUMBER(18,3),
  DFR_DT          VARCHAR2(8 CHAR),
  DFR_MPL_DT      VARCHAR2(8 CHAR),
  OPNN_CONE       VARCHAR2(1000 CHAR),
  CONSTRAINT PK_TPRMPP_BPAYTL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE  TPRMPP_BPAYTL                    IS '대금지급 상세 변경 로그';
COMMENT ON COLUMN TPRMPP_BPAYTL.LOG_HIS_TGR_SNO   IS '로그이력대상일련번호';
COMMENT ON COLUMN TPRMPP_BPAYTL.CHG_DTT_YN        IS '변경상세여부';
COMMENT ON COLUMN TPRMPP_BPAYTL.CHG_DTM           IS '변경일시';
COMMENT ON COLUMN TPRMPP_BPAYTL.CHG_USID          IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYTL.DEL_YN            IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPAYTL.GUID              IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPAYTL.GUID_PRG_SNO      IS 'GUID프로그램일련번호';
COMMENT ON COLUMN TPRMPP_BPAYTL.FST_ENR_DTM       IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPAYTL.FST_ENR_USID      IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYTL.LST_CHG_DTM       IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPAYTL.LST_CHG_USID      IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPAYTL.DOC_MNG_NO        IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BPAYTL.DOC_VRS_SNO       IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BPAYTL.DFR_TOD           IS '지급회차';
COMMENT ON COLUMN TPRMPP_BPAYTL.DFR_AMT           IS '지급금액';
COMMENT ON COLUMN TPRMPP_BPAYTL.DFR_DT            IS '지급일자';
COMMENT ON COLUMN TPRMPP_BPAYTL.DFR_MPL_DT        IS '지급예정일자';
COMMENT ON COLUMN TPRMPP_BPAYTL.OPNN_CONE         IS '의견내용';

CREATE SEQUENCE SEQ_BPAYMM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BPAYML START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
CREATE SEQUENCE SEQ_BPAYTL START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
