-- Cappla 채번 리넘버링 + 복합 PK (APF_MNG_NO, APF_REL_SNO) 도입
-- 신청서 단위 1~N 채번으로 전환하고, 전역 단일 PK(APF_REL_SNO)를 복합 PK로 재구성

-- 1단계: 임시 컬럼 + 신청서 단위 채번
ALTER TABLE TPRMPP_CAPPLA ADD APF_REL_SNO_NEW NUMBER;

MERGE INTO TPRMPP_CAPPLA tgt
USING (
    SELECT APF_REL_SNO,
           ROW_NUMBER() OVER (PARTITION BY APF_MNG_NO ORDER BY APF_REL_SNO) AS NEW_SNO
    FROM TPRMPP_CAPPLA
) src
ON (tgt.APF_REL_SNO = src.APF_REL_SNO)
WHEN MATCHED THEN UPDATE SET tgt.APF_REL_SNO_NEW = src.NEW_SNO;

COMMIT;

-- 2단계: PK 제약 해제 + 컬럼 교체
ALTER TABLE TPRMPP_CAPPLA DROP CONSTRAINT PK_CAPPLA;

UPDATE TPRMPP_CAPPLA SET APF_REL_SNO = APF_REL_SNO_NEW;
COMMIT;

ALTER TABLE TPRMPP_CAPPLA DROP COLUMN APF_REL_SNO_NEW;

-- 3단계: 복합 PK 재생성
ALTER TABLE TPRMPP_CAPPLA ADD CONSTRAINT PK_CAPPLA PRIMARY KEY (APF_MNG_NO, APF_REL_SNO);

-- 4단계: 시퀀스 DROP (신청서 단위 명시 채번으로 전환)
DROP SEQUENCE SEQ_CAPPLA;
