-- 컬럼 표준화 (column-domain-standardization.plan.md 반영)
--   IOE_C        : VARCHAR2(3)
--   DFR_CLE      → DFR_CLE_C      : VARCHAR2(3)
--   BG_FDTN      → BG_FDTN_CONE   : VARCHAR2(300)

-- ============================================================
-- 1) IOE_C: 기존 데이터 3자 초과분 절단 후 길이 축소
--    (V003 이후 단축 cdva 저장 정책에 따라 앞 3자만 의미가 있음)
-- ============================================================
UPDATE ITPAPP.TAAABB_BITEMM   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
UPDATE ITPAPP.TAAABB_BITEML   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
UPDATE ITPAPP.TAAABB_BBUGTM   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
UPDATE ITPAPP.TAAABB_BBUGTL   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTM   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTL   SET IOE_C = SUBSTR(IOE_C, 1, 3) WHERE LENGTH(IOE_C) > 3;
COMMIT;

ALTER TABLE ITPAPP.TAAABB_BITEMM   MODIFY (IOE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BITEML   MODIFY (IOE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BBUGTM   MODIFY (IOE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BBUGTL   MODIFY (IOE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTM   MODIFY (IOE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTL   MODIFY (IOE_C VARCHAR2(3));

-- ============================================================
-- 2) DFR_CLE → DFR_CLE_C, VARCHAR2(3)
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BITEMM   RENAME COLUMN DFR_CLE TO DFR_CLE_C;
ALTER TABLE ITPAPP.TAAABB_BITEML   RENAME COLUMN DFR_CLE TO DFR_CLE_C;
ALTER TABLE ITPAPP.TAAABB_BCOSTM   RENAME COLUMN DFR_CLE TO DFR_CLE_C;
ALTER TABLE ITPAPP.TAAABB_BCOSTL   RENAME COLUMN DFR_CLE TO DFR_CLE_C;
ALTER TABLE ITPAPP.TAAABB_BTERMM   RENAME COLUMN DFR_CLE TO DFR_CLE_C;
ALTER TABLE ITPAPP.TAAABB_BTERML   RENAME COLUMN DFR_CLE TO DFR_CLE_C;

UPDATE ITPAPP.TAAABB_BITEMM   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
UPDATE ITPAPP.TAAABB_BITEML   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTM   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTL   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
UPDATE ITPAPP.TAAABB_BTERMM   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
UPDATE ITPAPP.TAAABB_BTERML   SET DFR_CLE_C = SUBSTR(DFR_CLE_C, 1, 3) WHERE LENGTH(DFR_CLE_C) > 3;
COMMIT;

ALTER TABLE ITPAPP.TAAABB_BITEMM   MODIFY (DFR_CLE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BITEML   MODIFY (DFR_CLE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTM   MODIFY (DFR_CLE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTL   MODIFY (DFR_CLE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BTERMM   MODIFY (DFR_CLE_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BTERML   MODIFY (DFR_CLE_C VARCHAR2(3));

COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.DFR_CLE_C   IS '지급주기코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.DFR_CLE_C   IS '지급주기코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.DFR_CLE_C   IS '지급주기코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.DFR_CLE_C   IS '지급주기코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.DFR_CLE_C   IS '지급주기코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.DFR_CLE_C   IS '지급주기코드';

-- ============================================================
-- 3) BG_FDTN → BG_FDTN_CONE, VARCHAR2(300)
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BITEMM   RENAME COLUMN BG_FDTN TO BG_FDTN_CONE;
ALTER TABLE ITPAPP.TAAABB_BITEML   RENAME COLUMN BG_FDTN TO BG_FDTN_CONE;

ALTER TABLE ITPAPP.TAAABB_BITEMM   MODIFY (BG_FDTN_CONE VARCHAR2(300));
ALTER TABLE ITPAPP.TAAABB_BITEML   MODIFY (BG_FDTN_CONE VARCHAR2(300));

COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.BG_FDTN_CONE IS '예산근거내용';
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.BG_FDTN_CONE IS '예산근거내용';
