-- 팀코드(BICE_TEM_C)는 실제 5자리 숫자이나
-- V20260519_002 표준화 시 VARCHAR2(3)으로 잘못 축소되어 ORA-12899 발생.
-- VARCHAR2(3) → VARCHAR2(5)로 확장.
-- 대상: V20260521_006 prefix rename 이후 TPRMPP_* 테이블.

ALTER TABLE ITPAPP.TPRMPP_BTERMM MODIFY (BICE_TEM_C VARCHAR2(5));
ALTER TABLE ITPAPP.TPRMPP_BTERML MODIFY (BICE_TEM_C VARCHAR2(5));
ALTER TABLE ITPAPP.TPRMPP_BCOSTM MODIFY (BICE_TEM_C VARCHAR2(5));
ALTER TABLE ITPAPP.TPRMPP_BCOSTL MODIFY (BICE_TEM_C VARCHAR2(5));
