-- 정보화사업 품목 일련번호 표준화: GCL_SNO -> SNO, NUMBER(9)
-- 품목관리번호 표준화: GCL_MNG_NO VARCHAR2(16)

DECLARE
  has_old NUMBER;
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BITEML' AND column_name='GCL_SNO';
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BITEML' AND column_name='SNO';

  IF has_new=0 AND has_old=1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEML RENAME COLUMN GCL_SNO TO SNO';
  END IF;
END;
/

DECLARE
  has_old NUMBER;
  has_new NUMBER;
BEGIN
  SELECT COUNT(*) INTO has_old FROM user_tab_columns WHERE table_name='TPRMPP_BITEMM' AND column_name='GCL_SNO';
  SELECT COUNT(*) INTO has_new FROM user_tab_columns WHERE table_name='TPRMPP_BITEMM' AND column_name='SNO';

  IF has_new=0 AND has_old=1 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEMM RENAME COLUMN GCL_SNO TO SNO';
  END IF;
END;
/

DECLARE
  has_col NUMBER;
  precision_value NUMBER;
  over_cnt NUMBER;
BEGIN
  FOR t IN (
    SELECT 'TPRMPP_BITEML' table_name FROM dual UNION ALL
    SELECT 'TPRMPP_BITEMM' table_name FROM dual
  ) LOOP
    SELECT COUNT(*) INTO has_col
      FROM user_tab_columns
     WHERE table_name=t.table_name
       AND column_name='GCL_MNG_NO';

    IF has_col=1 THEN
      EXECUTE IMMEDIATE 'UPDATE ' || t.table_name || ' SET GCL_MNG_NO=TRIM(GCL_MNG_NO) WHERE GCL_MNG_NO IS NOT NULL';
      EXECUTE IMMEDIATE 'ALTER TABLE ' || t.table_name || ' MODIFY (GCL_MNG_NO VARCHAR2(16 CHAR))';
      EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || t.table_name || '.GCL_MNG_NO IS ''' || UNISTR('\D488\BAA9\AD00\B9AC\BC88\D638') || '''';
    END IF;

    SELECT COUNT(*), MAX(data_precision) INTO has_col, precision_value
      FROM user_tab_columns
     WHERE table_name=t.table_name
       AND column_name='SNO';

    IF has_col=1 THEN
      IF t.table_name='TPRMPP_BITEML' AND NVL(precision_value, 38)>9 THEN
        EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEML ADD (SNO_STD_TMP NUMBER(9))';
        EXECUTE IMMEDIATE 'UPDATE TPRMPP_BITEML SET SNO_STD_TMP = SNO';
        EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEML DROP COLUMN SNO';
        EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEML RENAME COLUMN SNO_STD_TMP TO SNO';
      ELSE
        EXECUTE IMMEDIATE 'ALTER TABLE ' || t.table_name || ' MODIFY (SNO NUMBER(9))';
      END IF;
      EXECUTE IMMEDIATE 'COMMENT ON COLUMN ' || t.table_name || '.SNO IS ''' || UNISTR('\C77C\B828\BC88\D638') || '''';
    END IF;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEMM RENAME CONSTRAINT "PK_TAAABB_BITEMM_GCL_MNG_NO_GCL_SNO" TO "PK_BITEMM_GCL_MNG_NO_SNO"';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'ALTER INDEX "PK_TAAABB_BITEMM_GCL_MNG_NO_GCL_SNO" RENAME TO "PK_BITEMM_GCL_MNG_NO_SNO"';
EXCEPTION
  WHEN OTHERS THEN NULL;
END;
/
