-- 컬럼 표준화
--   IT_MNGC_BG     → IT_MNGC_BG_AMT  : NUMBER(18,3)   -- 금액 확장 + scale 변경
--   DUP_BG         → DUP_BG_AMT      : NUMBER(18,3)
--   DOC_CONE       → DOC_INF         : CLOB           -- BLOB → CLOB
--   REQ_CONE       → REQ_INF         : CLOB
--   IVG_CONE, NAC_CONE, CMMT_CONE,
--   PLN_DTL_CONE, IT_PRJ_CONE, IT_BG_CONE : VARCHAR2(4000)  -- CLOB → VARCHAR2
--   IT_PRJ_RMK, CPIT_BG_RMK, MNGC_BG_RMK  : VARCHAR2(600)
--
-- 패턴: 기존 컬럼을 _BAK 으로 RENAME → 신규 컬럼 ADD →
--      데이터 복사 (NUMBER, SUBSTR, DBMS_LOB.SUBSTR, DBMS_LOB.CONVERTTOCLOB) →
--      _BAK DROP → COMMENT.

-- ============================================================
-- 1) IT_MNGC_BG → IT_MNGC_BG_AMT : NUMBER(18,3)
--    대상: TAAABB_BCOSTM, TAAABB_BCOSTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN IT_MNGC_BG TO IT_MNGC_BG_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (IT_MNGC_BG_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BCOSTM SET IT_MNGC_BG_AMT = IT_MNGC_BG_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN IT_MNGC_BG_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.IT_MNGC_BG_AMT IS '전산업무비예산금액';

ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN IT_MNGC_BG TO IT_MNGC_BG_BAK;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (IT_MNGC_BG_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BCOSTL SET IT_MNGC_BG_AMT = IT_MNGC_BG_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN IT_MNGC_BG_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.IT_MNGC_BG_AMT IS '전산업무비예산금액';

-- ============================================================
-- 2) DUP_BG → DUP_BG_AMT : NUMBER(18,3)
--    대상: TAAABB_BBUGTM, TAAABB_BBUGTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BBUGTM RENAME COLUMN DUP_BG TO DUP_BG_BAK;
ALTER TABLE ITPAPP.TAAABB_BBUGTM ADD (DUP_BG_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BBUGTM SET DUP_BG_AMT = DUP_BG_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BBUGTM DROP COLUMN DUP_BG_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BBUGTM.DUP_BG_AMT IS '편성예산금액';

ALTER TABLE ITPAPP.TAAABB_BBUGTL RENAME COLUMN DUP_BG TO DUP_BG_BAK;
ALTER TABLE ITPAPP.TAAABB_BBUGTL ADD (DUP_BG_AMT NUMBER(18,3));
UPDATE ITPAPP.TAAABB_BBUGTL SET DUP_BG_AMT = DUP_BG_BAK;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BBUGTL DROP COLUMN DUP_BG_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BBUGTL.DUP_BG_AMT IS '편성예산금액';

-- ============================================================
-- 3) DOC_CONE(BLOB) → DOC_INF(CLOB)
--    대상: TAAABB_BGDOCM, TAAABB_BGDOCL
--    BLOB → CLOB 변환은 DBMS_LOB.CONVERTTOCLOB 사용 (PL/SQL 블록).
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BGDOCM RENAME COLUMN DOC_CONE TO DOC_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BGDOCM ADD (DOC_INF CLOB);
DECLARE
    v_dest_offset  INTEGER;
    v_src_offset   INTEGER;
    v_lang_context INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning      INTEGER;
    v_clob         CLOB;
BEGIN
    FOR r IN (SELECT ROWID rid, DOC_CONE_BAK FROM ITPAPP.TAAABB_BGDOCM WHERE DOC_CONE_BAK IS NOT NULL) LOOP
        DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
        v_dest_offset := 1;
        v_src_offset  := 1;
        DBMS_LOB.CONVERTTOCLOB(v_clob, r.DOC_CONE_BAK, DBMS_LOB.LOBMAXSIZE,
                               v_dest_offset, v_src_offset,
                               NLS_CHARSET_ID('AL32UTF8'), v_lang_context, v_warning);
        UPDATE ITPAPP.TAAABB_BGDOCM SET DOC_INF = v_clob WHERE ROWID = r.rid;
        DBMS_LOB.FREETEMPORARY(v_clob);
    END LOOP;
END;
/
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BGDOCM DROP COLUMN DOC_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BGDOCM.DOC_INF IS '문서정보';

ALTER TABLE ITPAPP.TAAABB_BGDOCL RENAME COLUMN DOC_CONE TO DOC_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BGDOCL ADD (DOC_INF CLOB);
DECLARE
    v_dest_offset  INTEGER;
    v_src_offset   INTEGER;
    v_lang_context INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning      INTEGER;
    v_clob         CLOB;
BEGIN
    FOR r IN (SELECT ROWID rid, DOC_CONE_BAK FROM ITPAPP.TAAABB_BGDOCL WHERE DOC_CONE_BAK IS NOT NULL) LOOP
        DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
        v_dest_offset := 1;
        v_src_offset  := 1;
        DBMS_LOB.CONVERTTOCLOB(v_clob, r.DOC_CONE_BAK, DBMS_LOB.LOBMAXSIZE,
                               v_dest_offset, v_src_offset,
                               NLS_CHARSET_ID('AL32UTF8'), v_lang_context, v_warning);
        UPDATE ITPAPP.TAAABB_BGDOCL SET DOC_INF = v_clob WHERE ROWID = r.rid;
        DBMS_LOB.FREETEMPORARY(v_clob);
    END LOOP;
END;
/
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BGDOCL DROP COLUMN DOC_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BGDOCL.DOC_INF IS '문서정보';

-- ============================================================
-- 4) REQ_CONE(BLOB) → REQ_INF(CLOB)
--    대상: TAAABB_BRDOCM, TAAABB_BRDOCL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BRDOCM RENAME COLUMN REQ_CONE TO REQ_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BRDOCM ADD (REQ_INF CLOB);
DECLARE
    v_dest_offset  INTEGER;
    v_src_offset   INTEGER;
    v_lang_context INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning      INTEGER;
    v_clob         CLOB;
BEGIN
    FOR r IN (SELECT ROWID rid, REQ_CONE_BAK FROM ITPAPP.TAAABB_BRDOCM WHERE REQ_CONE_BAK IS NOT NULL) LOOP
        DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
        v_dest_offset := 1;
        v_src_offset  := 1;
        DBMS_LOB.CONVERTTOCLOB(v_clob, r.REQ_CONE_BAK, DBMS_LOB.LOBMAXSIZE,
                               v_dest_offset, v_src_offset,
                               NLS_CHARSET_ID('AL32UTF8'), v_lang_context, v_warning);
        UPDATE ITPAPP.TAAABB_BRDOCM SET REQ_INF = v_clob WHERE ROWID = r.rid;
        DBMS_LOB.FREETEMPORARY(v_clob);
    END LOOP;
END;
/
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRDOCM DROP COLUMN REQ_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BRDOCM.REQ_INF IS '요구사항정보';

ALTER TABLE ITPAPP.TAAABB_BRDOCL RENAME COLUMN REQ_CONE TO REQ_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BRDOCL ADD (REQ_INF CLOB);
DECLARE
    v_dest_offset  INTEGER;
    v_src_offset   INTEGER;
    v_lang_context INTEGER := DBMS_LOB.DEFAULT_LANG_CTX;
    v_warning      INTEGER;
    v_clob         CLOB;
BEGIN
    FOR r IN (SELECT ROWID rid, REQ_CONE_BAK FROM ITPAPP.TAAABB_BRDOCL WHERE REQ_CONE_BAK IS NOT NULL) LOOP
        DBMS_LOB.CREATETEMPORARY(v_clob, TRUE);
        v_dest_offset := 1;
        v_src_offset  := 1;
        DBMS_LOB.CONVERTTOCLOB(v_clob, r.REQ_CONE_BAK, DBMS_LOB.LOBMAXSIZE,
                               v_dest_offset, v_src_offset,
                               NLS_CHARSET_ID('AL32UTF8'), v_lang_context, v_warning);
        UPDATE ITPAPP.TAAABB_BRDOCL SET REQ_INF = v_clob WHERE ROWID = r.rid;
        DBMS_LOB.FREETEMPORARY(v_clob);
    END LOOP;
END;
/
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRDOCL DROP COLUMN REQ_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BRDOCL.REQ_INF IS '요구사항정보';

-- ============================================================
-- 5) IVG_CONE : CLOB → VARCHAR2(4000)
--    대상: TAAABB_BRIVGM, TAAABB_BRIVGL
--    CLOB → VARCHAR2 은 DBMS_LOB.SUBSTR 사용 (앞 4000자만 유지).
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BRIVGM RENAME COLUMN IVG_CONE TO IVG_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BRIVGM ADD (IVG_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BRIVGM SET IVG_CONE = DBMS_LOB.SUBSTR(IVG_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRIVGM DROP COLUMN IVG_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BRIVGM.IVG_CONE IS '의견내용';

ALTER TABLE ITPAPP.TAAABB_BRIVGL RENAME COLUMN IVG_CONE TO IVG_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BRIVGL ADD (IVG_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BRIVGL SET IVG_CONE = DBMS_LOB.SUBSTR(IVG_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRIVGL DROP COLUMN IVG_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BRIVGL.IVG_CONE IS '의견내용';

-- ============================================================
-- 6) NAC_CONE : CLOB → VARCHAR2(4000)
--    대상: TAAABB_CBLBCM, TAAABB_CBLBCL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_CBLBCM RENAME COLUMN NAC_CONE TO NAC_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_CBLBCM ADD (NAC_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_CBLBCM SET NAC_CONE = DBMS_LOB.SUBSTR(NAC_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBCM DROP COLUMN NAC_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CBLBCM.NAC_CONE IS '게시물내용';

ALTER TABLE ITPAPP.TAAABB_CBLBCL RENAME COLUMN NAC_CONE TO NAC_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_CBLBCL ADD (NAC_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_CBLBCL SET NAC_CONE = DBMS_LOB.SUBSTR(NAC_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBCL DROP COLUMN NAC_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CBLBCL.NAC_CONE IS '게시물내용';

-- ============================================================
-- 7) CMMT_CONE : CLOB → VARCHAR2(4000)
--    대상: TAAABB_CCMMTM, TAAABB_CCMMTL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_CCMMTM RENAME COLUMN CMMT_CONE TO CMMT_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_CCMMTM ADD (CMMT_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_CCMMTM SET CMMT_CONE = DBMS_LOB.SUBSTR(CMMT_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CCMMTM DROP COLUMN CMMT_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CCMMTM.CMMT_CONE IS '댓글내용';

ALTER TABLE ITPAPP.TAAABB_CCMMTL RENAME COLUMN CMMT_CONE TO CMMT_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_CCMMTL ADD (CMMT_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_CCMMTL SET CMMT_CONE = DBMS_LOB.SUBSTR(CMMT_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CCMMTL DROP COLUMN CMMT_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_CCMMTL.CMMT_CONE IS '댓글내용';

-- ============================================================
-- 8) Bplanm 계획세부/IT프로젝트/IT예산 내용 : CLOB → VARCHAR2(4000)
--    대상: TAAABB_BPLANM, TAAABB_BPLANL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN PLN_DTL_CONE TO PLN_DTL_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (PLN_DTL_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANM SET PLN_DTL_CONE = DBMS_LOB.SUBSTR(PLN_DTL_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN PLN_DTL_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.PLN_DTL_CONE IS '계획세부내용';

ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN IT_PRJ_CONE TO IT_PRJ_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (IT_PRJ_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANM SET IT_PRJ_CONE = DBMS_LOB.SUBSTR(IT_PRJ_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN IT_PRJ_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.IT_PRJ_CONE IS 'IT프로젝트내용';

ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN IT_BG_CONE TO IT_BG_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (IT_BG_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANM SET IT_BG_CONE = DBMS_LOB.SUBSTR(IT_BG_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN IT_BG_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.IT_BG_CONE IS 'IT예산내용';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN PLN_DTL_CONE TO PLN_DTL_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (PLN_DTL_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANL SET PLN_DTL_CONE = DBMS_LOB.SUBSTR(PLN_DTL_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN PLN_DTL_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.PLN_DTL_CONE IS '계획세부내용';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN IT_PRJ_CONE TO IT_PRJ_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (IT_PRJ_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANL SET IT_PRJ_CONE = DBMS_LOB.SUBSTR(IT_PRJ_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN IT_PRJ_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.IT_PRJ_CONE IS 'IT프로젝트내용';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN IT_BG_CONE TO IT_BG_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (IT_BG_CONE VARCHAR2(4000));
UPDATE ITPAPP.TAAABB_BPLANL SET IT_BG_CONE = DBMS_LOB.SUBSTR(IT_BG_CONE_BAK, 4000, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN IT_BG_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.IT_BG_CONE IS 'IT예산내용';

-- ============================================================
-- 9) Bplanm 비고 3종 : CLOB → VARCHAR2(600)
--    대상: TAAABB_BPLANM, TAAABB_BPLANL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN IT_PRJ_RMK TO IT_PRJ_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (IT_PRJ_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANM SET IT_PRJ_RMK = DBMS_LOB.SUBSTR(IT_PRJ_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN IT_PRJ_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.IT_PRJ_RMK IS 'IT예산비고';

ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN CPIT_BG_RMK TO CPIT_BG_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (CPIT_BG_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANM SET CPIT_BG_RMK = DBMS_LOB.SUBSTR(CPIT_BG_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN CPIT_BG_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.CPIT_BG_RMK IS '자본예산비고';

ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN MNGC_BG_RMK TO MNGC_BG_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (MNGC_BG_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANM SET MNGC_BG_RMK = DBMS_LOB.SUBSTR(MNGC_BG_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN MNGC_BG_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.MNGC_BG_RMK IS '관리비예산비고';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN IT_PRJ_RMK TO IT_PRJ_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (IT_PRJ_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANL SET IT_PRJ_RMK = DBMS_LOB.SUBSTR(IT_PRJ_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN IT_PRJ_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.IT_PRJ_RMK IS 'IT예산비고';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN CPIT_BG_RMK TO CPIT_BG_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (CPIT_BG_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANL SET CPIT_BG_RMK = DBMS_LOB.SUBSTR(CPIT_BG_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN CPIT_BG_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.CPIT_BG_RMK IS '자본예산비고';

ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN MNGC_BG_RMK TO MNGC_BG_RMK_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (MNGC_BG_RMK VARCHAR2(600));
UPDATE ITPAPP.TAAABB_BPLANL SET MNGC_BG_RMK = DBMS_LOB.SUBSTR(MNGC_BG_RMK_BAK, 600, 1);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN MNGC_BG_RMK_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.MNGC_BG_RMK IS '관리비예산비고';
