-- V20260607_004__RenameEstimateDetailTables.sql
-- 소요예산 산정 상세 테이블 명명규칙 정합: BESTID→BESTTM, BESTIDL→BESTTL, SEQ_BESTIDL→SEQ_BESTTL.
-- 마스터(TPRMPP_BESTIM / TPRMPP_BESTIL / SEQ_BESTIL)는 변경하지 않습니다.

-- 1. TPRMPP_BESTID → TPRMPP_BESTTM
ALTER TABLE TPRMPP_BESTID RENAME CONSTRAINT PK_TPRMPP_BESTID  TO PK_TPRMPP_BESTTM;
ALTER TABLE TPRMPP_BESTID RENAME CONSTRAINT CK_BESTID_DEL_YN  TO CK_BESTTM_DEL_YN;
ALTER TABLE TPRMPP_BESTID RENAME TO TPRMPP_BESTTM;

-- 2. TPRMPP_BESTIDL → TPRMPP_BESTTL
ALTER TABLE TPRMPP_BESTIDL RENAME CONSTRAINT PK_TPRMPP_BESTIDL TO PK_TPRMPP_BESTTL;
ALTER TABLE TPRMPP_BESTIDL RENAME TO TPRMPP_BESTTL;

-- 3. SEQ_BESTIDL → SEQ_BESTTL  (AuditLogIdGenerator가 로그 엔티티 @Table명에서 파생하는 시퀀스)
RENAME SEQ_BESTIDL TO SEQ_BESTTL;

-- 4. 테이블 코멘트 갱신
COMMENT ON TABLE TPRMPP_BESTTM IS '소요예산 산정 상세(팀별 산정)';
COMMENT ON TABLE TPRMPP_BESTTL IS '소요예산 산정 상세 변경 로그';
