-- 컬럼 표준화 후속 인덱스 복구
--   V20260519_002 에서 BICE_DPM → BICE_DPM_C 로 RENAME(DROP/re-ADD) 패턴 적용 시
--   기존 인덱스 IDX_TAAABB_BCOSTM_BICE_DPM_DEL_YN_LST_YN (V20260513_004 에서 생성)이
--   함께 삭제됨. 동일 의도의 인덱스를 새 컬럼명으로 재생성한다.
CREATE INDEX ITPAPP.IDX_TAAABB_BCOSTM_BICE_DPM_C_DEL_YN_LST_YN
    ON ITPAPP.TAAABB_BCOSTM (BICE_DPM_C, DEL_YN, LST_YN)
    TABLESPACE USERS;
