-- V20260624_001__BprojCodeToNameColumns.sql
-- TPRMPP_BPROJM/BPROJL: 사업유형/기술분야/고객유형/업무구분을 코드값→코드값명 저장으로 전환.
--  1) 컬럼 rename + 타입 확장
--     - BZ_TP_C(6)            -> ABUS_PPO_CONE(300)   사업목적내용(사업유형명)
--     - IT_PTL_TCHN_TP_TC(2)  -> SKL_FLD_NM(500)      기술분야명
--     - CST_TP_TC(3)          -> CST_TP_TC_NM(1000)   고객유형구분코드명
--     - BZ_DTT_NM(100)        -> BZ_DTT_NM(100, 불변)  업무구분명
--  2) 기존 코드값을 CCODEM 코드값명으로 변환(NVL로 미매칭/자유입력/널 보존).
--  3) 공통코드 그룹ID 통일: PRJ_TP -> ABUS_PPO, IT_PTL_TCHN_TP_TC -> SKL_FLD.
-- 주의: 적용 후 수정 금지(Flyway 체크섬). 추가 변경은 항상 새 버전 스크립트로.

-- 1) 컬럼 rename + 타입 확장 (BPROJM)
ALTER TABLE ITPOWN.TPRMPP_BPROJM RENAME COLUMN BZ_TP_C TO ABUS_PPO_CONE;
ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY ABUS_PPO_CONE VARCHAR2(300 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJM RENAME COLUMN IT_PTL_TCHN_TP_TC TO SKL_FLD_NM;
ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY SKL_FLD_NM VARCHAR2(500 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJM RENAME COLUMN CST_TP_TC TO CST_TP_TC_NM;
ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY CST_TP_TC_NM VARCHAR2(1000 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJM MODIFY BZ_DTT_NM VARCHAR2(100 CHAR);

-- 2) 컬럼 rename + 타입 확장 (BPROJL 로그)
ALTER TABLE ITPOWN.TPRMPP_BPROJL RENAME COLUMN BZ_TP_C TO ABUS_PPO_CONE;
ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY ABUS_PPO_CONE VARCHAR2(300 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJL RENAME COLUMN IT_PTL_TCHN_TP_TC TO SKL_FLD_NM;
ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY SKL_FLD_NM VARCHAR2(500 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJL RENAME COLUMN CST_TP_TC TO CST_TP_TC_NM;
ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY CST_TP_TC_NM VARCHAR2(1000 CHAR);
ALTER TABLE ITPOWN.TPRMPP_BPROJL MODIFY BZ_DTT_NM VARCHAR2(100 CHAR);

-- 3) 기존 코드값 -> 코드값명 변환 (BPROJM). 미매칭(자유입력/널)은 NVL로 원본 보존.
UPDATE ITPOWN.TPRMPP_BPROJM m SET m.ABUS_PPO_CONE = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'PRJ_TP' AND CDVA_ID = m.ABUS_PPO_CONE ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), m.ABUS_PPO_CONE)
WHERE m.ABUS_PPO_CONE IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJM m SET m.SKL_FLD_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'IT_PTL_TCHN_TP_TC' AND CDVA_ID = m.SKL_FLD_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), m.SKL_FLD_NM)
WHERE m.SKL_FLD_NM IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJM m SET m.CST_TP_TC_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'CST_TP_TC' AND CDVA_ID = m.CST_TP_TC_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), m.CST_TP_TC_NM)
WHERE m.CST_TP_TC_NM IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJM m SET m.BZ_DTT_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'BZ_DTT' AND CDVA_ID = m.BZ_DTT_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), m.BZ_DTT_NM)
WHERE m.BZ_DTT_NM IS NOT NULL;

-- 4) 기존 코드값 -> 코드값명 변환 (BPROJL 로그)
UPDATE ITPOWN.TPRMPP_BPROJL l SET l.ABUS_PPO_CONE = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'PRJ_TP' AND CDVA_ID = l.ABUS_PPO_CONE ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), l.ABUS_PPO_CONE)
WHERE l.ABUS_PPO_CONE IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJL l SET l.SKL_FLD_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'IT_PTL_TCHN_TP_TC' AND CDVA_ID = l.SKL_FLD_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), l.SKL_FLD_NM)
WHERE l.SKL_FLD_NM IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJL l SET l.CST_TP_TC_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'CST_TP_TC' AND CDVA_ID = l.CST_TP_TC_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), l.CST_TP_TC_NM)
WHERE l.CST_TP_TC_NM IS NOT NULL;

UPDATE ITPOWN.TPRMPP_BPROJL l SET l.BZ_DTT_NM = NVL((
    SELECT CDVA_NM FROM (
        SELECT CDVA_NM FROM ITPOWN.TPRMPP_CCODEM
        WHERE CO_C_ID_NM = 'BZ_DTT' AND CDVA_ID = l.BZ_DTT_NM ORDER BY STT_DT DESC
    ) WHERE ROWNUM = 1), l.BZ_DTT_NM)
WHERE l.BZ_DTT_NM IS NOT NULL;

-- 5) 공통코드 그룹ID 통일 (데이터 변환 완료 후 rename)
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'ABUS_PPO' WHERE CO_C_ID_NM = 'PRJ_TP';
UPDATE ITPOWN.TPRMPP_CCODEM SET CO_C_ID_NM = 'SKL_FLD'  WHERE CO_C_ID_NM = 'IT_PTL_TCHN_TP_TC';

-- 6) 컬럼 코멘트 갱신
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.ABUS_PPO_CONE IS '사업목적내용';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.SKL_FLD_NM    IS '기술분야명';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.CST_TP_TC_NM  IS '고객유형구분코드명';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJM.BZ_DTT_NM     IS '업무구분명';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.ABUS_PPO_CONE IS '사업목적내용';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.SKL_FLD_NM    IS '기술분야명';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.CST_TP_TC_NM  IS '고객유형구분코드명';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJL.BZ_DTT_NM     IS '업무구분명';
