-- 공통 게시판 시드 데이터

-- 게시판 유형 공통코드
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('BLB_TP', 'BLB_TP_001', '공지사항', 1, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('BLB_TP', 'BLB_TP_002', '자료실',   2, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 중요도 공통코드
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C', 'PRIT_C_001', '일반', 1, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C', 'PRIT_C_002', '중요', 2, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C', 'PRIT_C_003', '긴급', 3, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 게시물 유형 공통코드
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP', 'NAC_TP_001', '작업예정', 1, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP', 'NAC_TP_002', '작업완료', 2, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (GRP_C, C, C_NM, SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP', 'NAC_TP_003', '교육자료', 3, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 게시판 메타 시드: 공지사항
INSERT INTO TAAABB_CBLBMM (
    BLB_MNG_NO, BLB_NM, BLB_TP,
    REP_USE_YN, CMMT_USE_YN, FL_ESN_YN, HRK_FXN_USE_YN, NAC_TP_USE_YN, KD_USE_YN,
    INQ_ATH_C, ENR_ATH_C, BBR_LMTN_USE_YN,
    SRE_SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID
) VALUES (
    'BLBM-2026-0001', '공지사항', 'BLB_TP_001',
    'N', 'N', 'N', 'Y', 'N', 'N',
    'ALL', 'ROLE_ADMIN', 'N',
    1, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM'
);

-- 게시판 메타 시드: 자료실
INSERT INTO TAAABB_CBLBMM (
    BLB_MNG_NO, BLB_NM, BLB_TP,
    REP_USE_YN, CMMT_USE_YN, FL_ESN_YN, HRK_FXN_USE_YN, NAC_TP_USE_YN, KD_USE_YN,
    INQ_ATH_C, ENR_ATH_C, BBR_LMTN_USE_YN,
    SRE_SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID
) VALUES (
    'BLBM-2026-0002', '자료실', 'BLB_TP_002',
    'N', 'Y', 'Y', 'N', 'N', 'Y',
    'ALL', 'ALL', 'N',
    2, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM'
);

COMMIT;
