-- V20260608_001__RemapItPtlStsTc.sql
-- 정보화포탈 프로젝트상태(IT_PTL_STS_TC) 코드체계 재정렬 (code.csv 기준)
--
-- 배경:
--  - 기존 코드는 앞자리(단계)와 실제 진행단계가 어긋나 있었고, 사전협의/요구사항 구체화
--    단계에 대응하는 코드가 없었다.
--  - code.csv 변경안으로 (1) 앞자리=진행단계가 일관되게 정렬되도록 일부 코드를 재매핑하고,
--    (2) 사전협의/요구사항 구체화 4종을 신규 추가하며, (3) 순번을 재정렬한다.
--
-- 코드 재매핑(구 → 신):
--   09(예산편성 요청 결재완료) → 02
--   11(예산편성 작업 진행중)   → 03
--   19(예산편성 작업 완료)     → 09
--   21(정실협 진행중)          → 11
--   29(정실협 완료)            → 19
-- 신규: 21 사전협의 진행중, 22 사전협의 완료, 23 요구사항 구체화 진행중, 24 요구사항 구체화 완료
--
-- 멱등성 주의: 본 마이그레이션은 코드ID 재사용(예: 구 19→09, 구 09→02)으로 인해
--   재실행 시 데이터가 이중 변환되어 손상될 수 있다. Flyway 단일 실행(스키마 히스토리 추적)을
--   전제로 하며, 전체를 단일 트랜잭션으로 묶어 부분 적용을 방지한다. 수동 재실행 금지.

-- ============================================================================
-- 1) 저장된 상태값 재매핑 — CCODEM 재적재 전, 구 코드값 기준으로 수행.
--    CASE 가 행별로 구값을 1회만 평가하므로 ID 재사용(19→09 등) 충돌이 없다.
--    대상값(09/11/19/21/29)이 없는 테이블은 0건 갱신(무해).
--    마스터 + 변경로그(*L) 모두 적용해 화면 표시·이력 의미를 일관 보존한다.
-- ============================================================================
UPDATE ITPAPP.TPRMPP_BPROJM SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BCONTM SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BDELIM SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BESTIM SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BPAYMM SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BPROJL SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BCONTL SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BDELIL SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BESTIL SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');
UPDATE ITPAPP.TPRMPP_BPAYML SET IT_PTL_STS_TC = CASE IT_PTL_STS_TC WHEN '09' THEN '02' WHEN '11' THEN '03' WHEN '19' THEN '09' WHEN '21' THEN '11' WHEN '29' THEN '19' ELSE IT_PTL_STS_TC END WHERE IT_PTL_STS_TC IN ('09','11','19','21','29');

-- ============================================================================
-- 2) 공통코드 그룹(IT_PTL_STS_TC) 재적재 — code.csv 변경안(27종)
-- ============================================================================
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'IT_PTL_STS_TC';

INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','01',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 작성중',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','02',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 요청 결재완료',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','03',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 진행중',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','09',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','예산편성 작업 완료',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','11',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 진행중',5,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','19',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','정보기술부문계획 정실협 완료',6,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','21',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','사전협의 진행중',7,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','22',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','사전협의 완료',8,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','23',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','요구사항 구체화 진행중',9,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','24',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','요구사항 구체화 완료',10,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','31',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 요청 작성중',11,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','32',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 진행중',12,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','39',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','타당성검토 정실협 완료',13,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','41',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 요청 작성중',14,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','42',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 진행중',15,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','49',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','소요예산 산정 완료',16,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','51',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 요청 작성중',17,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','52',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 진행중',18,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','59',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','과업심의위원회 완료',19,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','61',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 요청 작성중',20,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','62',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 진행중',21,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','69',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','입찰/계약 완료',22,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','71',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 요청 작성중',23,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','72',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 진행중',24,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','79',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','대금지급 완료',25,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','81',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 작성중',26,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPAPP.TPRMPP_CCODEM (CO_C_ID,CDVA_ID,STT_DTM,END_DTM,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('IT_PTL_STS_TC','89',DATE '2026-01-01',DATE '9999-12-31',NULL,'프로젝트상태','성과평가 완료',27,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

COMMIT;
