-- TPRMPP_CAPPLM 테이블에 신청서상태코드(APF_STS_C) 컬럼 추가 및 백필
-- 기존 APF_STS(VARCHAR2(32), 한글 문자열) → APF_STS_C(VARCHAR2(3), Ccodem APF_STS 코드값) 매핑

ALTER TABLE TPRMPP_CAPPLM ADD APF_STS_C VARCHAR2(3);
COMMENT ON COLUMN TPRMPP_CAPPLM.APF_STS_C IS '신청서상태코드 (Ccodem APF_STS)';

UPDATE TPRMPP_CAPPLM
SET APF_STS_C = DECODE(APF_STS, '결재중', '001', '결재완료', '002', '반려', '003', '001');

COMMIT;

ALTER TABLE TPRMPP_CAPPLM MODIFY APF_STS_C VARCHAR2(3) NOT NULL;
