-- V20260607_001__SeedItPtlBgPrnTc.sql
-- 대상구분 공통코드(IT_PTL_BG_PRN_TC): 소요예산/심의/계약/대금지급 단계의 대상(사업/전산업무비) 구분.
-- 멱등: 그룹 DELETE 후 재INSERT.

DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE CO_C_ID = 'IT_PTL_BG_PRN_TC';

INSERT INTO ITPAPP.TPRMPP_CCODEM
  (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES
  ('IT_PTL_BG_PRN_TC', '100', DATE '2026-01-01', DATE '9999-12-31', '대상구분', '정보화사업', 1, 'MIGRATION', SYSDATE, 'N');

INSERT INTO ITPAPP.TPRMPP_CCODEM
  (CO_C_ID, CDVA_ID, STT_DTM, END_DTM, CO_C_NM, CDVA_NM, C_SQN_SNO, FST_ENR_USID, FST_ENR_DTM, DEL_YN)
VALUES
  ('IT_PTL_BG_PRN_TC', '200', DATE '2026-01-01', DATE '9999-12-31', '대상구분', '전산업무비', 2, 'MIGRATION', SYSDATE, 'N');

COMMIT;
