-- ============================================================================
-- 알림 마스터 테이블 신규 생성
-- ============================================================================
-- 목적:
--   결재요청, 결재결과, 게시판 멘션 등 사내 알림을 1행=1수신자 구조로 적재한다.
--   AppHeader 종 아이콘의 미읽음 뱃지·드롭다운 UI와 결합한다.
--
-- 명명 규칙 (META.md / DOMAIN.md 준수):
--   테이블: TAAABB_{C공통}{INFM 알림}{M 마스터} = TAAABB_CINFMM
--   엔티티: Cinfmm (BaseEntity 상속)
--   채번 형식: INF-{YYYY}-{8자리 시퀀스} (결재 APF-... 패턴 미러)
--
-- 핵심 컬럼:
--   필수(사용자 요구): EAI_SD_TP_C(3), EAI_SD_DTM(DATE), EAI_SD_CONE(4000)
--   알림 본문: INF_TTL(100), INF_CONE(300), INF_LNK_URL(300)
--   수신/읽음: RCV_USID(14), RDD_YN(1), RDD_DTM(DATE)
--
-- 인덱스 설계:
--   IX_CINFMM_RCV : 사용자별 미읽음/최근 알림 조회 핵심 인덱스
--     (RCV_USID, DEL_YN, RDD_YN, FST_ENR_DTM DESC)
-- ============================================================================

-- ── 1. 테이블 생성 ──────────────────────────────────────────────────────────
CREATE TABLE ITPAPP.TAAABB_CINFMM (
    INF_MNG_NO     VARCHAR2(32)    NOT NULL,
    INF_TP_C       VARCHAR2(3)     NOT NULL,
    INF_TTL        VARCHAR2(100),
    INF_CONE       VARCHAR2(300),
    INF_LNK_URL    VARCHAR2(300),
    RCV_USID       VARCHAR2(14)    NOT NULL,
    RDD_YN         VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    RDD_DTM        DATE,
    EAI_SD_TP_C    VARCHAR2(3),
    EAI_SD_DTM     DATE,
    EAI_SD_CONE    VARCHAR2(4000),
    -- BaseEntity 공통 컬럼
    DEL_YN         VARCHAR2(1)     DEFAULT 'N' NOT NULL,
    GUID           VARCHAR2(38),
    GUID_PRG_SNO   NUMBER          DEFAULT 1,
    FST_ENR_DTM    TIMESTAMP(6),
    FST_ENR_USID   VARCHAR2(14),
    LST_CHG_DTM    TIMESTAMP(6),
    LST_CHG_USID   VARCHAR2(14),
    CONSTRAINT PK_CINFMM PRIMARY KEY (INF_MNG_NO) USING INDEX TABLESPACE USERS
)
TABLESPACE USERS;

-- ── 2. 테이블·컬럼 코멘트 (META.md 용어사전 기반 한글 코멘트) ───────────────
COMMENT ON TABLE  ITPAPP.TAAABB_CINFMM              IS '알림 마스터';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.INF_MNG_NO   IS '알림관리번호';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.INF_TP_C     IS '알림종류구분코드';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.INF_TTL      IS '알림제목';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.INF_CONE     IS '알림내용';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.INF_LNK_URL  IS '알림연결URL';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.RCV_USID     IS '수신자사번';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.RDD_YN       IS '읽음여부';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.RDD_DTM      IS '읽음일시';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.EAI_SD_TP_C  IS 'EAI발송구분코드';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.EAI_SD_DTM   IS 'EAI발송일시';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.EAI_SD_CONE  IS 'EAI발송내용';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.DEL_YN       IS '삭제여부';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.GUID         IS '전역고유식별자';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.GUID_PRG_SNO IS '진행일련번호';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.FST_ENR_DTM  IS '최초등록일시';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.FST_ENR_USID IS '최초등록자사번';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.LST_CHG_DTM  IS '최종변경일시';
COMMENT ON COLUMN ITPAPP.TAAABB_CINFMM.LST_CHG_USID IS '최종변경자사번';

-- ── 3. 사용자별 미읽음/최근 알림 조회용 핵심 인덱스 ─────────────────────────
--   드롭다운 목록 + 뱃지 카운트 쿼리가 대다수의 트래픽을 차지하므로
--   (RCV_USID, DEL_YN, RDD_YN, FST_ENR_DTM DESC) 다중 컬럼 인덱스를 둔다.
CREATE INDEX ITPAPP.IX_CINFMM_RCV
    ON ITPAPP.TAAABB_CINFMM (RCV_USID, DEL_YN, RDD_YN, FST_ENR_DTM DESC)
    TABLESPACE USERS;

-- ── 4. 시퀀스 — INF-{yyyy}-%08d (8자리 패딩, 연도 prefix → CYCLE) ───────────
--   결재 SEQ_CAPPLM 패턴과 동일한 범위·CYCLE 설정.
CREATE SEQUENCE ITPAPP.SEQ_CINFMM
    START WITH 1
    INCREMENT BY 1
    MAXVALUE 99999999
    CYCLE
    NOCACHE;

-- ── 5. 공통코드 시드 — 알림종류구분(CINF_TP) ────────────────────────────────
--   알림 생성 시 INF_TP_C에 들어갈 값. 클라이언트가 종류별 아이콘·라벨을 매핑한다.
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CINF_TP', 'APPROVAL_REQUEST', '결재요청', DATE '2026-01-01', '결재요청 알림', 10,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CINF_TP', 'APPROVAL_RESULT', '결재결과', DATE '2026-01-01', '결재결과 알림', 20,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CINF_TP', 'MENTION_POST', '게시물멘션', DATE '2026-01-01', '게시물 멘션 알림', 30,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CINF_TP', 'MENTION_COMMENT', '댓글멘션', DATE '2026-01-01', '댓글 멘션 알림', 40,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CINF_TP', 'SYSTEM', '시스템', DATE '2026-01-01', '시스템 알림', 90,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);

-- ── 6. 공통코드 시드 — EAI발송구분(CEAI_SD_TP) ──────────────────────────────
--   알림이 어떤 채널로 발송됐는지 추적. INAPP만 본 페이즈에서 즉시 적재되며
--   나머지는 외부 어댑터 도입 후 활성화한다(Phase 2 백로그).
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CEAI_SD_TP', 'INAPP', '인앱', DATE '2026-01-01', '사내 인앱 알림', 10,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CEAI_SD_TP', 'EMAIL', '이메일', DATE '2026-01-01', '이메일 발송', 20,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CEAI_SD_TP', 'SMS', '문자', DATE '2026-01-01', '문자 발송', 30,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);
INSERT INTO ITPAPP.TAAABB_CCODEM (
    C_ID, CDVA, CDVA_NM, STT_DT, C_NM, C_SQN,
    DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID
) VALUES (
    'CEAI_SD_TP', 'TALK', '알림톡', DATE '2026-01-01', '카카오 알림톡', 40,
    'N', RAWTOHEX(SYS_GUID()), 1, SYSTIMESTAMP, 'SYSTEM', SYSTIMESTAMP, 'SYSTEM'
);

COMMIT;
