-- 게시판 채번용 Oracle 시퀀스 생성

-- 게시판 메타 관리번호 시퀀스 (BLBM-{YYYY}-{0001})
CREATE SEQUENCE SQ_BLBMNGNO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 게시물 관리번호 시퀀스 (NAC-{YYYY}-{0001})
CREATE SEQUENCE SQ_NACMNGNO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 댓글 관리번호 시퀀스 (CMMT-{YYYY}-{0001})
CREATE SEQUENCE SQ_CMMTMNGNO START WITH 1 INCREMENT BY 1 NOCACHE;

-- 변경 로그 시퀀스 (AuditLogIdGenerator 규칙: S_{테이블명_TAAABB_제거})
CREATE SEQUENCE S_CBLBML  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE S_CBLBCL  START WITH 1 INCREMENT BY 1 NOCACHE;
CREATE SEQUENCE S_CCMMTL  START WITH 1 INCREMENT BY 1 NOCACHE;
