-- 과업심의위원회 마스터(BDELIM, 명세 없음) + 변경로그(BDELIL) + 시퀀스.
CREATE TABLE TPRMPP_BDELIM (
  DOC_MNG_NO        VARCHAR2(20 CHAR)  NOT NULL,
  DOC_VRS_SNO       NUMBER(9,0)        NOT NULL,
  LST_YN            VARCHAR2(1 CHAR)   DEFAULT 'Y' NOT NULL,
  BG_PRN_TC         VARCHAR2(3 CHAR)   NOT NULL,
  CNCD_RFR_NO       VARCHAR2(30 CHAR)  NOT NULL,
  IT_PTL_STS_TC     VARCHAR2(2 CHAR)   NOT NULL,
  REQ_CONE          VARCHAR2(300 CHAR),
  TASK_DBR_TC       VARCHAR2(2 CHAR),
  TASK_DBR_RLT_TC   VARCHAR2(2 CHAR),
  TASK_DBR_DT       VARCHAR2(8 CHAR),
  TASK_DBR_TOD      VARCHAR2(2 CHAR),
  TASK_DBR_OMT_YN   VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  TASK_DBR_OMT_RSN  VARCHAR2(200 CHAR),
  OPNN_CONE         VARCHAR2(1000 CHAR),
  APV_TRDN_RSN_CONE VARCHAR2(300 CHAR),
  DEL_YN            VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BDELIM PRIMARY KEY (DOC_MNG_NO, DOC_VRS_SNO),
  CONSTRAINT CK_BDELIM_LST_YN CHECK (LST_YN IN ('Y','N')),
  CONSTRAINT CK_BDELIM_DEL_YN CHECK (DEL_YN IN ('Y','N')),
  CONSTRAINT CK_BDELIM_OMT_YN CHECK (TASK_DBR_OMT_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BDELIM                   IS '과업심의 기본';
COMMENT ON COLUMN TPRMPP_BDELIM.DOC_MNG_NO        IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BDELIM.DOC_VRS_SNO       IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BDELIM.LST_YN            IS '최종여부';
COMMENT ON COLUMN TPRMPP_BDELIM.BG_PRN_TC         IS '예산성격구분코드(대상구분)';
COMMENT ON COLUMN TPRMPP_BDELIM.CNCD_RFR_NO       IS '관련참조번호(대상관리번호)';
COMMENT ON COLUMN TPRMPP_BDELIM.IT_PTL_STS_TC     IS 'IT포탈상태구분코드';
COMMENT ON COLUMN TPRMPP_BDELIM.REQ_CONE          IS '요청내용';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_TC       IS '과업심의구분코드';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_RLT_TC   IS '과업심의결과구분코드';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_DT       IS '과업심의일자';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_TOD      IS '과업심의회차';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_OMT_YN   IS '과업심의생략여부';
COMMENT ON COLUMN TPRMPP_BDELIM.TASK_DBR_OMT_RSN  IS '과업심의생략사유';
COMMENT ON COLUMN TPRMPP_BDELIM.OPNN_CONE         IS '의견내용';
COMMENT ON COLUMN TPRMPP_BDELIM.APV_TRDN_RSN_CONE IS '승인반려사유내용';
CREATE INDEX IDX_BDELIM_TGT ON TPRMPP_BDELIM (BG_PRN_TC, CNCD_RFR_NO);
CREATE INDEX IDX_BDELIM_STS ON TPRMPP_BDELIM (IT_PTL_STS_TC);

CREATE TABLE TPRMPP_BDELIL (
  LOG_HIS_TGR_SNO   NUMBER(18,0) NOT NULL,
  CHG_DTT_YN        VARCHAR2(1 CHAR),
  CHG_DTM           TIMESTAMP(9),
  CHG_USID          VARCHAR2(14 CHAR),
  DEL_YN            VARCHAR2(1 CHAR),
  GUID              VARCHAR2(38 CHAR),
  GUID_PRG_SNO      NUMBER(4,0),
  FST_ENR_DTM       DATE,
  FST_ENR_USID      VARCHAR2(14 CHAR),
  LST_CHG_DTM       DATE,
  LST_CHG_USID      VARCHAR2(14 CHAR),
  DOC_MNG_NO        VARCHAR2(20 CHAR),
  DOC_VRS_SNO       NUMBER(9,0),
  LST_YN            VARCHAR2(1 CHAR),
  BG_PRN_TC         VARCHAR2(3 CHAR),
  CNCD_RFR_NO       VARCHAR2(30 CHAR),
  IT_PTL_STS_TC     VARCHAR2(2 CHAR),
  REQ_CONE          VARCHAR2(300 CHAR),
  TASK_DBR_TC       VARCHAR2(2 CHAR),
  TASK_DBR_RLT_TC   VARCHAR2(2 CHAR),
  TASK_DBR_DT       VARCHAR2(8 CHAR),
  TASK_DBR_TOD      VARCHAR2(2 CHAR),
  TASK_DBR_OMT_YN   VARCHAR2(1 CHAR),
  TASK_DBR_OMT_RSN  VARCHAR2(200 CHAR),
  OPNN_CONE         VARCHAR2(1000 CHAR),
  APV_TRDN_RSN_CONE VARCHAR2(300 CHAR),
  CONSTRAINT PK_TPRMPP_BDELIL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE TPRMPP_BDELIL IS '과업심의 기본 변경 로그';

CREATE SEQUENCE SEQ_BDELIM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BDELIL START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
