-- 컬럼 표준화
--   PLN_DTL_CONE → PLN_DTL_INF : CLOB
--
-- 패턴: 기존 컬럼을 _BAK 으로 RENAME → 신규 CLOB 컬럼 ADD →
--      TO_CLOB() 으로 복사 → _BAK DROP → COMMENT.
--
-- 대상: TAAABB_BPLANM, TAAABB_BPLANL
-- 비고: 이전 V20260519_004 에서 CLOB → VARCHAR2(4000) 으로 축소되었을 수 있으나,
--      VARCHAR2 → CLOB 는 TO_CLOB() 으로 안전하게 복사 가능하다.

-- ============================================================
-- TAAABB_BPLANM
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BPLANM RENAME COLUMN PLN_DTL_CONE TO PLN_DTL_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANM ADD (PLN_DTL_INF CLOB);
UPDATE ITPAPP.TAAABB_BPLANM SET PLN_DTL_INF = TO_CLOB(PLN_DTL_CONE_BAK);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANM DROP COLUMN PLN_DTL_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANM.PLN_DTL_INF IS '계획상세정보';

-- ============================================================
-- TAAABB_BPLANL
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN PLN_DTL_CONE TO PLN_DTL_CONE_BAK;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD (PLN_DTL_INF CLOB);
UPDATE ITPAPP.TAAABB_BPLANL SET PLN_DTL_INF = TO_CLOB(PLN_DTL_CONE_BAK);
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN PLN_DTL_CONE_BAK;
COMMENT ON COLUMN ITPAPP.TAAABB_BPLANL.PLN_DTL_INF IS '계획상세정보';
