-- 컬럼 표준화
--   XCR    : NUMBER(9,4)
--   CUR    → CUR_C : VARCHAR2(3)
--   ITD_DT : VARCHAR2(8)

-- ============================================================
-- 1) XCR : NUMBER(9,4)
--    대상: TAAABB_BITEMM, TAAABB_BITEML, TAAABB_BCOSTM, TAAABB_BCOSTL,
--         TAAABB_BTERMM, TAAABB_BTERML
--
--    ORA-01440 회피: Oracle 은 데이터가 있는 NUMBER 컬럼의 정밀도/자리수 축소를
--    허용하지 않으므로 "신규 컬럼 추가 → 데이터 복사 → 원본 DROP → RENAME" 패턴 사용.
--    기존 환율값이 NUMBER(9,4) 범위(99999.9999)를 초과하면 복사 시 오류 발생.
-- ============================================================

-- 1-1) TAAABB_BITEMM
ALTER TABLE ITPAPP.TAAABB_BITEMM ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BITEMM SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEMM DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BITEMM RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.XCR IS '환율';

-- 1-2) TAAABB_BITEML
ALTER TABLE ITPAPP.TAAABB_BITEML ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BITEML SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEML DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BITEML RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.XCR IS '환율';

-- 1-3) TAAABB_BCOSTM
ALTER TABLE ITPAPP.TAAABB_BCOSTM ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BCOSTM SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTM DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BCOSTM RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.XCR IS '환율';

-- 1-4) TAAABB_BCOSTL
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BCOSTL SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.XCR IS '환율';

-- 1-5) TAAABB_BTERMM
ALTER TABLE ITPAPP.TAAABB_BTERMM ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BTERMM SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERMM DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BTERMM RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.XCR IS '환율';

-- 1-6) TAAABB_BTERML
ALTER TABLE ITPAPP.TAAABB_BTERML ADD (XCR_NEW NUMBER(9,4));
UPDATE ITPAPP.TAAABB_BTERML SET XCR_NEW = XCR;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN XCR;
ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN XCR_NEW TO XCR;
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.XCR IS '환율';

-- ============================================================
-- 2) CUR → CUR_C, VARCHAR2(3)
--    대상: TAAABB_BITEMM, TAAABB_BITEML, TAAABB_BCOSTM, TAAABB_BCOSTL,
--         TAAABB_BTERMM, TAAABB_BTERML
-- ============================================================
ALTER TABLE ITPAPP.TAAABB_BITEMM   RENAME COLUMN CUR TO CUR_C;
ALTER TABLE ITPAPP.TAAABB_BITEML   RENAME COLUMN CUR TO CUR_C;
ALTER TABLE ITPAPP.TAAABB_BCOSTM   RENAME COLUMN CUR TO CUR_C;
ALTER TABLE ITPAPP.TAAABB_BCOSTL   RENAME COLUMN CUR TO CUR_C;
ALTER TABLE ITPAPP.TAAABB_BTERMM   RENAME COLUMN CUR TO CUR_C;
ALTER TABLE ITPAPP.TAAABB_BTERML   RENAME COLUMN CUR TO CUR_C;

UPDATE ITPAPP.TAAABB_BITEMM   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
UPDATE ITPAPP.TAAABB_BITEML   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTM   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
UPDATE ITPAPP.TAAABB_BCOSTL   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
UPDATE ITPAPP.TAAABB_BTERMM   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
UPDATE ITPAPP.TAAABB_BTERML   SET CUR_C = SUBSTR(CUR_C, 1, 3) WHERE LENGTH(CUR_C) > 3;
COMMIT;

ALTER TABLE ITPAPP.TAAABB_BITEMM   MODIFY (CUR_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BITEML   MODIFY (CUR_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTM   MODIFY (CUR_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BCOSTL   MODIFY (CUR_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BTERMM   MODIFY (CUR_C VARCHAR2(3));
ALTER TABLE ITPAPP.TAAABB_BTERML   MODIFY (CUR_C VARCHAR2(3));

COMMENT ON COLUMN ITPAPP.TAAABB_BITEMM.CUR_C IS '통화코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BITEML.CUR_C IS '통화코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTM.CUR_C IS '통화코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BCOSTL.CUR_C IS '통화코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BTERMM.CUR_C IS '통화코드';
COMMENT ON COLUMN ITPAPP.TAAABB_BTERML.CUR_C IS '통화코드';

-- ============================================================
-- 3) ITD_DT : VARCHAR2(8)
--    대상: TAAABB_BITEMM, TAAABB_BITEML
--    기존 데이터(YYYY-MM 등) 8자 초과분 절단
-- ============================================================
UPDATE ITPAPP.TAAABB_BITEMM   SET ITD_DT = SUBSTR(ITD_DT, 1, 8) WHERE LENGTH(ITD_DT) > 8;
UPDATE ITPAPP.TAAABB_BITEML   SET ITD_DT = SUBSTR(ITD_DT, 1, 8) WHERE LENGTH(ITD_DT) > 8;
COMMIT;

ALTER TABLE ITPAPP.TAAABB_BITEMM   MODIFY (ITD_DT VARCHAR2(8));
ALTER TABLE ITPAPP.TAAABB_BITEML   MODIFY (ITD_DT VARCHAR2(8));
