-- 공통 게시판 메타·본문·댓글·변경로그 테이블 생성

-- 1) 게시판 메타 (TAAABB_CBLBMM)
CREATE TABLE TAAABB_CBLBMM (
    BLB_MNG_NO        VARCHAR2(32)  NOT NULL,
    BLB_NM            VARCHAR2(100) NOT NULL,
    BLB_TP            VARCHAR2(32)  NOT NULL,
    REP_USE_YN        VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    CMMT_USE_YN       VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    FL_ESN_YN         VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    HRK_FXN_USE_YN    VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    NAC_TP_USE_YN     VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    KD_USE_YN         VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    INQ_ATH_C         VARCHAR2(32)  DEFAULT 'ALL' NOT NULL,
    ENR_ATH_C         VARCHAR2(32)  DEFAULT 'ALL' NOT NULL,
    BBR_LMTN_USE_YN   VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    BBR_LMTN_C        VARCHAR2(8),
    SRE_SQN_NO        NUMBER(3)     DEFAULT 0 NOT NULL,
    USE_YN            VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    RMK               VARCHAR2(500),
    DEL_YN            VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    GUID              VARCHAR2(38),
    GUID_PRG_SNO      NUMBER(10)    DEFAULT 1,
    FST_ENR_DTM       TIMESTAMP,
    FST_ENR_USID      VARCHAR2(14),
    LST_CHG_DTM       TIMESTAMP,
    LST_CHG_USID      VARCHAR2(14),
    CONSTRAINT PK_CBLBMM PRIMARY KEY (BLB_MNG_NO)
);
COMMENT ON TABLE  TAAABB_CBLBMM              IS '게시판 메타';
COMMENT ON COLUMN TAAABB_CBLBMM.BLB_MNG_NO  IS '게시판관리번호';
COMMENT ON COLUMN TAAABB_CBLBMM.BLB_NM      IS '게시판명';
COMMENT ON COLUMN TAAABB_CBLBMM.BLB_TP      IS '게시판유형';
COMMENT ON COLUMN TAAABB_CBLBMM.REP_USE_YN  IS '답변사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.CMMT_USE_YN IS '댓글사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.FL_ESN_YN   IS '첨부필수여부';
COMMENT ON COLUMN TAAABB_CBLBMM.HRK_FXN_USE_YN IS '상위고정사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.NAC_TP_USE_YN  IS '게시물유형사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.KD_USE_YN      IS '종류사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.INQ_ATH_C      IS '조회권한코드';
COMMENT ON COLUMN TAAABB_CBLBMM.ENR_ATH_C      IS '등록권한코드';
COMMENT ON COLUMN TAAABB_CBLBMM.BBR_LMTN_USE_YN IS '담당부서한정사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.BBR_LMTN_C     IS '담당부서한정코드';
COMMENT ON COLUMN TAAABB_CBLBMM.SRE_SQN_NO     IS '화면순서번호';
COMMENT ON COLUMN TAAABB_CBLBMM.USE_YN         IS '사용여부';
COMMENT ON COLUMN TAAABB_CBLBMM.RMK            IS '비고';
COMMENT ON COLUMN TAAABB_CBLBMM.DEL_YN         IS '삭제여부';

-- 2) 게시물 본문 (TAAABB_CBLBCM)
CREATE TABLE TAAABB_CBLBCM (
    NAC_MNG_NO        VARCHAR2(32)  NOT NULL,
    BLB_MNG_NO        VARCHAR2(32)  NOT NULL,
    NAC_NM            VARCHAR2(300) NOT NULL,
    NAC_CONE          CLOB,
    NAC_INQ_NBR       NUMBER(10)    DEFAULT 0 NOT NULL,
    NAC_TP            VARCHAR2(32),
    KD_C              VARCHAR2(32),
    PRIT_C            VARCHAR2(32)  DEFAULT 'PRIT_C_001' NOT NULL,
    HRK_FXN_YN        VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    SRE_YN            VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    BBR_C             VARCHAR2(8),
    STT_YMD           DATE,
    END_YMD           DATE,
    FL_APG_YN         VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    FL_NBR            NUMBER(4)     DEFAULT 0 NOT NULL,
    NAC_GRP_NO        VARCHAR2(32)  NOT NULL,
    NAC_GRP_SQN       NUMBER(5)     DEFAULT 0 NOT NULL,
    NAC_GRP_LEV       NUMBER(2)     DEFAULT 0 NOT NULL,
    HRK_NAC_MNG_NO    VARCHAR2(32),
    DEL_YN            VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    GUID              VARCHAR2(38),
    GUID_PRG_SNO      NUMBER(10)    DEFAULT 1,
    FST_ENR_DTM       TIMESTAMP,
    FST_ENR_USID      VARCHAR2(14),
    LST_CHG_DTM       TIMESTAMP,
    LST_CHG_USID      VARCHAR2(14),
    CONSTRAINT PK_CBLBCM PRIMARY KEY (NAC_MNG_NO),
    CONSTRAINT FK_CBLBCM_BLB FOREIGN KEY (BLB_MNG_NO) REFERENCES TAAABB_CBLBMM(BLB_MNG_NO)
);
COMMENT ON TABLE  TAAABB_CBLBCM             IS '게시물';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_MNG_NO  IS '게시물관리번호';
COMMENT ON COLUMN TAAABB_CBLBCM.BLB_MNG_NO  IS '게시판관리번호';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_NM      IS '게시물명';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_CONE    IS '게시물내용';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_INQ_NBR IS '게시물조회수';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_TP      IS '게시물유형';
COMMENT ON COLUMN TAAABB_CBLBCM.KD_C        IS '종류코드';
COMMENT ON COLUMN TAAABB_CBLBCM.PRIT_C      IS '중요도코드';
COMMENT ON COLUMN TAAABB_CBLBCM.HRK_FXN_YN  IS '상위고정여부';
COMMENT ON COLUMN TAAABB_CBLBCM.SRE_YN      IS '화면여부';
COMMENT ON COLUMN TAAABB_CBLBCM.BBR_C       IS '담당부서코드';
COMMENT ON COLUMN TAAABB_CBLBCM.STT_YMD     IS '시작일자';
COMMENT ON COLUMN TAAABB_CBLBCM.END_YMD     IS '종료일자';
COMMENT ON COLUMN TAAABB_CBLBCM.FL_APG_YN   IS '파일첨부여부';
COMMENT ON COLUMN TAAABB_CBLBCM.FL_NBR      IS '파일수';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_GRP_NO  IS '게시물그룹번호';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_GRP_SQN IS '게시물그룹순서';
COMMENT ON COLUMN TAAABB_CBLBCM.NAC_GRP_LEV IS '게시물그룹레벨';
COMMENT ON COLUMN TAAABB_CBLBCM.HRK_NAC_MNG_NO IS '상위게시물관리번호';
COMMENT ON COLUMN TAAABB_CBLBCM.DEL_YN      IS '삭제여부';

-- 3) 댓글 (TAAABB_CCMMTM)
CREATE TABLE TAAABB_CCMMTM (
    CMMT_MNG_NO       VARCHAR2(32)  NOT NULL,
    NAC_MNG_NO        VARCHAR2(32)  NOT NULL,
    CMMT_CONE         CLOB          NOT NULL,
    SRE_YN            VARCHAR2(1)   DEFAULT 'Y' NOT NULL,
    CMMT_GRP_NO       VARCHAR2(32)  NOT NULL,
    CMMT_GRP_SQN      NUMBER(5)     DEFAULT 0 NOT NULL,
    CMMT_GRP_LEV      NUMBER(2)     DEFAULT 0 NOT NULL,
    HRK_CMMT_MNG_NO   VARCHAR2(32),
    DEL_YN            VARCHAR2(1)   DEFAULT 'N' NOT NULL,
    GUID              VARCHAR2(38),
    GUID_PRG_SNO      NUMBER(10)    DEFAULT 1,
    FST_ENR_DTM       TIMESTAMP,
    FST_ENR_USID      VARCHAR2(14),
    LST_CHG_DTM       TIMESTAMP,
    LST_CHG_USID      VARCHAR2(14),
    CONSTRAINT PK_CCMMTM PRIMARY KEY (CMMT_MNG_NO),
    CONSTRAINT FK_CCMMTM_NAC FOREIGN KEY (NAC_MNG_NO) REFERENCES TAAABB_CBLBCM(NAC_MNG_NO)
);
COMMENT ON TABLE  TAAABB_CCMMTM              IS '게시판댓글';
COMMENT ON COLUMN TAAABB_CCMMTM.CMMT_MNG_NO  IS '댓글관리번호';
COMMENT ON COLUMN TAAABB_CCMMTM.NAC_MNG_NO   IS '게시물관리번호';
COMMENT ON COLUMN TAAABB_CCMMTM.CMMT_CONE    IS '댓글내용';
COMMENT ON COLUMN TAAABB_CCMMTM.SRE_YN       IS '화면여부';
COMMENT ON COLUMN TAAABB_CCMMTM.CMMT_GRP_NO  IS '댓글그룹번호';
COMMENT ON COLUMN TAAABB_CCMMTM.CMMT_GRP_SQN IS '댓글그룹순서';
COMMENT ON COLUMN TAAABB_CCMMTM.CMMT_GRP_LEV IS '댓글그룹레벨';
COMMENT ON COLUMN TAAABB_CCMMTM.HRK_CMMT_MNG_NO IS '상위댓글관리번호';
COMMENT ON COLUMN TAAABB_CCMMTM.DEL_YN       IS '삭제여부';

-- 4) 게시판 메타 변경 로그 (TAAABB_CBLBML)
CREATE TABLE TAAABB_CBLBML (
    LOG_SNO          VARCHAR2(32)  NOT NULL,
    CHG_TP           VARCHAR2(1),
    CHG_DTM          TIMESTAMP,
    CHG_USID         VARCHAR2(14),
    DEL_YN           VARCHAR2(1),
    GUID             VARCHAR2(38),
    GUID_PRG_SNO     NUMBER(10),
    FST_ENR_DTM      TIMESTAMP,
    FST_ENR_USID     VARCHAR2(14),
    LST_CHG_DTM      TIMESTAMP,
    LST_CHG_USID     VARCHAR2(14),
    BLB_MNG_NO       VARCHAR2(32),
    BLB_NM           VARCHAR2(100),
    BLB_TP           VARCHAR2(32),
    REP_USE_YN       VARCHAR2(1),
    CMMT_USE_YN      VARCHAR2(1),
    FL_ESN_YN        VARCHAR2(1),
    HRK_FXN_USE_YN   VARCHAR2(1),
    NAC_TP_USE_YN    VARCHAR2(1),
    KD_USE_YN        VARCHAR2(1),
    INQ_ATH_C        VARCHAR2(32),
    ENR_ATH_C        VARCHAR2(32),
    BBR_LMTN_USE_YN  VARCHAR2(1),
    BBR_LMTN_C       VARCHAR2(8),
    SRE_SQN_NO       NUMBER(3),
    USE_YN           VARCHAR2(1),
    RMK              VARCHAR2(500),
    CONSTRAINT PK_CBLBML PRIMARY KEY (LOG_SNO)
);
COMMENT ON TABLE TAAABB_CBLBML IS '게시판메타변경로그';

-- 5) 게시물 변경 로그 (TAAABB_CBLBCL)
CREATE TABLE TAAABB_CBLBCL (
    LOG_SNO          VARCHAR2(32)  NOT NULL,
    CHG_TP           VARCHAR2(1),
    CHG_DTM          TIMESTAMP,
    CHG_USID         VARCHAR2(14),
    DEL_YN           VARCHAR2(1),
    GUID             VARCHAR2(38),
    GUID_PRG_SNO     NUMBER(10),
    FST_ENR_DTM      TIMESTAMP,
    FST_ENR_USID     VARCHAR2(14),
    LST_CHG_DTM      TIMESTAMP,
    LST_CHG_USID     VARCHAR2(14),
    NAC_MNG_NO       VARCHAR2(32),
    BLB_MNG_NO       VARCHAR2(32),
    NAC_NM           VARCHAR2(300),
    NAC_CONE         CLOB,
    NAC_INQ_NBR      NUMBER(10),
    NAC_TP           VARCHAR2(32),
    KD_C             VARCHAR2(32),
    PRIT_C           VARCHAR2(32),
    HRK_FXN_YN       VARCHAR2(1),
    SRE_YN           VARCHAR2(1),
    BBR_C            VARCHAR2(8),
    STT_YMD          DATE,
    END_YMD          DATE,
    FL_APG_YN        VARCHAR2(1),
    FL_NBR           NUMBER(4),
    NAC_GRP_NO       VARCHAR2(32),
    NAC_GRP_SQN      NUMBER(5),
    NAC_GRP_LEV      NUMBER(2),
    HRK_NAC_MNG_NO   VARCHAR2(32),
    CONSTRAINT PK_CBLBCL PRIMARY KEY (LOG_SNO)
);
COMMENT ON TABLE TAAABB_CBLBCL IS '게시물변경로그';

-- 6) 댓글 변경 로그 (TAAABB_CCMMTL)
CREATE TABLE TAAABB_CCMMTL (
    LOG_SNO          VARCHAR2(32)  NOT NULL,
    CHG_TP           VARCHAR2(1),
    CHG_DTM          TIMESTAMP,
    CHG_USID         VARCHAR2(14),
    DEL_YN           VARCHAR2(1),
    GUID             VARCHAR2(38),
    GUID_PRG_SNO     NUMBER(10),
    FST_ENR_DTM      TIMESTAMP,
    FST_ENR_USID     VARCHAR2(14),
    LST_CHG_DTM      TIMESTAMP,
    LST_CHG_USID     VARCHAR2(14),
    CMMT_MNG_NO      VARCHAR2(32),
    NAC_MNG_NO       VARCHAR2(32),
    CMMT_CONE        CLOB,
    SRE_YN           VARCHAR2(1),
    CMMT_GRP_NO      VARCHAR2(32),
    CMMT_GRP_SQN     NUMBER(5),
    CMMT_GRP_LEV     NUMBER(2),
    HRK_CMMT_MNG_NO  VARCHAR2(32),
    CONSTRAINT PK_CCMMTL PRIMARY KEY (LOG_SNO)
);
COMMENT ON TABLE TAAABB_CCMMTL IS '게시판댓글변경로그';
