-- V20260622_003__AddPhase4PerformanceIndexes.sql
-- Phase 4 (T14) 성능 인덱스 묶음.
-- 대상: 결재(CDECIM/CAPPLM), 요구사항(BRDOCM/BRIVGM), 협의회(BASCTM/BCMMTM),
--       사업집행 4단계 마스터(BESTIM/BDELIM/BCONTM/BPAYMM), 메뉴(CMENUM/CMENUA).
-- 스키마 접두어 미사용(세션 CURRENT_SCHEMA=ITPOWN). 컬럼명은 엔티티 @Column / 베이스 DDL 검증 완료.
-- 주의(SKIP): 실시간로그 피드는 V_ITPAPP_LOG_FEED(뷰)라 직접 인덱스 불가 -> 본 묶음 제외(후속 조사).
-- 주의(SKIP): BESTIM은 V20260607_002에서 IDX_BESTIM_TGT(BG_PRN_TC,CNCD_RFR_NO)/IDX_BESTIM_STS(IT_PTL_STS_TC) 이미 생성됨 -> 중복 제외.
-- 주의(SKIP): BPAYTM JOIN 인덱스(DOC_MNG_NO,DOC_VRS_SNO)는 PK_TPRMPP_BPAYTM(DOC_MNG_NO,DOC_VRS_SNO,DFR_TOD)의
--             선행 컬럼 프리픽스로 이미 커버되어 중복 -> 제외.

-- ── 결재 ──────────────────────────────────────────────
-- 결재선 조회(findByDcdMngNoOrderByDcrSqnSnoAsc / In) 가속
CREATE INDEX IDX_CDECIM_APF_SQN ON TPRMPP_CDECIM (APF_DCM_NO, DCR_SQN_SNO);
-- 대시보드 사용자별 진행상태 카운트(countPending/InProgress/RejectedByEno) 가속
CREATE INDEX IDX_CAPPLM_REQ_STS ON TPRMPP_CAPPLM (DCD_REQ_USID, APF_PRG_STS_C);

-- ── 요구사항 ──────────────────────────────────────────
-- 최신버전/버전조회 및 Soft Delete 필터
CREATE INDEX IDX_BRDOCM_DOC_VRS ON TPRMPP_BRDOCM (DOC_MNG_NO, DOC_VRS_SNO, DEL_YN);
-- 검토의견 목록(findByDocMngNoAndDocVrsSnoAndDelYn...)
CREATE INDEX IDX_BRIVGM_DOC_VRS ON TPRMPP_BRIVGM (DOC_MNG_NO, DOC_VRS_SNO, DEL_YN);

-- ── 협의회 ────────────────────────────────────────────
-- 부서 JOIN(ABUS_MNG_NO/SNO) + Soft Delete (PK는 IT_PTL_ASCT_ID 단일이라 본 인덱스 유효)
CREATE INDEX IDX_BASCTM_ABUS_DEL ON TPRMPP_BASCTM (ABUS_MNG_NO, SNO, DEL_YN);
-- 위원 목록(findByItPtlAsctIdAndDelYn) + 위원 본인 배정 조회(ENO)
CREATE INDEX IDX_BCMMTM_ASCT_DEL ON TPRMPP_BCMMTM (IT_PTL_ASCT_ID, DEL_YN);
CREATE INDEX IDX_BCMMTM_ENO_DEL  ON TPRMPP_BCMMTM (ENO, DEL_YN);

-- ── 사업집행 4단계 마스터: 목록 필터(상태/대상/최신/삭제) + 정렬(FST_ENR_DTM) ──
-- BESTIM: 기존 TGT/STS 외 복합·정렬 보강
CREATE INDEX IDX_BESTIM_LIST    ON TPRMPP_BESTIM (DEL_YN, LST_YN, IT_PTL_STS_TC, CNCD_RFR_NO);
CREATE INDEX IDX_BESTIM_FST_DTM ON TPRMPP_BESTIM (FST_ENR_DTM);
CREATE INDEX IDX_BDELIM_LIST    ON TPRMPP_BDELIM (DEL_YN, LST_YN, BG_PRN_TC, IT_PTL_STS_TC);
CREATE INDEX IDX_BDELIM_FST_DTM ON TPRMPP_BDELIM (FST_ENR_DTM);
CREATE INDEX IDX_BCONTM_LIST    ON TPRMPP_BCONTM (DEL_YN, LST_YN, BG_PRN_TC, IT_PTL_STS_TC);
CREATE INDEX IDX_BCONTM_FST_DTM ON TPRMPP_BCONTM (FST_ENR_DTM);
CREATE INDEX IDX_BPAYMM_LIST    ON TPRMPP_BPAYMM (DEL_YN, LST_YN, BG_PRN_TC, IT_PTL_STS_TC);
CREATE INDEX IDX_BPAYMM_FST_DTM ON TPRMPP_BPAYMM (FST_ENR_DTM);

-- ── 메뉴: 활성 필터(DEL_YN='N') ──
-- CMENUM PK=MNU_ID, CMENUA PK=(MNU_ID,ATH_ID) 모두 DEL_YN 선행 아님 -> 본 인덱스 유효
CREATE INDEX IDX_CMENUM_DEL ON TPRMPP_CMENUM (DEL_YN);
CREATE INDEX IDX_CMENUA_DEL ON TPRMPP_CMENUA (DEL_YN);
