-- ============================================================================
-- 인덱스/PK 명명 표준화 및 정비
-- ============================================================================
-- 목적:
--   1) SYS_C 계열 PK 인덱스를 표준 PK명으로 재생성합니다.
--   2) 기존 일반 인덱스를 표준 IDX명으로 재생성합니다.
--   3) 조회 패턴상 필요한 누락 인덱스를 함께 보강합니다.
--
-- 명명 규칙:
--   - PK 제약/인덱스: PK_{테이블명}_{컬럼명...}
--   - 일반 인덱스:   IDX_{테이블명}_{컬럼명...}
--
-- 주의:
--   - PK를 받치는 unique index는 DROP INDEX로 제거할 수 없으므로 PK 제약조건을 먼저 제거합니다.
--   - 부모 PK를 재생성하기 위해 관련 FK를 잠시 제거한 뒤 동일 정의로 복구합니다.
--   - 운영 반영 전 백업 후 점검 시간에 실행하세요.
-- ============================================================================

-- ============================================================================
-- 1. PK 재생성을 위해 FK를 먼저 제거합니다.
-- ============================================================================
ALTER TABLE TAAABB_BTERMM DROP CONSTRAINT FKK58AD6SHPR5X8SFABNUMIPUMY;
ALTER TABLE TAAABB_CAPPLA DROP CONSTRAINT FK_TAAABB_CAPPLA_APF;
ALTER TABLE TAAABB_CBLBCM DROP CONSTRAINT FK_CBLBCM_BLB;
ALTER TABLE TAAABB_CCMMTM DROP CONSTRAINT FK_CCMMTM_NAC;
ALTER TABLE TAAABB_CORGNI DROP CONSTRAINT FKCQGW9S3E23OS57TBIWJSXM4HN;
ALTER TABLE TAAABB_CUSERI DROP CONSTRAINT FK6682LS44OK4T0XVK646CEYG8H;

-- ============================================================================
-- 2. 기존 PK 제약조건을 제거합니다. PK용 unique index도 함께 제거됩니다.
-- ============================================================================
ALTER TABLE TAAABB_BASCTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BASCTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BBUGTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BBUGTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCHKLC DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCHKLL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCMMTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCMMTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCOSTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BCOSTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BEVALL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BEVALM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BGDOCL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BGDOCM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BITEML DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BITEMM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPERFL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPERFM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPLANL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPLANM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPOVWL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPOVWM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPQNAL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPQNAM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPROJA DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BPROJL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRDOCL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRDOCM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRIVGL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRIVGM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRSLTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BRSLTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BSCHDL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BSCHDM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BTERML DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_BTERMM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CAPPLA DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CAPPLL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CAPPLM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CAUTHI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CBLBCL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CBLBCM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CBLBML DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CBLBMM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CCMMTL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CCMMTM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CCODEL DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CCODEM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CDECIM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CFILEM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CLOGNH DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CORGNI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CROLEI DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CRTOKM DROP PRIMARY KEY DROP INDEX;
ALTER TABLE TAAABB_CUSERI DROP PRIMARY KEY DROP INDEX;

-- ============================================================================
-- 3. 기존 일반 인덱스를 제거합니다.
-- ============================================================================
DROP INDEX IDX_BITEMM_PRJ_MNG_NO;
DROP INDEX IDX_CAPPLA_ORC_COMP;
DROP INDEX IDX_CBLBCM_AUTHOR;
DROP INDEX IDX_CBLBCM_BBR;
DROP INDEX IDX_CBLBCM_GRP;
DROP INDEX IDX_CBLBCM_HRK;
DROP INDEX IDX_CBLBCM_LIST;
DROP INDEX IDX_CBLBMM_NAV;
DROP INDEX IDX_CCMMTM_GRP;
DROP INDEX IDX_CCMMTM_HRK;
DROP INDEX IDX_CCMMTM_LIST;
DROP INDEX IX_TAAABB_CFILEM_ORC;

-- ============================================================================
-- 4. 표준명 PK를 생성합니다.
-- ============================================================================
ALTER TABLE TAAABB_BASCTL ADD CONSTRAINT PK_TAAABB_BASCTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BASCTM ADD CONSTRAINT PK_TAAABB_BASCTM_ASCT_ID PRIMARY KEY (ASCT_ID) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BBUGTL ADD CONSTRAINT PK_TAAABB_BBUGTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BBUGTM ADD CONSTRAINT PK_TAAABB_BBUGTM_BG_MNG_NO_BG_SNO PRIMARY KEY (BG_MNG_NO, BG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCHKLC ADD CONSTRAINT PK_TAAABB_BCHKLC_ASCT_ID_CKG_ITM_C PRIMARY KEY (ASCT_ID, CKG_ITM_C) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCHKLL ADD CONSTRAINT PK_TAAABB_BCHKLL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCMMTL ADD CONSTRAINT PK_TAAABB_BCMMTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCMMTM ADD CONSTRAINT PK_TAAABB_BCMMTM_ASCT_ID_ENO PRIMARY KEY (ASCT_ID, ENO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCOSTL ADD CONSTRAINT PK_TAAABB_BCOSTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BCOSTM ADD CONSTRAINT PK_TAAABB_BCOSTM_IT_MNGC_NO_IT_MNGC_SNO PRIMARY KEY (IT_MNGC_NO, IT_MNGC_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BEVALL ADD CONSTRAINT PK_TAAABB_BEVALL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BEVALM ADD CONSTRAINT PK_TAAABB_BEVALM_ASCT_ID_CKG_ITM_C_ENO PRIMARY KEY (ASCT_ID, CKG_ITM_C, ENO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BGDOCL ADD CONSTRAINT PK_TAAABB_BGDOCL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BGDOCM ADD CONSTRAINT PK_TAAABB_BGDOCM_DOC_MNG_NO PRIMARY KEY (DOC_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BITEML ADD CONSTRAINT PK_TAAABB_BITEML_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BITEMM ADD CONSTRAINT PK_TAAABB_BITEMM_GCL_MNG_NO_GCL_SNO PRIMARY KEY (GCL_MNG_NO, GCL_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPERFL ADD CONSTRAINT PK_TAAABB_BPERFL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPERFM ADD CONSTRAINT PK_TAAABB_BPERFM_ASCT_ID_DTP_SNO PRIMARY KEY (ASCT_ID, DTP_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPLANL ADD CONSTRAINT PK_TAAABB_BPLANL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPLANM ADD CONSTRAINT PK_TAAABB_BPLANM_PLN_MNG_NO PRIMARY KEY (PLN_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPOVWL ADD CONSTRAINT PK_TAAABB_BPOVWL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPOVWM ADD CONSTRAINT PK_TAAABB_BPOVWM_ASCT_ID PRIMARY KEY (ASCT_ID) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPQNAL ADD CONSTRAINT PK_TAAABB_BPQNAL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPQNAM ADD CONSTRAINT PK_TAAABB_BPQNAM_QTN_ID PRIMARY KEY (QTN_ID) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPROJA ADD CONSTRAINT PK_TAAABB_BPROJA_PRJ_MNG_NO_BZ_MNG_NO PRIMARY KEY (PRJ_MNG_NO, BZ_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPROJL ADD CONSTRAINT PK_TAAABB_BPROJL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BPROJM ADD CONSTRAINT PK_TAAABB_BPROJM_PRJ_MNG_NO_PRJ_SNO PRIMARY KEY (PRJ_MNG_NO, PRJ_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRDOCL ADD CONSTRAINT PK_TAAABB_BRDOCL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRDOCM ADD CONSTRAINT PK_TAAABB_BRDOCM_DOC_MNG_NO_DOC_VRS PRIMARY KEY (DOC_MNG_NO, DOC_VRS) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRIVGL ADD CONSTRAINT PK_TAAABB_BRIVGL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRIVGM ADD CONSTRAINT PK_TAAABB_BRIVGM_IVG_SNO PRIMARY KEY (IVG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRSLTL ADD CONSTRAINT PK_TAAABB_BRSLTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BRSLTM ADD CONSTRAINT PK_TAAABB_BRSLTM_ASCT_ID PRIMARY KEY (ASCT_ID) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BSCHDL ADD CONSTRAINT PK_TAAABB_BSCHDL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BSCHDM ADD CONSTRAINT PK_TAAABB_BSCHDM_ASCT_ID_DSD_DT_DSD_TM_ENO PRIMARY KEY (ASCT_ID, DSD_DT, DSD_TM, ENO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BTERML ADD CONSTRAINT PK_TAAABB_BTERML_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_BTERMM ADD CONSTRAINT PK_TAAABB_BTERMM_TMN_MNG_NO_TMN_SNO PRIMARY KEY (TMN_MNG_NO, TMN_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CAPPLA ADD CONSTRAINT PK_TAAABB_CAPPLA_APF_REL_SNO PRIMARY KEY (APF_REL_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CAPPLL ADD CONSTRAINT PK_TAAABB_CAPPLL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CAPPLM ADD CONSTRAINT PK_TAAABB_CAPPLM_APF_MNG_NO PRIMARY KEY (APF_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CAUTHI ADD CONSTRAINT PK_TAAABB_CAUTHI_ATH_ID PRIMARY KEY (ATH_ID) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CBLBCL ADD CONSTRAINT PK_TAAABB_CBLBCL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CBLBCM ADD CONSTRAINT PK_TAAABB_CBLBCM_NAC_MNG_NO PRIMARY KEY (NAC_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CBLBML ADD CONSTRAINT PK_TAAABB_CBLBML_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CBLBMM ADD CONSTRAINT PK_TAAABB_CBLBMM_BLB_MNG_NO PRIMARY KEY (BLB_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CCMMTL ADD CONSTRAINT PK_TAAABB_CCMMTL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CCMMTM ADD CONSTRAINT PK_TAAABB_CCMMTM_CMMT_MNG_NO PRIMARY KEY (CMMT_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CCODEL ADD CONSTRAINT PK_TAAABB_CCODEL_LOG_SNO PRIMARY KEY (LOG_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CCODEM ADD CONSTRAINT PK_TAAABB_CCODEM_C_ID_CDVA_STT_DT PRIMARY KEY (C_ID, CDVA, STT_DT) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CDECIM ADD CONSTRAINT PK_TAAABB_CDECIM_DCD_MNG_NO_DCD_SQN PRIMARY KEY (DCD_MNG_NO, DCD_SQN) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CFILEM ADD CONSTRAINT PK_TAAABB_CFILEM_FL_MNG_NO PRIMARY KEY (FL_MNG_NO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CLOGNH ADD CONSTRAINT PK_TAAABB_CLOGNH_LGN_SNO PRIMARY KEY (LGN_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CORGNI ADD CONSTRAINT PK_TAAABB_CORGNI_PRLM_OGZ_C_CONE PRIMARY KEY (PRLM_OGZ_C_CONE) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CROLEI ADD CONSTRAINT PK_TAAABB_CROLEI_ATH_ID_ENO PRIMARY KEY (ATH_ID, ENO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CRTOKM ADD CONSTRAINT PK_TAAABB_CRTOKM_TOK_SNO PRIMARY KEY (TOK_SNO) USING INDEX TABLESPACE USERS;
ALTER TABLE TAAABB_CUSERI ADD CONSTRAINT PK_TAAABB_CUSERI_ENO PRIMARY KEY (ENO) USING INDEX TABLESPACE USERS;

-- ============================================================================
-- 5. 제거했던 FK를 표준명으로 복구합니다.
-- ============================================================================
ALTER TABLE TAAABB_BTERMM
    ADD CONSTRAINT FK_TAAABB_BTERMM_IT_MNGC_NO_IT_MNGC_SNO
    FOREIGN KEY (IT_MNGC_NO, IT_MNGC_SNO)
    REFERENCES TAAABB_BCOSTM (IT_MNGC_NO, IT_MNGC_SNO);

ALTER TABLE TAAABB_CAPPLA
    ADD CONSTRAINT FK_TAAABB_CAPPLA_APF_MNG_NO
    FOREIGN KEY (APF_MNG_NO)
    REFERENCES TAAABB_CAPPLM (APF_MNG_NO);

ALTER TABLE TAAABB_CBLBCM
    ADD CONSTRAINT FK_TAAABB_CBLBCM_BLB_MNG_NO
    FOREIGN KEY (BLB_MNG_NO)
    REFERENCES TAAABB_CBLBMM (BLB_MNG_NO);

ALTER TABLE TAAABB_CCMMTM
    ADD CONSTRAINT FK_TAAABB_CCMMTM_NAC_MNG_NO
    FOREIGN KEY (NAC_MNG_NO)
    REFERENCES TAAABB_CBLBCM (NAC_MNG_NO);

ALTER TABLE TAAABB_CORGNI
    ADD CONSTRAINT FK_TAAABB_CORGNI_PRLM_HRK_OGZ_C_CONE
    FOREIGN KEY (PRLM_HRK_OGZ_C_CONE)
    REFERENCES TAAABB_CORGNI (PRLM_OGZ_C_CONE);

ALTER TABLE TAAABB_CUSERI
    ADD CONSTRAINT FK_TAAABB_CUSERI_BBR_C
    FOREIGN KEY (BBR_C)
    REFERENCES TAAABB_CORGNI (PRLM_OGZ_C_CONE);

-- ============================================================================
-- 6. 표준명 일반 인덱스를 생성합니다.
-- ============================================================================

-- 기존 일반 인덱스 재생성
CREATE INDEX IDX_TAAABB_BITEMM_PRJ_MNG_NO ON TAAABB_BITEMM (PRJ_MNG_NO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CAPPLA_ORC_TB_CD_ORC_PK_VL_ORC_SNO_VL_APF_REL_SNO ON TAAABB_CAPPLA (ORC_TB_CD, ORC_PK_VL, ORC_SNO_VL, APF_REL_SNO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBCM_FST_ENR_USID_DEL_YN ON TAAABB_CBLBCM (FST_ENR_USID, DEL_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBCM_BBR_C ON TAAABB_CBLBCM (BBR_C) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBCM_NAC_GRP_NO_NAC_GRP_SQN ON TAAABB_CBLBCM (NAC_GRP_NO, NAC_GRP_SQN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBCM_HRK_NAC_MNG_NO ON TAAABB_CBLBCM (HRK_NAC_MNG_NO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBCM_BLB_MNG_NO_DEL_YN_SRE_YN_HRK_FXN_YN_FST_ENR_DTM ON TAAABB_CBLBCM (BLB_MNG_NO, DEL_YN, SRE_YN, HRK_FXN_YN, FST_ENR_DTM) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CBLBMM_USE_YN_SRE_SQN_NO ON TAAABB_CBLBMM (USE_YN, SRE_SQN_NO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CCMMTM_CMMT_GRP_NO_CMMT_GRP_SQN ON TAAABB_CCMMTM (CMMT_GRP_NO, CMMT_GRP_SQN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CCMMTM_HRK_CMMT_MNG_NO ON TAAABB_CCMMTM (HRK_CMMT_MNG_NO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CCMMTM_NAC_MNG_NO_DEL_YN_SRE_YN_FST_ENR_DTM ON TAAABB_CCMMTM (NAC_MNG_NO, DEL_YN, SRE_YN, FST_ENR_DTM) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CFILEM_ORC_DTT_ORC_PK_VL_DEL_YN ON TAAABB_CFILEM (ORC_DTT, ORC_PK_VL, DEL_YN) TABLESPACE USERS;

-- FK/조회 패턴 보강 인덱스
CREATE INDEX IDX_TAAABB_BTERMM_IT_MNGC_NO_IT_MNGC_SNO ON TAAABB_BTERMM (IT_MNGC_NO, IT_MNGC_SNO) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CAPPLA_APF_MNG_NO_ORC_TB_CD ON TAAABB_CAPPLA (APF_MNG_NO, ORC_TB_CD) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CORGNI_PRLM_HRK_OGZ_C_CONE ON TAAABB_CORGNI (PRLM_HRK_OGZ_C_CONE) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CUSERI_BBR_C ON TAAABB_CUSERI (BBR_C) TABLESPACE USERS;

-- 로그인 이력 조회 보강 인덱스
CREATE INDEX IDX_TAAABB_CLOGNH_ENO_LGN_DTM ON TAAABB_CLOGNH (ENO, LGN_DTM DESC) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CLOGNH_ENO_LGN_TP_LGN_DTM ON TAAABB_CLOGNH (ENO, LGN_TP, LGN_DTM DESC) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CLOGNH_LGN_TP_LGN_DTM ON TAAABB_CLOGNH (LGN_TP, LGN_DTM DESC) TABLESPACE USERS;

-- 첨부파일 상세 조회 보강 인덱스
CREATE INDEX IDX_TAAABB_CFILEM_ORC_DTT_ORC_PK_VL_FL_DTT_DEL_YN ON TAAABB_CFILEM (ORC_DTT, ORC_PK_VL, FL_DTT, DEL_YN) TABLESPACE USERS;

-- 프로젝트/비용/예산 현황 조회 보강 인덱스
CREATE INDEX IDX_TAAABB_BPROJM_BG_YY_DEL_YN_LST_YN_ORN_YN ON TAAABB_BPROJM (BG_YY, DEL_YN, LST_YN, ORN_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BPROJM_BG_YY_DEL_YN_LST_YN_PRJ_STS ON TAAABB_BPROJM (BG_YY, DEL_YN, LST_YN, PRJ_STS) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BITEMM_PRJ_MNG_NO_PRJ_SNO_DEL_YN_LST_YN ON TAAABB_BITEMM (PRJ_MNG_NO, PRJ_SNO, DEL_YN, LST_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BITEMM_IOE_C_DEL_YN_LST_YN ON TAAABB_BITEMM (IOE_C, DEL_YN, LST_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BCOSTM_BG_YY_DEL_YN_LST_YN_IOE_C ON TAAABB_BCOSTM (BG_YY, DEL_YN, LST_YN, IOE_C) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BCOSTM_BICE_DPM_DEL_YN_LST_YN ON TAAABB_BCOSTM (BICE_DPM, DEL_YN, LST_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BBUGTM_BG_YY_ORC_TB_ORC_PK_VL_DEL_YN ON TAAABB_BBUGTM (BG_YY, ORC_TB, ORC_PK_VL, DEL_YN) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_BBUGTM_ORC_TB_ORC_PK_VL_ORC_SNO_VL ON TAAABB_BBUGTM (ORC_TB, ORC_PK_VL, ORC_SNO_VL) TABLESPACE USERS;

-- 공통코드 조회 보강 인덱스
CREATE INDEX IDX_TAAABB_CCODEM_C_ID_DEL_YN_STT_DT_END_DT ON TAAABB_CCODEM (C_ID, DEL_YN, STT_DT, END_DT) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CCODEM_C_TP_DEL_YN_STT_DT_END_DT ON TAAABB_CCODEM (C_TP, DEL_YN, STT_DT, END_DT) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CCODEM_HRK_C_DEL_YN ON TAAABB_CCODEM (HRK_C, DEL_YN) TABLESPACE USERS;

-- 리프레시 토큰 조회 보강 인덱스
CREATE INDEX IDX_TAAABB_CRTOKM_TOK ON TAAABB_CRTOKM (TOK) TABLESPACE USERS;
CREATE INDEX IDX_TAAABB_CRTOKM_ENO ON TAAABB_CRTOKM (ENO) TABLESPACE USERS;

-- ============================================================================
-- 7. 옵티마이저 통계를 수집합니다.
-- ============================================================================
BEGIN
    DBMS_STATS.GATHER_SCHEMA_STATS(
        ownname          => USER,
        cascade          => TRUE,
        estimate_percent => DBMS_STATS.AUTO_SAMPLE_SIZE,
        method_opt       => 'FOR ALL COLUMNS SIZE AUTO'
    );
END;
/

COMMIT;
