-- =============================================================================
-- Phase 3: LOG_SNO 23개 로그 테이블 VARCHAR2(32) -> NUMBER(22)
-- Migration: V20260521_003__fix_sno_number22_phase3_log.sql
-- Date: 2026-05-21
-- =============================================================================
-- 변환식: TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', ''))
-- 예: 'BPROJL-0000000000000000000001' -> 1
-- 패턴: ADD TMP -> UPDATE -> DROP PK -> DROP COLUMN -> RENAME -> MODIFY NOT NULL -> ADD PK -> SEQ 재생성
-- =============================================================================

-- 1. TAAABB_BASCTL (정보화실무협의회 기본정보 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BASCTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BASCTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BASCTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BASCTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BASCTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BASCTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BASCTL ADD CONSTRAINT PK_BASCTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BASCTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BASCTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BASCTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 2. TAAABB_BBUGTL (예산 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BBUGTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BBUGTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BBUGTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BBUGTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BBUGTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BBUGTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BBUGTL ADD CONSTRAINT PK_BBUGTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BBUGTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BBUGTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BBUGTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 3. TAAABB_BCMMTL (협의회 평가위원 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BCMMTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BCMMTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCMMTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BCMMTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCMMTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCMMTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BCMMTL ADD CONSTRAINT PK_BCMMTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BCMMTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BCMMTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BCMMTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 4. TAAABB_BCOSTL (전산관리비 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BCOSTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BCOSTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCOSTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCOSTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BCOSTL ADD CONSTRAINT PK_BCOSTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BCOSTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BCOSTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BCOSTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 5. TAAABB_BCHKLL (타당성 자체점검 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BCHKLL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BCHKLL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BCHKLL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BCHKLL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCHKLL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BCHKLL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BCHKLL ADD CONSTRAINT PK_BCHKLL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BCHKLL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BCHKLL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BCHKLL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 6. TAAABB_BEVALL (평가위원 평가의견 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BEVALL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BEVALL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BEVALL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BEVALL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BEVALL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BEVALL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BEVALL ADD CONSTRAINT PK_BEVALL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BEVALL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BEVALL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BEVALL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 7. TAAABB_BGDOCL (가이드 문서 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BGDOCL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BGDOCL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BGDOCL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BGDOCL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BGDOCL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BGDOCL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BGDOCL ADD CONSTRAINT PK_BGDOCL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BGDOCL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BGDOCL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BGDOCL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 8. TAAABB_BITEML (정보화사업 품목 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BITEML ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BITEML SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BITEML DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BITEML DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BITEML RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BITEML MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BITEML ADD CONSTRAINT PK_BITEML PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BITEML;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BITEML'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BITEML START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 9. TAAABB_BPERFL (성과관리 자체계획 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BPERFL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BPERFL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPERFL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BPERFL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPERFL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPERFL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BPERFL ADD CONSTRAINT PK_BPERFL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BPERFL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BPERFL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BPERFL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 10. TAAABB_BPLANL (정보기술부문계획 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BPLANL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BPLANL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPLANL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPLANL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BPLANL ADD CONSTRAINT PK_BPLANL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BPLANL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BPLANL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BPLANL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 11. TAAABB_BPOVWL (협의회 사업개요 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BPOVWL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BPOVWL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPOVWL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BPOVWL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPOVWL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPOVWL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BPOVWL ADD CONSTRAINT PK_BPOVWL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BPOVWL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BPOVWL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BPOVWL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 12. TAAABB_BPQNAL (사전질의응답 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BPQNAL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BPQNAL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPQNAL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BPQNAL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPQNAL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPQNAL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BPQNAL ADD CONSTRAINT PK_BPQNAL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BPQNAL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BPQNAL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BPQNAL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 13. TAAABB_BPROJL (정보화사업 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BPROJL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BPROJL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BPROJL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BPROJL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPROJL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BPROJL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BPROJL ADD CONSTRAINT PK_BPROJL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BPROJL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BPROJL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BPROJL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 14. TAAABB_BRDOCL (요구사항 정의서 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BRDOCL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BRDOCL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRDOCL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BRDOCL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRDOCL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRDOCL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BRDOCL ADD CONSTRAINT PK_BRDOCL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BRDOCL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BRDOCL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BRDOCL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 15. TAAABB_BRIVGL (문서 검토의견 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BRIVGL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BRIVGL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRIVGL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BRIVGL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRIVGL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRIVGL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BRIVGL ADD CONSTRAINT PK_BRIVGL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BRIVGL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BRIVGL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BRIVGL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 16. TAAABB_BRSLTL (협의회 결과서 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BRSLTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BRSLTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BRSLTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BRSLTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRSLTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRSLTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BRSLTL ADD CONSTRAINT PK_BRSLTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BRSLTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BRSLTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BRSLTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 17. TAAABB_BSCHDL (협의회 일정 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BSCHDL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BSCHDL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BSCHDL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BSCHDL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BSCHDL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BSCHDL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BSCHDL ADD CONSTRAINT PK_BSCHDL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BSCHDL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BSCHDL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BSCHDL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 18. TAAABB_BTERML (단말기관리마스터 변경 로그)
ALTER TABLE ITPAPP.TAAABB_BTERML ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_BTERML SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BTERML DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BTERML RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_BTERML MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BTERML ADD CONSTRAINT PK_BTERML PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BTERML;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BTERML'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BTERML START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 19. TAAABB_CAPPLL (신청서 마스터 변경 로그)
ALTER TABLE ITPAPP.TAAABB_CAPPLL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CAPPLL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CAPPLL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CAPPLL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CAPPLL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CAPPLL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CAPPLL ADD CONSTRAINT PK_CAPPLL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CAPPLL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CAPPLL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CAPPLL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 20. TAAABB_CBLBCL (게시물 변경 로그)
ALTER TABLE ITPAPP.TAAABB_CBLBCL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CBLBCL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBCL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CBLBCL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CBLBCL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CBLBCL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CBLBCL ADD CONSTRAINT PK_CBLBCL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CBLBCL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CBLBCL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CBLBCL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 21. TAAABB_CBLBML (게시판 메타 변경 로그)
ALTER TABLE ITPAPP.TAAABB_CBLBML ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CBLBML SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CBLBML DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CBLBML DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CBLBML RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CBLBML MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CBLBML ADD CONSTRAINT PK_CBLBML PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CBLBML;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CBLBML'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CBLBML START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 22. TAAABB_CCODEL (코드 마스터 변경 로그)
ALTER TABLE ITPAPP.TAAABB_CCODEL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CCODEL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CCODEL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CCODEL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CCODEL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CCODEL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CCODEL ADD CONSTRAINT PK_CCODEL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CCODEL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CCODEL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CCODEL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- 23. TAAABB_CCMMTL (댓글 변경 로그)
ALTER TABLE ITPAPP.TAAABB_CCMMTL ADD TMP_LOG_SNO NUMBER(22);
UPDATE ITPAPP.TAAABB_CCMMTL SET TMP_LOG_SNO = TO_NUMBER(REGEXP_REPLACE(LOG_SNO, '[^0-9]', '')) WHERE LOG_SNO IS NOT NULL;
COMMIT;
ALTER TABLE ITPAPP.TAAABB_CCMMTL DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_CCMMTL DROP COLUMN LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CCMMTL RENAME COLUMN TMP_LOG_SNO TO LOG_SNO;
ALTER TABLE ITPAPP.TAAABB_CCMMTL MODIFY LOG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_CCMMTL ADD CONSTRAINT PK_CCMMTL PRIMARY KEY (LOG_SNO);
COMMIT;
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(LOG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_CCMMTL;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_CCMMTL'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_CCMMTL START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

COMMIT;
