-- V20260624_002__CreateBprojaDropStatus.sql
-- 정보화사업관계(TPRMPP_BPROJA) 신설 + BPROJM/BPROJL의 IT_PTL_STS_TC 제거.
--  - BPROJA: 프로젝트(ABUS_MNG_NO)와 각 단계 원본문서(CNCD_RFR_NO=단계 자기 key)의 상태(IT_PTL_STS_TC) 정규화.
--  - 상태는 더 이상 BPROJM 단일 컬럼이 아니라 BPROJA 다건으로 관리(대표상태=MAX(IT_PTL_STS_TC)).
--  - 데이터 이관 없음(빈 테이블 시작). 적재(8개 단계 서비스 upsert)는 2차.
-- 주의: 적용 후 수정 금지(Flyway 체크섬). 변경은 새 버전으로.

-- 1) 정보화사업관계 테이블 생성
CREATE TABLE ITPOWN.TPRMPP_BPROJA (
    ABUS_MNG_NO   VARCHAR2(30 CHAR)  NOT NULL,
    CNCD_RFR_NO   VARCHAR2(30 CHAR)  NOT NULL,
    IT_PTL_STS_TC VARCHAR2(2 CHAR),
    FST_ENR_USID  VARCHAR2(14 CHAR)  DEFAULT '00000000000000' NOT NULL,
    FST_ENR_DTM   DATE               DEFAULT SYSDATE NOT NULL,
    DEL_YN        VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
    GUID          VARCHAR2(38 CHAR)  DEFAULT '00000000000000000000000000000000000000' NOT NULL,
    GUID_PRG_SNO  NUMBER(4)          DEFAULT 0 NOT NULL,
    LST_CHG_USID  VARCHAR2(14 CHAR)  DEFAULT '00000000000000' NOT NULL,
    LST_CHG_DTM   DATE               DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TPRMPP_BPROJA PRIMARY KEY (ABUS_MNG_NO, CNCD_RFR_NO)
);

COMMENT ON TABLE  ITPOWN.TPRMPP_BPROJA               IS '프로젝트관리_정보화사업관계';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.ABUS_MNG_NO   IS '사업관리번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.CNCD_RFR_NO   IS '관련참조번호(단계 원본문서 key)';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.IT_PTL_STS_TC IS 'IT포탈상태구분코드';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.FST_ENR_USID  IS '최초등록사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.FST_ENR_DTM   IS '최초등록일시';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.DEL_YN        IS '삭제여부';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.GUID          IS 'GUID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.GUID_PRG_SNO  IS 'GUID진행일련번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.LST_CHG_USID  IS '최종변경사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BPROJA.LST_CHG_DTM   IS '최종변경일시';

-- 2) 기존 단일 상태 컬럼 제거 (마스터 + 로그)
ALTER TABLE ITPOWN.TPRMPP_BPROJM DROP COLUMN IT_PTL_STS_TC;
ALTER TABLE ITPOWN.TPRMPP_BPROJL DROP COLUMN IT_PTL_STS_TC;
