-- =============================================================================
-- V20260630_003__SimplifyCouncilSkipAttachment.sql
-- 협의회 생략판정요청(TPRMPP_BASKPM/BASKPL) 컬럼 정리. (PRD_c_20260620 #3)
--
--  1) 첨부 간소화
--     - 타당성검토표는 협의회 구조화 데이터(Bpovwm + 성과지표)로 활용 → 파일참조 불필요 → PRTY_IVG_FL_MPN_ID 제거
--     - 첨부는 사업계획서 1종뿐 → ABUS_PDC_FL_MPN_ID → FL_MPN_ID 로 간소화(Bpovwm/Brsltm와 동일 표준)
--  2) 의견/응답 내용 컬럼 재명명 + 길이 확장(VARCHAR2(4000 BYTE))
--     - 요청측(정보보호기획) 사유   : PRTY_IVG_OMT_RSN → CGPR_OPNN_CONE(담당자의견내용)
--     - 응답측(IT기획) 판정 내용     : OMT_CNFM_CONE    → CGPR_RPD_CONE (담당자응답내용)
--     - 본 DB는 max_string_size=STANDARD(최대 4000 BYTE) → BYTE 명시(게시판 본문 NAC_CONE과 동일)
--
-- 마스터/로그 동일 적용. 테이블 비어 있어 RENAME/MODIFY 안전. 적용 후 수정 금지(Flyway 체크섬). 소유 스키마 ITPOWN.
-- =============================================================================

-- 1) 마스터(TPRMPP_BASKPM)
ALTER TABLE ITPOWN.TPRMPP_BASKPM DROP COLUMN PRTY_IVG_FL_MPN_ID;
ALTER TABLE ITPOWN.TPRMPP_BASKPM RENAME COLUMN ABUS_PDC_FL_MPN_ID TO FL_MPN_ID;
ALTER TABLE ITPOWN.TPRMPP_BASKPM RENAME COLUMN PRTY_IVG_OMT_RSN TO CGPR_OPNN_CONE;
ALTER TABLE ITPOWN.TPRMPP_BASKPM MODIFY (CGPR_OPNN_CONE VARCHAR2(4000 BYTE));
ALTER TABLE ITPOWN.TPRMPP_BASKPM RENAME COLUMN OMT_CNFM_CONE TO CGPR_RPD_CONE;
ALTER TABLE ITPOWN.TPRMPP_BASKPM MODIFY (CGPR_RPD_CONE VARCHAR2(4000 BYTE));
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.FL_MPN_ID     IS '첨부파일관리번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.CGPR_OPNN_CONE IS '담당자의견내용';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.CGPR_RPD_CONE  IS '담당자응답내용';

-- 2) 로그(TPRMPP_BASKPL)
ALTER TABLE ITPOWN.TPRMPP_BASKPL DROP COLUMN PRTY_IVG_FL_MPN_ID;
ALTER TABLE ITPOWN.TPRMPP_BASKPL RENAME COLUMN ABUS_PDC_FL_MPN_ID TO FL_MPN_ID;
ALTER TABLE ITPOWN.TPRMPP_BASKPL RENAME COLUMN PRTY_IVG_OMT_RSN TO CGPR_OPNN_CONE;
ALTER TABLE ITPOWN.TPRMPP_BASKPL MODIFY (CGPR_OPNN_CONE VARCHAR2(4000 BYTE));
ALTER TABLE ITPOWN.TPRMPP_BASKPL RENAME COLUMN OMT_CNFM_CONE TO CGPR_RPD_CONE;
ALTER TABLE ITPOWN.TPRMPP_BASKPL MODIFY (CGPR_RPD_CONE VARCHAR2(4000 BYTE));
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.FL_MPN_ID     IS '첨부파일관리번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.CGPR_OPNN_CONE IS '담당자의견내용';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.CGPR_RPD_CONE  IS '담당자응답내용';

-- 3) BASKPL 공통 7컬럼을 표준 순서로 맨뒤 재배치 (다른 *L 테이블 BASCTL과 동일 순서).
--    Oracle은 컬럼 순서 변경을 직접 지원하지 않아, 빈 테이블에서 DROP 후 표준 순서로 재ADD.
ALTER TABLE ITPOWN.TPRMPP_BASKPL DROP (FST_ENR_USID, FST_ENR_DTM, DEL_YN, GUID, GUID_PRG_SNO, LST_CHG_USID, LST_CHG_DTM);
ALTER TABLE ITPOWN.TPRMPP_BASKPL ADD (
    FST_ENR_USID VARCHAR2(14 CHAR),
    FST_ENR_DTM  DATE,
    DEL_YN       VARCHAR2(1 CHAR),
    GUID         VARCHAR2(38 CHAR),
    GUID_PRG_SNO NUMBER(4),
    LST_CHG_USID VARCHAR2(14 CHAR),
    LST_CHG_DTM  DATE
);
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.FST_ENR_DTM  IS '최초등록일시';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.DEL_YN       IS '삭제여부';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.GUID         IS 'GUID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPL.LST_CHG_DTM  IS '최종변경일시';
