-- =============================================================================
-- Phase 4: IVG_SNO UUID VARCHAR2(32) -> NUMBER(22)
-- Migration: V20260521_005__fix_sno_number22_phase4_ivg.sql
-- Date: 2026-05-21
-- =============================================================================
-- UUID는 숫자 직접 변환 불가 -> GTT(Global Temporary Table) 매핑 방식 사용
-- BRIVGM, BRIVGL 양쪽 IVG_SNO를 동일 매핑으로 교체
-- =============================================================================

-- Step 1: UUID -> 등록순 번호 매핑 GTT 생성
CREATE GLOBAL TEMPORARY TABLE ITPAPP.TMP_IVG_MAP (
    OLD_IVG_SNO VARCHAR2(32) NOT NULL,
    NEW_IVG_SNO NUMBER(22)   NOT NULL
) ON COMMIT PRESERVE ROWS;

-- Step 2: 매핑 채우기 (등록일시 기준 ROWNUM 순번 할당)
INSERT INTO ITPAPP.TMP_IVG_MAP (OLD_IVG_SNO, NEW_IVG_SNO)
SELECT IVG_SNO, ROWNUM
FROM ITPAPP.TAAABB_BRIVGM
ORDER BY FST_ENR_DTM, IVG_SNO;
COMMIT;

-- Step 3: BRIVGM - 임시 NUMBER 컬럼 추가
ALTER TABLE ITPAPP.TAAABB_BRIVGM ADD TMP_IVG_SNO NUMBER(22);

-- Step 4: BRIVGM - 매핑 기반 번호 채우기
UPDATE ITPAPP.TAAABB_BRIVGM m
SET TMP_IVG_SNO = (
    SELECT t.NEW_IVG_SNO
    FROM ITPAPP.TMP_IVG_MAP t
    WHERE t.OLD_IVG_SNO = m.IVG_SNO
);
COMMIT;

-- Step 5: BRIVGL - IVG_SNO(스냅샷 컬럼) 임시 NUMBER 컬럼 추가
ALTER TABLE ITPAPP.TAAABB_BRIVGL ADD TMP_IVG_SNO NUMBER(22);

-- Step 6: BRIVGL - 매핑 기반 번호 채우기 (LOG_SNO != IVG_SNO 주의)
UPDATE ITPAPP.TAAABB_BRIVGL l
SET TMP_IVG_SNO = (
    SELECT t.NEW_IVG_SNO
    FROM ITPAPP.TMP_IVG_MAP t
    WHERE t.OLD_IVG_SNO = l.IVG_SNO
);
COMMIT;

-- Step 7: BRIVGM - PK 삭제 -> 구 컬럼 삭제 -> 임시컬럼 이름 변경 -> NOT NULL -> PK 재생성
ALTER TABLE ITPAPP.TAAABB_BRIVGM DROP PRIMARY KEY CASCADE;
ALTER TABLE ITPAPP.TAAABB_BRIVGM DROP COLUMN IVG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRIVGM RENAME COLUMN TMP_IVG_SNO TO IVG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRIVGM MODIFY IVG_SNO NOT NULL;
ALTER TABLE ITPAPP.TAAABB_BRIVGM ADD CONSTRAINT PK_BRIVGM PRIMARY KEY (IVG_SNO);
COMMIT;

-- Step 8: BRIVGL - 구 IVG_SNO 컬럼 삭제 -> 임시컬럼 이름 변경 (PK 아닌 스냅샷 컬럼)
ALTER TABLE ITPAPP.TAAABB_BRIVGL DROP COLUMN IVG_SNO;
ALTER TABLE ITPAPP.TAAABB_BRIVGL RENAME COLUMN TMP_IVG_SNO TO IVG_SNO;
COMMIT;

-- Step 9: SEQ_BRIVGM 생성 (기존에 없는 신규 시퀀스)
DECLARE
    v_max NUMBER;
BEGIN
    SELECT NVL(MAX(IVG_SNO), 0) INTO v_max FROM ITPAPP.TAAABB_BRIVGM;
    BEGIN EXECUTE IMMEDIATE 'DROP SEQUENCE ITPAPP.SEQ_BRIVGM'; EXCEPTION WHEN OTHERS THEN NULL; END;
    EXECUTE IMMEDIATE 'CREATE SEQUENCE ITPAPP.SEQ_BRIVGM START WITH ' || (v_max + 1) || ' MAXVALUE 9999999999999999999999 NOCYCLE CACHE 20 NOORDER';
END;
/

-- Step 10: 매핑 GTT 삭제
DROP TABLE ITPAPP.TMP_IVG_MAP;

COMMIT;
