-- =============================================================================
-- V20260630_002__CreateCouncilSkipRequest.sql
-- 협의회 타당성검토 생략판정요청(TPRMPP_BASKPM) + 변경로그(TPRMPP_BASKPL) + 시퀀스 + 사유코드.
-- (PRD_c_20260620 #3 — Phase 4a: DB/엔티티)
--
--  - 정보보호기획(ITPAD002)이 IT기획(ITPAD001) 앞으로 보내는 '타당성 검토 생략 판정 요청'을 적재.
--  - 결재(IT기획팀장→부장) 완료 콜백으로 생략 확정(skipCouncil) / 개최준비(startPreparation) / 반려 분기.
--  - 협의회 진행상태(BASCTM)는 04 유지, 본 요청테이블의 PRC_STS_TC로 진행 추적(신규 협의회 상태코드 미추가).
--
-- 주의: 적용 후 수정 금지(Flyway 체크섬). 변경은 새 버전으로. 소유 스키마 ITPOWN.
-- =============================================================================

-- 1) 생략판정요청 마스터
CREATE TABLE ITPOWN.TPRMPP_BASKPM (
    IT_PTL_ASCT_ID        VARCHAR2(32 CHAR)   NOT NULL,
    PRTY_IVG_OMT_RSN_TC   VARCHAR2(2 CHAR)    NOT NULL,
    PRTY_IVG_OMT_RSN      VARCHAR2(200 CHAR)  NOT NULL,
    ABUS_PDC_FL_MPN_ID    VARCHAR2(36 CHAR)   NOT NULL,
    PRTY_IVG_FL_MPN_ID    VARCHAR2(36 CHAR)   NOT NULL,
    RQS_USID              VARCHAR2(14 CHAR)   NOT NULL,
    RQS_DTM               DATE                NOT NULL,
    PRTY_IVG_OMT_YN       VARCHAR2(1 CHAR),
    OMT_CNFM_CONE         VARCHAR2(2000 CHAR),
    CNFM_USID             VARCHAR2(14 CHAR),
    CNFM_DTM              DATE,
    APF_MNG_NO            VARCHAR2(30 CHAR),
    FST_ENR_USID          VARCHAR2(14 CHAR)   DEFAULT '00000000000000' NOT NULL,
    FST_ENR_DTM           DATE                DEFAULT SYSDATE NOT NULL,
    DEL_YN                VARCHAR2(1 CHAR)    DEFAULT 'N' NOT NULL,
    GUID                  VARCHAR2(38 CHAR)   DEFAULT '00000000000000000000000000000000000000' NOT NULL,
    GUID_PRG_SNO          NUMBER(4)           DEFAULT 0 NOT NULL,
    LST_CHG_USID          VARCHAR2(14 CHAR)   DEFAULT '00000000000000' NOT NULL,
    LST_CHG_DTM           DATE                DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TPRMPP_BASKPM PRIMARY KEY (IT_PTL_ASCT_ID)
);

COMMENT ON TABLE  ITPOWN.TPRMPP_BASKPM                       IS '정보화실무협의회 타당성검토 생략판정요청';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.IT_PTL_ASCT_ID        IS '협의회ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.PRTY_IVG_OMT_RSN_TC   IS '타당성검토생략사유구분코드';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.PRTY_IVG_OMT_RSN      IS '타당성검토생략사유';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.ABUS_PDC_FL_MPN_ID    IS '사업계획서첨부파일관리번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.PRTY_IVG_FL_MPN_ID    IS '타당성검토표첨부파일관리번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.RQS_USID            IS '신청사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.RQS_DTM              IS '신청일시';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.PRTY_IVG_OMT_YN      IS '타당성검토생략여부(확인결과)';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.OMT_CNFM_CONE       IS '생략확인내용';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.CNFM_USID           IS '확인사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.CNFM_DTM            IS '확인일시';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.APF_MNG_NO         IS '신청관리번호(전자결재)';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.FST_ENR_USID       IS '최초등록사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.FST_ENR_DTM        IS '최초등록일시';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.DEL_YN             IS '삭제여부';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.GUID               IS 'GUID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.GUID_PRG_SNO       IS 'GUID진행일련번호';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.LST_CHG_USID       IS '최종변경사용자ID';
COMMENT ON COLUMN ITPOWN.TPRMPP_BASKPM.LST_CHG_DTM        IS '최종변경일시';

-- 2) 생략판정요청 변경 로그 (감사로그 — BaseLogEntity 구조, PK=LOG_HIS_TGR_SNO)
CREATE TABLE ITPOWN.TPRMPP_BASKPL (
    LOG_HIS_TGR_SNO       NUMBER              NOT NULL,
    IT_PTL_ASCT_ID        VARCHAR2(32 CHAR),
    PRTY_IVG_OMT_RSN_TC   VARCHAR2(2 CHAR),
    PRTY_IVG_OMT_RSN      VARCHAR2(200 CHAR),
    ABUS_PDC_FL_MPN_ID    VARCHAR2(36 CHAR),
    PRTY_IVG_FL_MPN_ID    VARCHAR2(36 CHAR),
    RQS_USID              VARCHAR2(14 CHAR),
    RQS_DTM               DATE,
    PRTY_IVG_OMT_YN       VARCHAR2(1 CHAR),
    OMT_CNFM_CONE         VARCHAR2(2000 CHAR),
    CNFM_USID             VARCHAR2(14 CHAR),
    CNFM_DTM              DATE,
    APF_MNG_NO            VARCHAR2(30 CHAR),
    CHG_DTT_YN            VARCHAR2(1 CHAR),
    CHG_DTM               DATE                NOT NULL,
    CHG_USID              VARCHAR2(14 CHAR),
    DEL_YN                VARCHAR2(1 CHAR),
    GUID                  VARCHAR2(38 CHAR),
    GUID_PRG_SNO          NUMBER(4),
    FST_ENR_DTM           DATE,
    FST_ENR_USID          VARCHAR2(14 CHAR),
    LST_CHG_DTM           DATE,
    LST_CHG_USID          VARCHAR2(14 CHAR),
    CONSTRAINT PK_TPRMPP_BASKPL PRIMARY KEY (LOG_HIS_TGR_SNO)
);

COMMENT ON TABLE ITPOWN.TPRMPP_BASKPL IS '정보화실무협의회 타당성검토 생략판정요청 변경 로그';

-- 3) 로그 시퀀스 (AuditLogIdGenerator: TPRMPP_BASKPL → S_BASKPL.NEXTVAL)
CREATE SEQUENCE ITPOWN.S_BASKPL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- 4) 공통코드: 타당성검토생략사유구분코드 (IT업무지침 제44조 제3항 4종)
DELETE FROM ITPOWN.TPRMPP_CCODEM WHERE CO_C_ID_NM = 'PRTY_IVG_OMT_RSN_TC';
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('PRTY_IVG_OMT_RSN_TC','01','20260101','99991231',NULL,'타당성검토생략사유','소요예산(추정) 전결권자가 부점장 이하인 사업',1,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('PRTY_IVG_OMT_RSN_TC','02','20260101','99991231',NULL,'타당성검토생략사유','법률·규제 대응을 위한 사업',2,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('PRTY_IVG_OMT_RSN_TC','03','20260101','99991231',NULL,'타당성검토생략사유','기존 AI·클라우드·구독형 SW 서비스 연장 사업',3,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');
INSERT INTO ITPOWN.TPRMPP_CCODEM (CO_C_ID_NM,CDVA_ID,STT_DT,END_DT,CO_CDVA_NM,CO_C_NM,CDVA_NM,C_SQN_SNO,CO_C_INTN_NM,CO_C_INTN_CONE,CO_CDVA_ABV_NM,CO_CDVA_SPS,HRK_CDVA_ID,FST_ENR_USID,FST_ENR_DTM,DEL_YN) VALUES ('PRTY_IVG_OMT_RSN_TC','04','20260101','99991231',NULL,'타당성검토생략사유','위원장이 타당성 검토 불필요로 판단한 사업',4,NULL,NULL,NULL,NULL,NULL,'MIGRATION',SYSDATE,'N');

COMMIT;
