-- 메뉴 관리 4개 테이블 (공통화면상세/메뉴기본/메뉴권한연결/메뉴로그)
-- 수동 실행: sqlplus ITPAPP/****@127.0.0.1:1521/XEPDB1 @V20260603_007__CreateMenuTables.sql
-- ddl-auto=validate 이므로 엔티티 작성 전 본 스크립트를 먼저 실행해야 부팅 검증을 통과한다.
-- BaseEntity/BaseLogEntity 컬럼 타입은 ITPAPP_DDL_live.sql(CCODEM/BBUGTL)에서 확인한 실제 타입을 사용:
--   FST_ENR_DTM/LST_CHG_DTM = DATE, GUID_PRG_SNO = NUMBER(4,0), LOG_HIS_TGR_SNO = NUMBER(18,0), CHG_DTM = TIMESTAMP(9)

-- 1) 공통화면상세 — 라우트 카탈로그
CREATE TABLE TPRMPP_CMENUD (
  SRE_PTH       VARCHAR2(300 CHAR) NOT NULL,
  SRE_MNU_NM    VARCHAR2(100 CHAR) NOT NULL,
  SRE_TC        VARCHAR2(2 CHAR),
  USE_YN        VARCHAR2(1 CHAR)   DEFAULT 'Y' NOT NULL,
  RMK           VARCHAR2(300 CHAR),
  DEL_YN        VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID          VARCHAR2(38 CHAR),
  GUID_PRG_SNO  NUMBER(4,0),
  FST_ENR_DTM   DATE,
  FST_ENR_USID  VARCHAR2(14 CHAR),
  LST_CHG_DTM   DATE,
  LST_CHG_USID  VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_CMENUD PRIMARY KEY (SRE_PTH),
  CONSTRAINT CK_CMENUD_USE_YN CHECK (USE_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_CMENUD            IS '공통화면상세 — 라우트 카탈로그';
COMMENT ON COLUMN TPRMPP_CMENUD.SRE_PTH    IS '화면경로';
COMMENT ON COLUMN TPRMPP_CMENUD.SRE_MNU_NM IS '화면메뉴명';
COMMENT ON COLUMN TPRMPP_CMENUD.SRE_TC     IS '화면구분코드';
COMMENT ON COLUMN TPRMPP_CMENUD.USE_YN     IS '사용여부';
COMMENT ON COLUMN TPRMPP_CMENUD.RMK        IS '비고';

-- 2) 공통메뉴기본 — 메뉴 마스터
CREATE TABLE TPRMPP_CMENUM (
  MNU_ID          VARCHAR2(10 CHAR)  NOT NULL,
  HRK_MNU_ID      VARCHAR2(10 CHAR),
  SRE_TC          VARCHAR2(2 CHAR)   NOT NULL,
  MNU_NM          VARCHAR2(100 CHAR) NOT NULL,
  MNU_TP_C        VARCHAR2(3 CHAR)   NOT NULL,
  SRE_PTH         VARCHAR2(300 CHAR),
  MNU_SOT_SQN_SNO NUMBER(9,0)        NOT NULL,
  HID_YN          VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  MNU_DEP         NUMBER(3,0)        NOT NULL,
  WHL_MNU_PTH     VARCHAR2(500 CHAR) NOT NULL,
  DEL_YN          VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID            VARCHAR2(38 CHAR),
  GUID_PRG_SNO    NUMBER(4,0),
  FST_ENR_DTM     DATE,
  FST_ENR_USID    VARCHAR2(14 CHAR),
  LST_CHG_DTM     DATE,
  LST_CHG_USID    VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_CMENUM PRIMARY KEY (MNU_ID),
  CONSTRAINT CK_CMENUM_TP   CHECK (MNU_TP_C IN ('LNK','GRP','DYN')),
  CONSTRAINT CK_CMENUM_HID  CHECK (HID_YN IN ('Y','N')),
  CONSTRAINT CK_CMENUM_DEP  CHECK (MNU_DEP BETWEEN 1 AND 3),
  CONSTRAINT FK_CMENUM_SRE  FOREIGN KEY (SRE_PTH) REFERENCES TPRMPP_CMENUD (SRE_PTH)
);
COMMENT ON TABLE  TPRMPP_CMENUM             IS '공통메뉴기본 — 메뉴 마스터';
COMMENT ON COLUMN TPRMPP_CMENUM.MNU_ID      IS '메뉴ID';
COMMENT ON COLUMN TPRMPP_CMENUM.HRK_MNU_ID  IS '상위메뉴ID';
COMMENT ON COLUMN TPRMPP_CMENUM.SRE_TC      IS '화면구분코드';
COMMENT ON COLUMN TPRMPP_CMENUM.MNU_NM      IS '메뉴명';
COMMENT ON COLUMN TPRMPP_CMENUM.MNU_TP_C    IS '메뉴유형코드';
COMMENT ON COLUMN TPRMPP_CMENUM.SRE_PTH     IS '화면경로';
COMMENT ON COLUMN TPRMPP_CMENUM.MNU_SOT_SQN_SNO IS '메뉴정렬순서일련번호';
COMMENT ON COLUMN TPRMPP_CMENUM.HID_YN      IS '숨김여부';
COMMENT ON COLUMN TPRMPP_CMENUM.MNU_DEP     IS '메뉴깊이';
COMMENT ON COLUMN TPRMPP_CMENUM.WHL_MNU_PTH IS '전체메뉴경로';

CREATE INDEX IDX_CMENUM_TREE ON TPRMPP_CMENUM (SRE_TC, HRK_MNU_ID, MNU_SOT_SQN_SNO);
CREATE INDEX IDX_CMENUM_PTH  ON TPRMPP_CMENUM (SRE_PTH);
CREATE INDEX IDX_CMENUM_WHL  ON TPRMPP_CMENUM (WHL_MNU_PTH);

-- 3) 공통메뉴권한연결 — 메뉴↔권한
CREATE TABLE TPRMPP_CMENUA (
  MNU_ID        VARCHAR2(10 CHAR) NOT NULL,
  ATH_ID        VARCHAR2(32 CHAR) NOT NULL,
  DEL_YN        VARCHAR2(1 CHAR)  DEFAULT 'N' NOT NULL,
  GUID          VARCHAR2(38 CHAR),
  GUID_PRG_SNO  NUMBER(4,0),
  FST_ENR_DTM   DATE,
  FST_ENR_USID  VARCHAR2(14 CHAR),
  LST_CHG_DTM   DATE,
  LST_CHG_USID  VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_CMENUA PRIMARY KEY (MNU_ID, ATH_ID)
);
COMMENT ON TABLE  TPRMPP_CMENUA        IS '공통메뉴권한연결 — 메뉴↔권한';
COMMENT ON COLUMN TPRMPP_CMENUA.MNU_ID IS '메뉴ID';
COMMENT ON COLUMN TPRMPP_CMENUA.ATH_ID IS '권한ID';

-- 4) 공통메뉴로그 — 변경 스냅샷 (BaseLogEntity)
CREATE TABLE TPRMPP_CMENUL (
  LOG_HIS_TGR_SNO NUMBER(18,0)       NOT NULL,
  CHG_DTT_YN      VARCHAR2(1 CHAR),
  CHG_DTM         TIMESTAMP(9),
  CHG_USID        VARCHAR2(14 CHAR),
  DEL_YN          VARCHAR2(1 CHAR),
  GUID            VARCHAR2(38 CHAR),
  GUID_PRG_SNO    NUMBER(4,0),
  FST_ENR_DTM     DATE,
  FST_ENR_USID    VARCHAR2(14 CHAR),
  LST_CHG_DTM     DATE,
  LST_CHG_USID    VARCHAR2(14 CHAR),
  MNU_ID          VARCHAR2(10 CHAR),
  HRK_MNU_ID      VARCHAR2(10 CHAR),
  SRE_TC          VARCHAR2(2 CHAR),
  MNU_NM          VARCHAR2(100 CHAR),
  MNU_TP_C        VARCHAR2(3 CHAR),
  SRE_PTH         VARCHAR2(300 CHAR),
  MNU_SOT_SQN_SNO NUMBER(9,0),
  HID_YN          VARCHAR2(1 CHAR),
  MNU_DEP         NUMBER(3,0),
  WHL_MNU_PTH     VARCHAR2(500 CHAR),
  CONSTRAINT PK_TPRMPP_CMENUL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE TPRMPP_CMENUL IS '공통메뉴로그 — 변경 스냅샷';

-- 5) 시퀀스
--   메뉴ID 채번용 (마스터 컨벤션 SEQ_*)
CREATE SEQUENCE SEQ_CMENUM START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
--   로그 PK 채번용 — AuditLogIdGenerator가 SEQ_CMENUL.NEXTVAL을 호출하므로 반드시 이 이름
CREATE SEQUENCE SEQ_CMENUL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
