-- 공통 게시판 시드 데이터
ALTER SESSION SET CURRENT_SCHEMA = ITPAPP;

-- 게시판 유형 공통코드 (BLB_TP)
-- CTT_TP: 코드값구분(그룹), C_ID: 코드ID, C_NM: 코드명, C_SQN: 코드순서, STT_DT: 시작일자(PK)
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('BLB_TP_001', '공지사항', 'BLB_TP', 1, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('BLB_TP_002', '자료실',   'BLB_TP', 2, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 중요도 공통코드 (PRIT_C)
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C_001', '일반', 'PRIT_C', 1, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C_002', '중요', 'PRIT_C', 2, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('PRIT_C_003', '긴급', 'PRIT_C', 3, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 게시물 유형 공통코드 (NAC_TP)
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP_001', '작업예정', 'NAC_TP', 1, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP_002', '작업완료', 'NAC_TP', 2, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');
INSERT INTO TAAABB_CCODEM (C_ID, C_NM, CTT_TP, C_SQN, STT_DT, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID)
VALUES ('NAC_TP_003', '교육자료', 'NAC_TP', 3, DATE '2026-01-01', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM');

-- 게시판 메타 시드: 공지사항
INSERT INTO TAAABB_CBLBMM (
    BLB_MNG_NO, BLB_NM, BLB_TP,
    REP_USE_YN, CMMT_USE_YN, FL_ESN_YN, HRK_FXN_USE_YN, NAC_TP_USE_YN, KD_USE_YN,
    INQ_ATH_C, ENR_ATH_C, BBR_LMTN_USE_YN,
    SRE_SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID
) VALUES (
    'BLBM-2026-0001', '공지사항', 'BLB_TP_001',
    'N', 'N', 'N', 'Y', 'N', 'N',
    'ALL', 'ROLE_ADMIN', 'N',
    1, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM'
);

-- 게시판 메타 시드: 자료실
INSERT INTO TAAABB_CBLBMM (
    BLB_MNG_NO, BLB_NM, BLB_TP,
    REP_USE_YN, CMMT_USE_YN, FL_ESN_YN, HRK_FXN_USE_YN, NAC_TP_USE_YN, KD_USE_YN,
    INQ_ATH_C, ENR_ATH_C, BBR_LMTN_USE_YN,
    SRE_SQN_NO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID
) VALUES (
    'BLBM-2026-0002', '자료실', 'BLB_TP_002',
    'N', 'Y', 'Y', 'N', 'N', 'Y',
    'ALL', 'ALL', 'N',
    2, 'Y', 'N', SYS_GUID(), 1, SYSDATE, 'SYSTEM'
);

COMMIT;
