-- ============================================================
-- 타입만 변환 (DATE -> VARCHAR2(8), 값 YYYYMMDD 변환)
-- 생성: _generate_rename.py (보고서 기반, 멱등). 직접 수정 금지.
-- ============================================================

-- TPRMPP_BCOSTL: FST_DFR_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BCOSTL' AND column_name='FST_DFR_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BCOSTL ADD (FST_DFR_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BCOSTL SET FST_DFR_DT_TMP=TO_CHAR(FST_DFR_DT,'YYYYMMDD') WHERE FST_DFR_DT IS NOT NULL AND FST_DFR_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BCOSTL DROP COLUMN FST_DFR_DT;
ALTER TABLE TPRMPP_BCOSTL RENAME COLUMN FST_DFR_DT_TMP TO FST_DFR_DT;

-- TPRMPP_BCOSTL: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BCOSTL' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BCOSTL ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BCOSTL SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BCOSTL DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BCOSTL RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

-- TPRMPP_BCOSTM: FST_DFR_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BCOSTM' AND column_name='FST_DFR_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BCOSTM ADD (FST_DFR_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BCOSTM SET FST_DFR_DT_TMP=TO_CHAR(FST_DFR_DT,'YYYYMMDD') WHERE FST_DFR_DT IS NOT NULL AND FST_DFR_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BCOSTM DROP COLUMN FST_DFR_DT;
ALTER TABLE TPRMPP_BCOSTM RENAME COLUMN FST_DFR_DT_TMP TO FST_DFR_DT;

-- TPRMPP_BCOSTM: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BCOSTM' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BCOSTM ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BCOSTM SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BCOSTM DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BCOSTM RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

-- TPRMPP_BITEML: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BITEML' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEML ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BITEML SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BITEML DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BITEML RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

-- TPRMPP_BITEMM: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BITEMM' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BITEMM ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BITEMM SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BITEMM DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BITEMM RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

-- TPRMPP_BTERML: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BTERML' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERML ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BTERML SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BTERML DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BTERML RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

-- TPRMPP_BTERMM: XCR_BSE_DT DATE -> VARCHAR2(8)
DECLARE has_tmp NUMBER; BEGIN
  SELECT COUNT(*) INTO has_tmp FROM user_tab_columns WHERE table_name='TPRMPP_BTERMM' AND column_name='XCR_BSE_DT_TMP';
  IF has_tmp=0 THEN EXECUTE IMMEDIATE 'ALTER TABLE TPRMPP_BTERMM ADD (XCR_BSE_DT_TMP VARCHAR2(8 CHAR))'; END IF;
END;
/
UPDATE TPRMPP_BTERMM SET XCR_BSE_DT_TMP=TO_CHAR(XCR_BSE_DT,'YYYYMMDD') WHERE XCR_BSE_DT IS NOT NULL AND XCR_BSE_DT_TMP IS NULL;
ALTER TABLE TPRMPP_BTERMM DROP COLUMN XCR_BSE_DT;
ALTER TABLE TPRMPP_BTERMM RENAME COLUMN XCR_BSE_DT_TMP TO XCR_BSE_DT;

COMMIT;
