-- 입찰계약 마스터(BCONTM, 명세 없음) + 변경로그(BCONTL) + 시퀀스.
CREATE TABLE TPRMPP_BCONTM (
  DOC_MNG_NO     VARCHAR2(20 CHAR)  NOT NULL,
  DOC_VRS_SNO    NUMBER(9,0)        NOT NULL,
  LST_YN         VARCHAR2(1 CHAR)   DEFAULT 'Y' NOT NULL,
  BG_PRN_TC      VARCHAR2(3 CHAR)   NOT NULL,
  CNCD_RFR_NO    VARCHAR2(30 CHAR)  NOT NULL,
  IT_PTL_STS_TC  VARCHAR2(2 CHAR)   NOT NULL,
  REQ_CONE       VARCHAR2(300 CHAR),
  CTT_MANR_C     VARCHAR2(2 CHAR),
  CTT_MANR_RSN   VARCHAR2(1000 CHAR),
  CTT_NM         VARCHAR2(100 CHAR),
  CTT_AMT        NUMBER(18,3),
  CTT_OPP_NM     VARCHAR2(100 CHAR),
  CTT_DT         VARCHAR2(8 CHAR),
  DEL_YN         VARCHAR2(1 CHAR)   DEFAULT 'N' NOT NULL,
  GUID           VARCHAR2(38 CHAR),
  GUID_PRG_SNO   NUMBER(4,0),
  FST_ENR_DTM    DATE,
  FST_ENR_USID   VARCHAR2(14 CHAR),
  LST_CHG_DTM    DATE,
  LST_CHG_USID   VARCHAR2(14 CHAR),
  CONSTRAINT PK_TPRMPP_BCONTM PRIMARY KEY (DOC_MNG_NO, DOC_VRS_SNO),
  CONSTRAINT CK_BCONTM_LST_YN CHECK (LST_YN IN ('Y','N')),
  CONSTRAINT CK_BCONTM_DEL_YN CHECK (DEL_YN IN ('Y','N'))
);
COMMENT ON TABLE  TPRMPP_BCONTM                IS '입찰계약 기본';
COMMENT ON COLUMN TPRMPP_BCONTM.DOC_MNG_NO     IS '문서관리번호';
COMMENT ON COLUMN TPRMPP_BCONTM.DOC_VRS_SNO    IS '문서버전일련번호';
COMMENT ON COLUMN TPRMPP_BCONTM.LST_YN         IS '최종여부';
COMMENT ON COLUMN TPRMPP_BCONTM.BG_PRN_TC      IS '예산성격구분코드(대상구분)';
COMMENT ON COLUMN TPRMPP_BCONTM.CNCD_RFR_NO    IS '관련참조번호(대상관리번호)';
COMMENT ON COLUMN TPRMPP_BCONTM.IT_PTL_STS_TC  IS 'IT포탈상태구분코드';
COMMENT ON COLUMN TPRMPP_BCONTM.REQ_CONE       IS '요청내용';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_MANR_C     IS '계약방법코드';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_MANR_RSN   IS '계약방법사유';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_NM         IS '계약명';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_AMT        IS '계약금액';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_OPP_NM     IS '계약상대처명';
COMMENT ON COLUMN TPRMPP_BCONTM.CTT_DT         IS '계약일자';
COMMENT ON COLUMN TPRMPP_BCONTM.DEL_YN         IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BCONTM.GUID           IS 'GUID';
COMMENT ON COLUMN TPRMPP_BCONTM.GUID_PRG_SNO   IS 'GUID프로그램일련번호';
COMMENT ON COLUMN TPRMPP_BCONTM.FST_ENR_DTM    IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BCONTM.FST_ENR_USID   IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BCONTM.LST_CHG_DTM    IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BCONTM.LST_CHG_USID   IS '최종변경사용자ID';
CREATE INDEX IDX_BCONTM_TGT ON TPRMPP_BCONTM (BG_PRN_TC, CNCD_RFR_NO);
CREATE INDEX IDX_BCONTM_STS ON TPRMPP_BCONTM (IT_PTL_STS_TC);

CREATE TABLE TPRMPP_BCONTL (
  LOG_HIS_TGR_SNO NUMBER(18,0)       NOT NULL,
  CHG_DTT_YN      VARCHAR2(1 CHAR),
  CHG_DTM         TIMESTAMP(9),
  CHG_USID        VARCHAR2(14 CHAR),
  DEL_YN          VARCHAR2(1 CHAR),
  GUID            VARCHAR2(38 CHAR),
  GUID_PRG_SNO    NUMBER(4,0),
  FST_ENR_DTM     DATE,
  FST_ENR_USID    VARCHAR2(14 CHAR),
  LST_CHG_DTM     DATE,
  LST_CHG_USID    VARCHAR2(14 CHAR),
  DOC_MNG_NO      VARCHAR2(20 CHAR),
  DOC_VRS_SNO     NUMBER(9,0),
  LST_YN          VARCHAR2(1 CHAR),
  BG_PRN_TC       VARCHAR2(3 CHAR),
  CNCD_RFR_NO     VARCHAR2(30 CHAR),
  IT_PTL_STS_TC   VARCHAR2(2 CHAR),
  REQ_CONE        VARCHAR2(300 CHAR),
  CTT_MANR_C      VARCHAR2(2 CHAR),
  CTT_MANR_RSN    VARCHAR2(1000 CHAR),
  CTT_NM          VARCHAR2(100 CHAR),
  CTT_AMT         NUMBER(18,3),
  CTT_OPP_NM      VARCHAR2(100 CHAR),
  CTT_DT          VARCHAR2(8 CHAR),
  CONSTRAINT PK_TPRMPP_BCONTL PRIMARY KEY (LOG_HIS_TGR_SNO)
);
COMMENT ON TABLE  TPRMPP_BCONTL                  IS '입찰계약 기본 변경 로그';
COMMENT ON COLUMN TPRMPP_BCONTL.LOG_HIS_TGR_SNO IS '로그이력대상일련번호';
COMMENT ON COLUMN TPRMPP_BCONTL.CHG_DTT_YN      IS '변경상세여부';
COMMENT ON COLUMN TPRMPP_BCONTL.CHG_DTM         IS '변경일시';
COMMENT ON COLUMN TPRMPP_BCONTL.CHG_USID        IS '변경사용자ID';

CREATE SEQUENCE SEQ_BCONTM START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BCONTL START WITH 1 INCREMENT BY 1 CACHE 20 NOCYCLE;
