-- ============================================================
-- 20 테이블 DDL — K230028 작업분 (council 도메인)
-- 추출: 2026-05-28 03:56
-- 적용: SQL*Plus에서 @01_tables_ddl.sql
-- ============================================================


  CREATE TABLE "TPRMPP_BASCTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_STS_C" VARCHAR2(3 CHAR) NOT NULL ENABLE,
	"CNRC_DT" VARCHAR2(8 CHAR),
	"CNRC_PLC_NM" VARCHAR2(100 CHAR),
	"CNRC_TM" VARCHAR2(6 CHAR),
	"DBR_TC" VARCHAR2(20 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BASCTM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BCHKLM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_ITM_C" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"CKG_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCHKLM" PRIMARY KEY ("ASCT_ID", "CKG_ITM_C")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BCMMTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CNFM_YN" VARCHAR2(1 CHAR) NOT NULL ENABLE,
	"VLR_TC" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCMMTM" PRIMARY KEY ("ASCT_ID", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BEVALM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_ITM_C" VARCHAR2(20 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_OPNN_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BEVALM" PRIMARY KEY ("ASCT_ID", "CKG_ITM_C", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BMQNAM"
   (	"QTN_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BMQNAM" PRIMARY KEY ("QTN_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPERFM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DTP_SNO" NUMBER(10,0) NOT NULL ENABLE,
	"CLF" VARCHAR2(255 CHAR),
	"DTP_CONE" VARCHAR2(2000 CHAR),
	"DTP_NM" VARCHAR2(255 CHAR),
	"GL_NV_CONE" VARCHAR2(300 CHAR),
	"MSM_CLE" VARCHAR2(100 CHAR),
	"MSM_END_DT" VARCHAR2(8 CHAR),
	"MSM_MANR_CONE" VARCHAR2(2000 CHAR),
	"MSM_PTM_CONE" VARCHAR2(100 CHAR),
	"MSM_STT_DT" VARCHAR2(8 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPERFM" PRIMARY KEY ("ASCT_ID", "DTP_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPOVWM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"EDRT_NM" VARCHAR2(100 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"KPN_TC" VARCHAR2(10 CHAR),
	"LGL_RGL_NM" VARCHAR2(255 CHAR),
	"LGL_RGL_YN" VARCHAR2(1 CHAR),
	"NCS_CONE" VARCHAR2(2000 CHAR),
	"PRJ_BG_AMT" NUMBER(18,3),
	"PRJ_DES" VARCHAR2(300 CHAR),
	"PRJ_NM" VARCHAR2(255 CHAR),
	"PRJ_TRM_CONE" VARCHAR2(100 CHAR),
	"XPT_EFF_CONE" VARCHAR2(2000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPOVWM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPQNAM"
   (	"QTN_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPQNAM" PRIMARY KEY ("QTN_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BRSLTM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"CKG_OPNN_CONE" VARCHAR2(4000 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"SYN_OPNN_CONE" VARCHAR2(4000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BRSLTM" PRIMARY KEY ("ASCT_ID")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BSCHDM"
   (	"ASCT_ID" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"DSD_DT" VARCHAR2(8 CHAR) NOT NULL ENABLE,
	"DSD_TM" VARCHAR2(6 CHAR) NOT NULL ENABLE,
	"ENO" VARCHAR2(32 CHAR) NOT NULL ENABLE,
	"PSB_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BSCHDM" PRIMARY KEY ("ASCT_ID", "DSD_DT", "DSD_TM", "ENO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BASCTL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"ASCT_STS_C" VARCHAR2(3 CHAR),
	"CNRC_DT" VARCHAR2(8 CHAR),
	"CNRC_PLC_NM" VARCHAR2(100 CHAR),
	"CNRC_TM" VARCHAR2(6 CHAR),
	"DBR_TC" VARCHAR2(20 CHAR),
	"PRJ_MNG_NO" VARCHAR2(32 CHAR),
	"PRJ_SNO" NUMBER(10,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BASCTL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BCHKLL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_ITM_C" VARCHAR2(20 CHAR),
	"CKG_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCHKLL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BCMMTL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"VLR_TC" VARCHAR2(32 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BCMMTL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BEVALL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_ITM_C" VARCHAR2(20 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"CKG_OPNN_CONE" VARCHAR2(2000 CHAR),
	"CKG_RCRD" NUMBER(5,0),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BEVALL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BMQNAL"
   (	"LOG_SNO" NUMBER(19,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"QTN_ID" VARCHAR2(32 CHAR),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BMQNAL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPERFL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"DTP_SNO" NUMBER(10,0),
	"CLF" VARCHAR2(255 CHAR),
	"DTP_CONE" VARCHAR2(2000 CHAR),
	"DTP_NM" VARCHAR2(255 CHAR),
	"GL_NV_CONE" VARCHAR2(300 CHAR),
	"MSM_CLE" VARCHAR2(100 CHAR),
	"MSM_END_DT" VARCHAR2(8 CHAR),
	"MSM_MANR_CONE" VARCHAR2(2000 CHAR),
	"MSM_PTM_CONE" VARCHAR2(100 CHAR),
	"MSM_STT_DT" VARCHAR2(8 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPERFL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPOVWL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"EDRT_NM" VARCHAR2(100 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"KPN_TC" VARCHAR2(10 CHAR),
	"LGL_RGL_NM" VARCHAR2(255 CHAR),
	"LGL_RGL_YN" VARCHAR2(1 CHAR),
	"NCS_CONE" VARCHAR2(2000 CHAR),
	"PRJ_BG_AMT" NUMBER(18,3),
	"PRJ_DES" VARCHAR2(300 CHAR),
	"PRJ_NM" VARCHAR2(255 CHAR),
	"PRJ_TRM_CONE" VARCHAR2(100 CHAR),
	"XPT_EFF_CONE" VARCHAR2(2000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPOVWL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BPQNAL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"QTN_ID" VARCHAR2(32 CHAR),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"QTN_CONE" VARCHAR2(4000 CHAR),
	"QTN_USID" VARCHAR2(14),
	"REP_CONE" VARCHAR2(4000 CHAR),
	"REP_USID" VARCHAR2(14),
	"REP_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BPQNAL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BRSLTL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"CKG_OPNN_CONE" VARCHAR2(4000 CHAR),
	"FL_MNG_NO" VARCHAR2(32 CHAR),
	"SYN_OPNN_CONE" VARCHAR2(4000 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BRSLTL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;


  CREATE TABLE "TPRMPP_BSCHDL"
   (	"LOG_SNO" NUMBER(22,0) NOT NULL ENABLE,
	"CHG_TP" VARCHAR2(1) NOT NULL ENABLE,
	"CHG_DTM" DATE NOT NULL ENABLE,
	"CHG_USID" VARCHAR2(14),
	"ASCT_ID" VARCHAR2(32 CHAR),
	"DSD_DT" VARCHAR2(8 CHAR),
	"DSD_TM" VARCHAR2(6 CHAR),
	"ENO" VARCHAR2(32 CHAR),
	"PSB_YN" VARCHAR2(1 CHAR),
	"DEL_YN" VARCHAR2(1),
	"GUID" VARCHAR2(38),
	"GUID_PRG_SNO" NUMBER(4,0),
	"FST_ENR_USID" VARCHAR2(14),
	"FST_ENR_DTM" DATE,
	"LST_CHG_USID" VARCHAR2(14),
	"LST_CHG_DTM" DATE,
	 CONSTRAINT "PK_BSCHDL" PRIMARY KEY ("LOG_SNO")
  USING INDEX  ENABLE
   ) ;

COMMENT ON TABLE TPRMPP_BASCTL IS '정보화실무협의회 기본정보 변경 로그';
COMMENT ON TABLE TPRMPP_BASCTM IS '정보화실무협의회 기본정보';
COMMENT ON TABLE TPRMPP_BCHKLL IS '타당성 자체점검 변경 로그';
COMMENT ON TABLE TPRMPP_BCHKLM IS '타당성 자체점검';
COMMENT ON TABLE TPRMPP_BCMMTL IS '협의회 평가위원 변경 로그';
COMMENT ON TABLE TPRMPP_BCMMTM IS '협의회 평가위원';
COMMENT ON TABLE TPRMPP_BEVALL IS '평가위원 평가의견 변경 로그';
COMMENT ON TABLE TPRMPP_BEVALM IS '평가위원 평가의견';
COMMENT ON TABLE TPRMPP_BMQNAL IS '본회의질의응답 변경 로그';
COMMENT ON TABLE TPRMPP_BMQNAM IS '본회의질의응답';
COMMENT ON TABLE TPRMPP_BPERFL IS '성과관리 자체계획 변경 로그';
COMMENT ON TABLE TPRMPP_BPERFM IS '성과관리 자체계획(성과지표)';
COMMENT ON TABLE TPRMPP_BPOVWL IS '협의회 사업개요 변경 로그';
COMMENT ON TABLE TPRMPP_BPOVWM IS '협의회 사업개요';
COMMENT ON TABLE TPRMPP_BPQNAL IS '사전질의응답 변경 로그';
COMMENT ON TABLE TPRMPP_BPQNAM IS '사전질의응답';
COMMENT ON TABLE TPRMPP_BRSLTL IS '협의회 결과서 변경 로그';
COMMENT ON TABLE TPRMPP_BRSLTM IS '협의회 결과서';
COMMENT ON TABLE TPRMPP_BSCHDL IS '협의회 일정 변경 로그';
COMMENT ON TABLE TPRMPP_BSCHDM IS '협의회 일정';
COMMENT ON COLUMN TPRMPP_BASCTL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BASCTL.ASCT_STS_C IS '협의회상태코드';
COMMENT ON COLUMN TPRMPP_BASCTL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BASCTL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BASCTL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BASCTL.CNRC_DT IS '회의일자';
COMMENT ON COLUMN TPRMPP_BASCTL.CNRC_PLC_NM IS '회의장소명';
COMMENT ON COLUMN TPRMPP_BASCTL.CNRC_TM IS '회의시간';
COMMENT ON COLUMN TPRMPP_BASCTL.DBR_TC IS '심의유형코드';
COMMENT ON COLUMN TPRMPP_BASCTL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BASCTL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BASCTL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BASCTL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BASCTL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BASCTL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BASCTL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BASCTL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BASCTL.PRJ_MNG_NO IS '프로젝트관리번호';
COMMENT ON COLUMN TPRMPP_BASCTL.PRJ_SNO IS '프로젝트순번';
COMMENT ON COLUMN TPRMPP_BASCTM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BASCTM.ASCT_STS_C IS '협의회상태코드';
COMMENT ON COLUMN TPRMPP_BASCTM.CNRC_DT IS '회의일자';
COMMENT ON COLUMN TPRMPP_BASCTM.CNRC_PLC_NM IS '회의장소명';
COMMENT ON COLUMN TPRMPP_BASCTM.CNRC_TM IS '회의시간';
COMMENT ON COLUMN TPRMPP_BASCTM.DBR_TC IS '심의유형코드';
COMMENT ON COLUMN TPRMPP_BASCTM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BASCTM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BASCTM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BASCTM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BASCTM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BASCTM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BASCTM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BASCTM.PRJ_MNG_NO IS '프로젝트관리번호';
COMMENT ON COLUMN TPRMPP_BASCTM.PRJ_SNO IS '프로젝트순번';
COMMENT ON COLUMN TPRMPP_BCHKLL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BCHKLL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BCHKLL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BCHKLL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BCHKLL.CKG_CONE IS '점검내용';
COMMENT ON COLUMN TPRMPP_BCHKLL.CKG_ITM_C IS '점검항목코드';
COMMENT ON COLUMN TPRMPP_BCHKLL.CKG_RCRD IS '점검점수';
COMMENT ON COLUMN TPRMPP_BCHKLL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BCHKLL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BCHKLL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BCHKLL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BCHKLL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BCHKLL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BCHKLL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BCHKLL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BCHKLM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BCHKLM.CKG_CONE IS '점검내용';
COMMENT ON COLUMN TPRMPP_BCHKLM.CKG_ITM_C IS '점검항목코드';
COMMENT ON COLUMN TPRMPP_BCHKLM.CKG_RCRD IS '점검점수';
COMMENT ON COLUMN TPRMPP_BCHKLM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BCHKLM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BCHKLM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BCHKLM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BCHKLM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BCHKLM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BCHKLM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BCMMTL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BCMMTL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BCMMTL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BCMMTL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BCMMTL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BCMMTL.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BCMMTL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BCMMTL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BCMMTL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BCMMTL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BCMMTL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BCMMTL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BCMMTL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BCMMTM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BCMMTM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BCMMTM.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BCMMTM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BCMMTM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BCMMTM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BCMMTM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BCMMTM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BCMMTM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BEVALL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BEVALL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BEVALL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BEVALL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BEVALL.CKG_ITM_C IS '점검항목코드';
COMMENT ON COLUMN TPRMPP_BEVALL.CKG_OPNN_CONE IS '점검의견내용';
COMMENT ON COLUMN TPRMPP_BEVALL.CKG_RCRD IS '점검점수';
COMMENT ON COLUMN TPRMPP_BEVALL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BEVALL.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BEVALL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BEVALL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BEVALL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BEVALL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BEVALL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BEVALL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BEVALL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BEVALM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BEVALM.CKG_ITM_C IS '점검항목코드';
COMMENT ON COLUMN TPRMPP_BEVALM.CKG_OPNN_CONE IS '점검의견내용';
COMMENT ON COLUMN TPRMPP_BEVALM.CKG_RCRD IS '점검점수';
COMMENT ON COLUMN TPRMPP_BEVALM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BEVALM.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BEVALM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BEVALM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BEVALM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BEVALM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BEVALM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BEVALM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BMQNAL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BMQNAL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BMQNAL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BMQNAL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BMQNAL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BMQNAL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BMQNAL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BMQNAL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.QTN_CONE IS '질의내용';
COMMENT ON COLUMN TPRMPP_BMQNAL.QTN_ID IS '질의응답ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.QTN_USID IS '질의사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.REP_CONE IS '답변내용';
COMMENT ON COLUMN TPRMPP_BMQNAL.REP_USID IS '답변사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAL.REP_YN IS '답변여부';
COMMENT ON COLUMN TPRMPP_BMQNAM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BMQNAM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BMQNAM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BMQNAM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BMQNAM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BMQNAM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.QTN_CONE IS '질의내용';
COMMENT ON COLUMN TPRMPP_BMQNAM.QTN_ID IS '질의응답ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.QTN_USID IS '질의사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.REP_CONE IS '답변내용';
COMMENT ON COLUMN TPRMPP_BMQNAM.REP_USID IS '답변사용자ID';
COMMENT ON COLUMN TPRMPP_BMQNAM.REP_YN IS '답변여부';
COMMENT ON COLUMN TPRMPP_BPERFL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPERFL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BPERFL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BPERFL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPERFL.CLF IS '산식';
COMMENT ON COLUMN TPRMPP_BPERFL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPERFL.DTP_CONE IS '성과지표정의';
COMMENT ON COLUMN TPRMPP_BPERFL.DTP_NM IS '성과지표명';
COMMENT ON COLUMN TPRMPP_BPERFL.DTP_SNO IS '지표일련번호';
COMMENT ON COLUMN TPRMPP_BPERFL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPERFL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPERFL.GL_NV_CONE IS '목표수치내용';
COMMENT ON COLUMN TPRMPP_BPERFL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPERFL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPERFL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BPERFL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPERFL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPERFL.MSM_CLE IS '측정주기';
COMMENT ON COLUMN TPRMPP_BPERFL.MSM_END_DT IS '측정종료일';
COMMENT ON COLUMN TPRMPP_BPERFL.MSM_MANR_CONE IS '측정방법내용';
COMMENT ON COLUMN TPRMPP_BPERFL.MSM_PTM_CONE IS '측정시점내용';
COMMENT ON COLUMN TPRMPP_BPERFL.MSM_STT_DT IS '측정시작일';
COMMENT ON COLUMN TPRMPP_BPERFM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPERFM.CLF IS '산식';
COMMENT ON COLUMN TPRMPP_BPERFM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPERFM.DTP_CONE IS '성과지표정의';
COMMENT ON COLUMN TPRMPP_BPERFM.DTP_NM IS '성과지표명';
COMMENT ON COLUMN TPRMPP_BPERFM.DTP_SNO IS '지표일련번호';
COMMENT ON COLUMN TPRMPP_BPERFM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPERFM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPERFM.GL_NV_CONE IS '목표수치내용';
COMMENT ON COLUMN TPRMPP_BPERFM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPERFM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPERFM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPERFM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPERFM.MSM_CLE IS '측정주기';
COMMENT ON COLUMN TPRMPP_BPERFM.MSM_END_DT IS '측정종료일';
COMMENT ON COLUMN TPRMPP_BPERFM.MSM_MANR_CONE IS '측정방법내용';
COMMENT ON COLUMN TPRMPP_BPERFM.MSM_PTM_CONE IS '측정시점내용';
COMMENT ON COLUMN TPRMPP_BPERFM.MSM_STT_DT IS '측정시작일';
COMMENT ON COLUMN TPRMPP_BPOVWL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPOVWL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BPOVWL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BPOVWL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPOVWL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPOVWL.EDRT_NM IS '전결권명';
COMMENT ON COLUMN TPRMPP_BPOVWL.FL_MNG_NO IS '첨부파일관리번호';
COMMENT ON COLUMN TPRMPP_BPOVWL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPOVWL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPOVWL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPOVWL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPOVWL.KPN_TC IS '저장구분코드';
COMMENT ON COLUMN TPRMPP_BPOVWL.LGL_RGL_NM IS '법률규제명';
COMMENT ON COLUMN TPRMPP_BPOVWL.LGL_RGL_YN IS '법률규제여부';
COMMENT ON COLUMN TPRMPP_BPOVWL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BPOVWL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPOVWL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPOVWL.NCS_CONE IS '필요성내용';
COMMENT ON COLUMN TPRMPP_BPOVWL.PRJ_BG_AMT IS '프로젝트예산금액';
COMMENT ON COLUMN TPRMPP_BPOVWL.PRJ_DES IS '프로젝트설명';
COMMENT ON COLUMN TPRMPP_BPOVWL.PRJ_NM IS '프로젝트명';
COMMENT ON COLUMN TPRMPP_BPOVWL.PRJ_TRM_CONE IS '프로젝트기간내용';
COMMENT ON COLUMN TPRMPP_BPOVWL.XPT_EFF_CONE IS '기대효과내용';
COMMENT ON COLUMN TPRMPP_BPOVWM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPOVWM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPOVWM.EDRT_NM IS '전결권명';
COMMENT ON COLUMN TPRMPP_BPOVWM.FL_MNG_NO IS '첨부파일관리번호';
COMMENT ON COLUMN TPRMPP_BPOVWM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPOVWM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPOVWM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPOVWM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPOVWM.KPN_TC IS '저장구분코드';
COMMENT ON COLUMN TPRMPP_BPOVWM.LGL_RGL_NM IS '법률규제명';
COMMENT ON COLUMN TPRMPP_BPOVWM.LGL_RGL_YN IS '법률규제여부';
COMMENT ON COLUMN TPRMPP_BPOVWM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPOVWM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPOVWM.NCS_CONE IS '필요성내용';
COMMENT ON COLUMN TPRMPP_BPOVWM.PRJ_BG_AMT IS '프로젝트예산금액';
COMMENT ON COLUMN TPRMPP_BPOVWM.PRJ_DES IS '프로젝트설명';
COMMENT ON COLUMN TPRMPP_BPOVWM.PRJ_NM IS '프로젝트명';
COMMENT ON COLUMN TPRMPP_BPOVWM.PRJ_TRM_CONE IS '프로젝트기간내용';
COMMENT ON COLUMN TPRMPP_BPOVWM.XPT_EFF_CONE IS '기대효과내용';
COMMENT ON COLUMN TPRMPP_BPQNAL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BPQNAL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BPQNAL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPQNAL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPQNAL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPQNAL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPQNAL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BPQNAL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPQNAL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.QTN_CONE IS '질의내용';
COMMENT ON COLUMN TPRMPP_BPQNAL.QTN_ID IS '질의응답ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.QTN_USID IS '질의사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.REP_CONE IS '답변내용';
COMMENT ON COLUMN TPRMPP_BPQNAL.REP_USID IS '답변사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAL.REP_YN IS '답변여부';
COMMENT ON COLUMN TPRMPP_BPQNAM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BPQNAM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BPQNAM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BPQNAM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BPQNAM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BPQNAM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.QTN_CONE IS '질의내용';
COMMENT ON COLUMN TPRMPP_BPQNAM.QTN_ID IS '질의응답ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.QTN_USID IS '질의사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.REP_CONE IS '답변내용';
COMMENT ON COLUMN TPRMPP_BPQNAM.REP_USID IS '답변사용자ID';
COMMENT ON COLUMN TPRMPP_BPQNAM.REP_YN IS '답변여부';
COMMENT ON COLUMN TPRMPP_BRSLTL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BRSLTL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BRSLTL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BRSLTL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BRSLTL.CKG_OPNN_CONE IS '점검의견내용';
COMMENT ON COLUMN TPRMPP_BRSLTL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BRSLTL.FL_MNG_NO IS '관련자료 첨부파일관리번호';
COMMENT ON COLUMN TPRMPP_BRSLTL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BRSLTL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BRSLTL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BRSLTL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BRSLTL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BRSLTL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BRSLTL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BRSLTL.SYN_OPNN_CONE IS '종합의견내용';
COMMENT ON COLUMN TPRMPP_BRSLTM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BRSLTM.CKG_OPNN_CONE IS '점검의견내용';
COMMENT ON COLUMN TPRMPP_BRSLTM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BRSLTM.FL_MNG_NO IS '관련자료 첨부파일관리번호';
COMMENT ON COLUMN TPRMPP_BRSLTM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BRSLTM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BRSLTM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BRSLTM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BRSLTM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BRSLTM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BRSLTM.SYN_OPNN_CONE IS '종합의견내용';
COMMENT ON COLUMN TPRMPP_BSCHDL.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BSCHDL.CHG_DTM IS '변경일시';
COMMENT ON COLUMN TPRMPP_BSCHDL.CHG_TP IS '변경유형';
COMMENT ON COLUMN TPRMPP_BSCHDL.CHG_USID IS '변경사용자ID';
COMMENT ON COLUMN TPRMPP_BSCHDL.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BSCHDL.DSD_DT IS '일정일자';
COMMENT ON COLUMN TPRMPP_BSCHDL.DSD_TM IS '일정시간';
COMMENT ON COLUMN TPRMPP_BSCHDL.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BSCHDL.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BSCHDL.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BSCHDL.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BSCHDL.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BSCHDL.LOG_SNO IS '로그일련번호';
COMMENT ON COLUMN TPRMPP_BSCHDL.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BSCHDL.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BSCHDL.PSB_YN IS '가능여부';
COMMENT ON COLUMN TPRMPP_BSCHDM.ASCT_ID IS '협의회ID';
COMMENT ON COLUMN TPRMPP_BSCHDM.DEL_YN IS '삭제여부';
COMMENT ON COLUMN TPRMPP_BSCHDM.DSD_DT IS '일정일자';
COMMENT ON COLUMN TPRMPP_BSCHDM.DSD_TM IS '일정시간';
COMMENT ON COLUMN TPRMPP_BSCHDM.ENO IS '사번';
COMMENT ON COLUMN TPRMPP_BSCHDM.FST_ENR_DTM IS '최초등록일시';
COMMENT ON COLUMN TPRMPP_BSCHDM.FST_ENR_USID IS '최초등록사용자ID';
COMMENT ON COLUMN TPRMPP_BSCHDM.GUID IS 'GUID';
COMMENT ON COLUMN TPRMPP_BSCHDM.GUID_PRG_SNO IS 'GUID진행일련번호';
COMMENT ON COLUMN TPRMPP_BSCHDM.LST_CHG_DTM IS '최종변경일시';
COMMENT ON COLUMN TPRMPP_BSCHDM.LST_CHG_USID IS '최종변경사용자ID';
COMMENT ON COLUMN TPRMPP_BSCHDM.PSB_YN IS '가능여부';