-- ============================================================
-- 정보화실무협의회 테스트 사용자 데이터
-- 대상 테이블: TPRMPP_CORGNI, TPRMPP_CUSERI, TPRMPP_CROLEI
-- 비밀번호: 1q2w3e4r! (SHA-256 + Base64)
-- 해시값: /r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=
--
-- [팀코드 확정값]
--   - 미래전략팀:  BBR_C=140(미래전략개발부), TEM_C=14011
--   - 조직·평가팀: BBR_C=120(종합기획부),    TEM_C=12003
-- ============================================================

-- ── TPRMPP_CORGNI: 부점정보 (없으면 INSERT, 있으면 무시) ─────────────────

MERGE INTO TPRMPP_CORGNI T
USING (SELECT '180' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('180', 'IT기획부', 'IT Planning', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CORGNI T
USING (SELECT '182' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('182', '디지털금융부', 'Digital Finance', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CORGNI T
USING (SELECT '120' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('120', '종합기획부', 'General Planning', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CORGNI T
USING (SELECT '183' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('183', '정보보호기획부', 'Information Security', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CORGNI T
USING (SELECT '185' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('185', 'AI·디지털전략부', 'AI Digital Strategy', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

-- 미래전략개발부 (BBR_C=140)
MERGE INTO TPRMPP_CORGNI T
USING (SELECT '140' AS PRLM_OGZ_C_CONE FROM DUAL) S
ON (T.PRLM_OGZ_C_CONE = S.PRLM_OGZ_C_CONE)
WHEN NOT MATCHED THEN
    INSERT (PRLM_OGZ_C_CONE, BBR_NM, BBR_WREN_NM, ITM_SQN_SNO, PRLM_HRK_OGZ_C_CONE, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('140', '미래전략개발부', 'Future Strategy', '1', '013', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');


-- ── TPRMPP_CUSERI: 존재하면 UPDATE, 없으면 INSERT ─────────────────────────
-- 총 14개 계정 (ENO 기준)

-- [1] IT기획팀 대리 (K230028)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230028' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '180',
        PT_C_NM      = '대리',
        TEM_C        = '18001',
        TEM_NM       = 'IT기획팀',
        USR_NM       = '김영수',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230028'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230028', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '180', '대리', '18001', 'IT기획팀', '김영수', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

-- [2] IT기획팀 팀장 (K000001)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K000001' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '180',
        PT_C_NM      = '팀장',
        TEM_C        = '18001',
        TEM_NM       = 'IT기획팀',
        USR_NM       = '김기획팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K000001'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K000001', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '180', '팀장', '18001', 'IT기획팀', '김기획팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K000001', SYSTIMESTAMP, 'K000001');

-- [3] IT기획부 부장 (K230033)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230033' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '180',
        PT_C_NM      = '부장',
        TEM_C        = '18000',
        TEM_NM       = 'IT기획부',
        USR_NM       = '김기획부장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230033'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230033', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '180', '부장', '18000', 'IT기획부', '김기획부장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230033', SYSTIMESTAMP, 'K230033');

-- [4] 예산팀 팀장 (K230030)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230030' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '120',
        PT_C_NM      = '팀장',
        TEM_C        = '12004',
        TEM_NM       = '예산팀',
        USR_NM       = '김예산팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230030'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230030', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '120', '팀장', '12004', '예산팀', '김예산팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230030', SYSTIMESTAMP, 'K230030');

-- [5] 지식정보팀 대리 (K230032)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230032' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '182',
        PT_C_NM      = '대리',
        TEM_C        = '18201',
        TEM_NM       = '지식정보팀',
        USR_NM       = '김지정',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230032'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230032', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '182', '대리', '18201', '지식정보팀', '김지정', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230032', SYSTIMESTAMP, 'K230032');

-- [6] 지식정보팀 팀장 (K230031)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230031' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '182',
        PT_C_NM      = '팀장',
        TEM_C        = '18201',
        TEM_NM       = '지식정보팀',
        USR_NM       = '김지정팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230031'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230031', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '182', '팀장', '18201', '지식정보팀', '김지정팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230031', SYSTIMESTAMP, 'K230031');

-- [7] 디지털금융부 부장 (K230029)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230029' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '182',
        PT_C_NM      = '부장',
        TEM_C        = '18200',
        TEM_NM       = '디지털금융부',
        USR_NM       = '김디금부장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230029'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230029', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '182', '부장', '18200', '디지털금융부', '김디금부장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230029', SYSTIMESTAMP, 'K230029');

-- [8] PMO·품질관리팀 팀장 (K230034)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230034' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '180',
        PT_C_NM      = '팀장',
        TEM_C        = '18010',
        TEM_NM       = 'PMO·품질관리팀',
        USR_NM       = '김피엠오',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230034'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230034', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '180', '팀장', '18010', 'PMO·품질관리팀', '김피엠오', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230034', SYSTIMESTAMP, 'K230034');

-- [9] 정보보호기획팀 팀장 (K230035)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230035' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '183',
        PT_C_NM      = '팀장',
        TEM_C        = '18301',
        TEM_NM       = '정보보호기획팀',
        USR_NM       = '김보안팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230035'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230035', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '183', '팀장', '18301', '정보보호기획팀', '김보안팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230035', SYSTIMESTAMP, 'K230035');

-- [10] 정보보호기획팀 대리 (K230036)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230036' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '183',
        PT_C_NM      = '대리',
        TEM_C        = '18301',
        TEM_NM       = '정보보호기획팀',
        USR_NM       = '김보안',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230036'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230036', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '183', '대리', '18301', '정보보호기획팀', '김보안', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230036', SYSTIMESTAMP, 'K230036');

-- [11] AI·디지털전략팀 팀장 (K230037)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230037' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '185',
        PT_C_NM      = '팀장',
        TEM_C        = '18501',
        TEM_NM       = 'AI·디지털전략팀',
        USR_NM       = '김에이아이',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230037'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230037', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '185', '팀장', '18501', 'AI·디지털전략팀', '김에이아이', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230037', SYSTIMESTAMP, 'K230037');

-- [12] 미래전략팀 팀장 (K230038)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230038' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '140',
        PT_C_NM      = '팀장',
        TEM_C        = '14011',
        TEM_NM       = '미래전략팀',
        USR_NM       = '김미래팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230038'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230038', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '140', '팀장', '14011', '미래전략팀', '김미래팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230038', SYSTIMESTAMP, 'K230038');

-- [13] 조직·평가팀 팀장 (K230039)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230039' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '120',
        PT_C_NM      = '팀장',
        TEM_C        = '12003',
        TEM_NM       = '조직·평가팀',
        USR_NM       = '김조평팀장',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230039'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230039', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '120', '팀장', '12003', '조직·평가팀', '김조평팀장', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230039', SYSTIMESTAMP, 'K230039');

-- [14] 조직·평가팀 과장 (K230040)
MERGE INTO TPRMPP_CUSERI T
USING (SELECT 'K230040' AS ENO FROM DUAL) S
ON (T.ENO = S.ENO)
WHEN MATCHED THEN
    UPDATE SET
        USR_ECY_PWD  = '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=',
        BBR_C        = '120',
        PT_C_NM      = '과장',
        TEM_C        = '12003',
        TEM_NM       = '조직·평가팀',
        USR_NM       = '김조평',
        GUID         = SYS_GUID(),
        LST_CHG_DTM  = SYSTIMESTAMP,
        LST_CHG_USID = 'K230040'
WHEN NOT MATCHED THEN
    INSERT (ENO, USR_ECY_PWD, BBR_C, PT_C_NM, TEM_C, TEM_NM, USR_NM, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('K230040', '/r2T8EvaGuwNN0+P0BTQYlJZNP6x8bge58ZNYfZrhLE=', '120', '과장', '12003', '조직·평가팀', '김조평', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230040', SYSTIMESTAMP, 'K230040');


-- ── TPRMPP_CROLEI: 일반사용자 권한 부여 (없으면 INSERT, 있으면 무시) ────────

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230028' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230028', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPAD001' AS ATH_ID, 'K230028' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPAD001', 'K230028', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230028', SYSTIMESTAMP, 'K230028');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K000001' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K000001', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K000001', SYSTIMESTAMP, 'K000001');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPAD001' AS ATH_ID, 'K000001' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPAD001', 'K000001', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K000001', SYSTIMESTAMP, 'K000001');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230033' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230033', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230033', SYSTIMESTAMP, 'K230033');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230030' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230030', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230030', SYSTIMESTAMP, 'K230030');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230032' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230032', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230032', SYSTIMESTAMP, 'K230032');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230031' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230031', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230031', SYSTIMESTAMP, 'K230031');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230029' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230029', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230029', SYSTIMESTAMP, 'K230029');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230034' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230034', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230034', SYSTIMESTAMP, 'K230034');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230035' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230035', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230035', SYSTIMESTAMP, 'K230035');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230036' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230036', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230036', SYSTIMESTAMP, 'K230036');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230037' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230037', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230037', SYSTIMESTAMP, 'K230037');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230038' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230038', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230038', SYSTIMESTAMP, 'K230038');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230039' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230039', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230039', SYSTIMESTAMP, 'K230039');

MERGE INTO TPRMPP_CROLEI T
USING (SELECT 'ITPZZ001' AS ATH_ID, 'K230040' AS ENO FROM DUAL) S
ON (T.ATH_ID = S.ATH_ID AND T.ENO = S.ENO)
WHEN NOT MATCHED THEN
    INSERT (ATH_ID, ENO, USE_YN, DEL_YN, GUID, GUID_PRG_SNO, FST_ENR_DTM, FST_ENR_USID, LST_CHG_DTM, LST_CHG_USID)
    VALUES ('ITPZZ001', 'K230040', 'Y', 'N', SYS_GUID(), 1, SYSTIMESTAMP, 'K230040', SYSTIMESTAMP, 'K230040');

COMMIT;
