-- ============================================================
-- 적용 후 검증 스크립트
-- ============================================================
-- 적용: SQL*Plus에서 @05_verify.sql
-- 기대: 모든 결과가 'OK' 또는 정확한 카운트
-- ============================================================

SET LINESIZE 200
SET PAGESIZE 100
SET FEEDBACK ON
COL chk    FORMAT A40
COL result FORMAT A40

PROMPT === 20 테이블 존재 (기대=20) ===
SELECT 'TABLES_COUNT' AS chk, COUNT(*) || ' / 20' AS result FROM user_tables
WHERE table_name IN (
  'TPRMPP_BASCTM','TPRMPP_BCHKLM','TPRMPP_BCMMTM','TPRMPP_BEVALM','TPRMPP_BMQNAM',
  'TPRMPP_BPERFM','TPRMPP_BPOVWM','TPRMPP_BPQNAM','TPRMPP_BRSLTM','TPRMPP_BSCHDM',
  'TPRMPP_BASCTL','TPRMPP_BCHKLL','TPRMPP_BCMMTL','TPRMPP_BEVALL','TPRMPP_BMQNAL',
  'TPRMPP_BPERFL','TPRMPP_BPOVWL','TPRMPP_BPQNAL','TPRMPP_BRSLTL','TPRMPP_BSCHDL');

PROMPT === 시퀀스 12개 존재 ===
SELECT 'SEQUENCES_COUNT' AS chk, COUNT(*) || ' / 12' AS result FROM user_sequences
WHERE sequence_name IN (
  'SEQ_BASCTM','SEQ_BCHKLM','SEQ_BMQNAL','SEQ_BBUGTL','SEQ_BCHKLL','SEQ_BCMMTL',
  'SEQ_BEVALL','SEQ_BPERFL','SEQ_BPOVWL','SEQ_BPQNAL','SEQ_BRSLTL','SEQ_BSCHDL'
);

PROMPT === PK 표준 명명 (기대=20: PK_*) ===
SELECT 'PK_NAMES' AS chk, COUNT(*) || ' / 20' AS result FROM user_constraints
WHERE constraint_type='P'
  AND constraint_name LIKE 'PK_%'
  AND table_name IN (
  'TPRMPP_BASCTM','TPRMPP_BCHKLM','TPRMPP_BCMMTM','TPRMPP_BEVALM','TPRMPP_BMQNAM',
  'TPRMPP_BPERFM','TPRMPP_BPOVWM','TPRMPP_BPQNAM','TPRMPP_BRSLTM','TPRMPP_BSCHDM',
  'TPRMPP_BASCTL','TPRMPP_BCHKLL','TPRMPP_BCMMTL','TPRMPP_BEVALL','TPRMPP_BMQNAL',
  'TPRMPP_BPERFL','TPRMPP_BPOVWL','TPRMPP_BPQNAL','TPRMPP_BRSLTL','TPRMPP_BSCHDL');

PROMPT === 잔존 옛 이름 검사 (기대=0: 모두 0이어야 정상) ===
SELECT 'TAAABB_INDEX_REMAIN'  AS chk, COUNT(*) AS result FROM user_indexes     WHERE index_name LIKE '%TAAABB%';
SELECT 'TAAABB_CONST_REMAIN'  AS chk, COUNT(*) AS result FROM user_constraints WHERE constraint_name LIKE '%TAAABB%';
SELECT 'TP_COL_REMAIN'        AS chk, COUNT(*) AS result FROM user_tab_columns WHERE column_name='CHG_TC' AND table_name IN ('TPRMPP_BASCTL','TPRMPP_BCHKLL','TPRMPP_BCMMTL','TPRMPP_BEVALL','TPRMPP_BMQNAL','TPRMPP_BPERFL','TPRMPP_BPOVWL','TPRMPP_BPQNAL','TPRMPP_BRSLTL','TPRMPP_BSCHDL');
SELECT 'STS_OLD_COL_REMAIN'   AS chk, COUNT(*) AS result FROM user_tab_columns WHERE column_name IN ('ASCT_STS','DBR_TP','VLR_TP','KPN_TP','CNRC_PLC','CKG_OPNN','SYN_OPNN','GL_NV','MSM_MANR','MSM_TPM','EDRT','NCS','PRJ_BG','PRJ_TRM','XPT_EFF','PRJ_BG_AMR') AND table_name IN ('TPRMPP_BASCTL','TPRMPP_BASCTM','TPRMPP_BCHKLM','TPRMPP_BCHKLL','TPRMPP_BCMMTL','TPRMPP_BCMMTM','TPRMPP_BEVALL','TPRMPP_BEVALM','TPRMPP_BPERFL','TPRMPP_BPERFM','TPRMPP_BPOVWL','TPRMPP_BPOVWM','TPRMPP_BPQNAL','TPRMPP_BPQNAM','TPRMPP_BRSLTL','TPRMPP_BRSLTM','TPRMPP_BSCHDL','TPRMPP_BSCHDM');

PROMPT === 시드 적용 카운트 ===
SELECT 'CCODEM_TOTAL' AS chk, COUNT(*) || ' (기대>=20)' AS result FROM TPRMPP_CCODEM;
SELECT 'CCODEM_ASCT_STS_C' AS chk, COUNT(*) || ' / 13' AS result FROM TPRMPP_CCODEM WHERE C_ID='ASCT_STS_C';
SELECT 'CCODEM_DBR_TC'     AS chk, COUNT(*) || ' / 5'  AS result FROM TPRMPP_CCODEM WHERE C_ID='DBR_TC';
SELECT 'CCODEM_VLR_TC'     AS chk, COUNT(*) || ' / 3'  AS result FROM TPRMPP_CCODEM WHERE C_ID='VLR_TC';
SELECT 'CCODEM_CKG_ITM_C'  AS chk, COUNT(*) || ' / 6'  AS result FROM TPRMPP_CCODEM WHERE C_ID='CKG_ITM_C';
SELECT 'CCODEM_KPN_TC'     AS chk, COUNT(*) || ' / 2'  AS result FROM TPRMPP_CCODEM WHERE C_ID='KPN_TC';
SELECT 'CUSERI_K230028'    AS chk, COUNT(*) || ' (기대=1)' AS result FROM TPRMPP_CUSERI WHERE ENO='K230028';

EXIT;
