-- 공통코드 마이그레이션 검증 쿼리 (Flyway 비대상, 수동 실행)
SET LINESIZE 200
SET PAGESIZE 100

PROMPT === 백필 대상 컬럼 현재 분포 ===
SELECT 'BCOSTM.DFR_CLE_C' col, DFR_CLE_C v, COUNT(*) c FROM ITPAPP.TPRMPP_BCOSTM WHERE DEL_YN='N' GROUP BY DFR_CLE_C
UNION ALL SELECT 'BTERMM.DFR_CLE_C', DFR_CLE_C, COUNT(*) FROM ITPAPP.TPRMPP_BTERMM GROUP BY DFR_CLE_C
UNION ALL SELECT 'BCOSTM.TMN_YN', TMN_YN, COUNT(*) FROM ITPAPP.TPRMPP_BCOSTM WHERE DEL_YN='N' GROUP BY TMN_YN
UNION ALL SELECT 'CAPPLM.APF_PRG_STS_C', APF_PRG_STS_C, COUNT(*) FROM ITPAPP.TPRMPP_CAPPLM WHERE DEL_YN='N' GROUP BY APF_PRG_STS_C
UNION ALL SELECT 'BTERMM.IT_PTL_TMN_SVC_TC', IT_PTL_TMN_SVC_TC, COUNT(*) FROM ITPAPP.TPRMPP_BTERMM GROUP BY IT_PTL_TMN_SVC_TC
UNION ALL SELECT 'BTERMM.IT_PTL_TMN_KD_TC', IT_PTL_TMN_KD_TC, COUNT(*) FROM ITPAPP.TPRMPP_BTERMM GROUP BY IT_PTL_TMN_KD_TC
ORDER BY 1,2;

PROMPT === 고아 검출: 업무 컬럼 값이 CCODEM(신규 그룹)에 없는 행 ===
SELECT 'BCOSTM.DFR_CLE_C' src, c.DFR_CLE_C v, COUNT(*) n
FROM ITPAPP.TPRMPP_BCOSTM c
WHERE c.DEL_YN='N' AND c.DFR_CLE_C IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM ITPAPP.TPRMPP_CCODEM m WHERE m.CO_C_ID='DFR_CLE_C' AND m.CDVA_ID=c.DFR_CLE_C AND m.DEL_YN='N')
GROUP BY c.DFR_CLE_C
UNION ALL
SELECT 'BTERMM.DFR_CLE_C', c.DFR_CLE_C, COUNT(*)
FROM ITPAPP.TPRMPP_BTERMM c
WHERE c.DFR_CLE_C IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM ITPAPP.TPRMPP_CCODEM m WHERE m.CO_C_ID='DFR_CLE_C' AND m.CDVA_ID=c.DFR_CLE_C AND m.DEL_YN='N')
GROUP BY c.DFR_CLE_C
UNION ALL
SELECT 'CAPPLM.APF_PRG_STS_C', c.APF_PRG_STS_C, COUNT(*)
FROM ITPAPP.TPRMPP_CAPPLM c
WHERE c.DEL_YN='N' AND c.APF_PRG_STS_C IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM ITPAPP.TPRMPP_CCODEM m WHERE m.CO_C_ID='APF_PRG_STS_C' AND m.CDVA_ID=c.APF_PRG_STS_C AND m.DEL_YN='N')
GROUP BY c.APF_PRG_STS_C;

PROMPT === CCODEL 시퀀스 실재 ===
SELECT SEQUENCE_NAME FROM USER_SEQUENCES WHERE SEQUENCE_NAME LIKE '%CCODEL%';

PROMPT === EDRT 업무 저장 컬럼 실재 ===
SELECT TABLE_NAME, COLUMN_NAME FROM USER_TAB_COLS WHERE COLUMN_NAME LIKE '%EDRT%' ORDER BY 1,2;

PROMPT === CCODEM 그룹 현황(영향 그룹) ===
SELECT CO_C_ID, COUNT(*) n FROM ITPAPP.TPRMPP_CCODEM WHERE DEL_YN='N'
  AND CO_C_ID IN ('TMN_USG','TMN_MAGR','TMN_KD','TCHN_TP','SD','RPR_STS','PRJ_PUL_PTT','MN_USR',
    'IT_MNGC_TP','IOE','INFM_SVC','EDRT_MNGC','EDRT_CPIT','DFR_CLE','CUR','APF_STS','ABUS_C','PUL_DTT',
    'IT_PTL_TMN_SVC_TC','IT_PTL_TMN_KD_TC','IT_PTL_TCHN_TP_TC','SD_TC','IT_PTL_RPR_STS_TC','EXE_PTT_YN','CST_TP_TC','TMN_YN',
    'IOE_C','INFM_SVC_TC','IT_PTL_EDRT_TC','DFR_CLE_C','CUR_C','APF_PRG_STS_C','BG_UNT_ABUS_C','ABUS_TC')
GROUP BY CO_C_ID ORDER BY CO_C_ID;
