-- 공통코드 마이그레이션 수동 롤백 (V20260606_001/002/003)
-- 주의: 업무데이터 백필(DFR_CLE_C/APF/EDRT)과 Btermm 랜덤채움은 원복 불가(백업 미보존).
--       CCODEM은 백업 테이블에서 완전 복원 가능.
SET DEFINE OFF

-- 1) CCODEM 복원: 마이그레이션 적재분 제거 후 백업 재적재
DELETE FROM ITPAPP.TPRMPP_CCODEM WHERE FST_ENR_USID='MIGRATION';
INSERT INTO ITPAPP.TPRMPP_CCODEM SELECT * FROM ITPAPP.TPRMPP_CCODEM_BAK_20260606
  WHERE (CO_C_ID, CDVA_ID, STT_DTM) NOT IN (SELECT CO_C_ID, CDVA_ID, STT_DTM FROM ITPAPP.TPRMPP_CCODEM);

-- 2) CCODEL 감사분 제거
DELETE FROM ITPAPP.TPRMPP_CCODEL WHERE CHG_USID='MIGRATION';

COMMIT;
-- 업무데이터/컬럼폭은 필요 시 별도 스냅샷에서 복구. Btermm 폭 확장(VARCHAR2(3))은 되돌리지 않아도 무해.
